// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/notice.yaml

// Package api exposes notice transport adapters.
package api

import "github.com/weouc-plus/campus-platform/internal/modules/notice/application"

// Handler is the extension point for generated OpenAPI operations.
type Handler struct{ service *application.Service }

// NewHandler creates a notice API handler.
func NewHandler(service *application.Service) *Handler { return &Handler{service: service} }
