// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/notice.yaml

// Package infrastructure implements notice persistence contracts.
package infrastructure

import (
	"context"
	"fmt"

	platformquery "github.com/weouc-plus/campus-platform/internal/infrastructure/mysql/query"
	"github.com/weouc-plus/campus-platform/internal/modules/notice/domain"
	"gorm.io/gorm"
)

// Repository is the generated type-safe GORM Query persistence adapter.
type Repository struct{ query *platformquery.Query }

// NewRepository creates a notice repository.
func NewRepository(db *gorm.DB) *Repository { return &Repository{query: platformquery.Use(db)} }

// Create inserts a Notice.
func (r *Repository) Create(ctx context.Context, value *domain.Notice) error {
	if err := r.query.Notice.WithContext(ctx).Create(value); err != nil {
		return fmt.Errorf("create notice: %w", err)
	}
	return nil
}

// Get returns one Notice by primary key.
func (r *Repository) Get(ctx context.Context, id uint64) (*domain.Notice, error) {
	q := r.query.Notice
	value, err := q.WithContext(ctx).Where(q.ID.Eq(id)).First()
	if err != nil {
		return nil, fmt.Errorf("get notice: %w", err)
	}
	return value, nil
}

// List returns a deterministic page ordered by primary key.
func (r *Repository) List(ctx context.Context, page, pageSize int) ([]domain.Notice, int64, error) {
	if page < 1 {
		page = 1
	}
	if pageSize < 1 {
		pageSize = 20
	}
	q := r.query.Notice
	dao := q.WithContext(ctx)
	total, err := dao.Count()
	if err != nil {
		return nil, 0, fmt.Errorf("count notice: %w", err)
	}
	values, err := dao.Order(q.ID).Offset((page - 1) * pageSize).Limit(pageSize).Find()
	if err != nil {
		return nil, 0, fmt.Errorf("list notice: %w", err)
	}
	rows := make([]domain.Notice, len(values))
	for i := range values {
		rows[i] = *values[i]
	}
	return rows, total, nil
}

// Update saves a Notice by primary key.
func (r *Repository) Update(ctx context.Context, value *domain.Notice) error {
	if err := r.query.Notice.WithContext(ctx).Save(value); err != nil {
		return fmt.Errorf("update notice: %w", err)
	}
	return nil
}

// Delete removes a Notice by primary key.
func (r *Repository) Delete(ctx context.Context, id uint64) error {
	q := r.query.Notice
	if _, err := q.WithContext(ctx).Where(q.ID.Eq(id)).Delete(); err != nil {
		return fmt.Errorf("delete notice: %w", err)
	}
	return nil
}

var _ domain.Repository = (*Repository)(nil)
