// Code generated by campusctl from .agent/modules.json. DO NOT EDIT.

package main

import (
	noticedomain "github.com/weouc-plus/campus-platform/internal/modules/notice/domain"
	"gorm.io/gen"
)

func applyGeneratedModules(generator *gen.Generator) {
	generator.ApplyBasic(
		noticedomain.Notice{},
		noticedomain.NoticeAudience{},
		noticedomain.NoticeRecipient{},
		noticedomain.NoticeDelivery{},
		noticedomain.OutboxEvent{},
	)
}
