// Code generated by campusctl from .agent/modules.json. DO NOT EDIT.

package main

import (
	academic_verificationdomain "github.com/weouc-plus/campus-platform/internal/modules/academic_verification/domain"
	activitydomain "github.com/weouc-plus/campus-platform/internal/modules/activity/domain"
	carpooldomain "github.com/weouc-plus/campus-platform/internal/modules/carpool/domain"
	commentdomain "github.com/weouc-plus/campus-platform/internal/modules/comment/domain"
	erranddomain "github.com/weouc-plus/campus-platform/internal/modules/errand/domain"
	marketplacedomain "github.com/weouc-plus/campus-platform/internal/modules/marketplace/domain"
	noticedomain "github.com/weouc-plus/campus-platform/internal/modules/notice/domain"
	paymentdomain "github.com/weouc-plus/campus-platform/internal/modules/payment/domain"
	tradedomain "github.com/weouc-plus/campus-platform/internal/modules/trade/domain"
	"gorm.io/gen"
)

func applyGeneratedModules(generator *gen.Generator) {
	generator.ApplyBasic(
		academic_verificationdomain.AcademicIdentity{},
		academic_verificationdomain.AcademicVerificationMaterial{},
		academic_verificationdomain.AcademicVerificationRequest{},
		activitydomain.Activity{},
		activitydomain.ActivityRegistration{},
		carpooldomain.Trip{},
		carpooldomain.Participant{},
		commentdomain.Comment{},
		commentdomain.CommentPin{},
		erranddomain.Task{},
		erranddomain.Transition{},
		marketplacedomain.Listing{},
		marketplacedomain.ListingImage{},
		marketplacedomain.MarketplaceReservation{},
		noticedomain.Notice{},
		noticedomain.NoticeAudience{},
		noticedomain.NoticeRecipient{},
		noticedomain.NoticeDelivery{},
		noticedomain.OutboxEvent{},
		paymentdomain.PaymentIntent{},
		paymentdomain.PaymentTransaction{},
		paymentdomain.PaymentRefund{},
		paymentdomain.PaymentCallback{},
		tradedomain.Order{},
		tradedomain.OrderTransition{},
	)
}
