// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/activity.yaml

// Package application coordinates activity use cases.
package application

import (
	"context"

	"github.com/weouc-plus/campus-platform/internal/modules/activity/domain"
)

// Service coordinates generated CRUD operations and handwritten domain rules.
type Service struct{ repository domain.Repository }

// NewService creates a activity application service.
func NewService(repository domain.Repository) *Service { return &Service{repository: repository} }

// Create persists a new Activity.
func (s *Service) Create(ctx context.Context, value *domain.Activity) error {
	return s.repository.Create(ctx, value)
}

// Get returns one Activity by ID.
func (s *Service) Get(ctx context.Context, id uint64) (*domain.Activity, error) {
	return s.repository.Get(ctx, id)
}

// List returns a page of Activity values.
func (s *Service) List(ctx context.Context, page, pageSize int) ([]domain.Activity, int64, error) {
	return s.repository.List(ctx, page, pageSize)
}

// Update persists an existing Activity.
func (s *Service) Update(ctx context.Context, value *domain.Activity) error {
	return s.repository.Update(ctx, value)
}
