// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/trade.yaml

// Package trade wires the generated module components.
package trade

import (
	"github.com/weouc-plus/campus-platform/internal/modules/trade/api"
	"github.com/weouc-plus/campus-platform/internal/modules/trade/application"
	"github.com/weouc-plus/campus-platform/internal/modules/trade/infrastructure"
	"gorm.io/gorm"
)

// Module contains the public runtime components of the trade module.
type Module struct{ Handler *api.Handler }

// New creates a trade module from shared infrastructure.
func New(db *gorm.DB) *Module {
	repository := infrastructure.NewRepository(db)
	service := application.NewService(repository)
	return &Module{Handler: api.NewHandler(service)}
}
