// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/payment.yaml

// Package application coordinates payment use cases.
package application

import (
	"context"

	"github.com/weouc-plus/campus-platform/internal/modules/payment/domain"
)

// Service coordinates generated CRUD operations and handwritten domain rules.
type Service struct{ repository domain.Repository }

// NewService creates a payment application service.
func NewService(repository domain.Repository) *Service { return &Service{repository: repository} }

// Create persists a new PaymentIntent.
func (s *Service) Create(ctx context.Context, value *domain.PaymentIntent) error {
	return s.repository.Create(ctx, value)
}

// Get returns one PaymentIntent by ID.
func (s *Service) Get(ctx context.Context, id uint64) (*domain.PaymentIntent, error) {
	return s.repository.Get(ctx, id)
}

// List returns a page of PaymentIntent values.
func (s *Service) List(ctx context.Context, page, pageSize int) ([]domain.PaymentIntent, int64, error) {
	return s.repository.List(ctx, page, pageSize)
}

// Update persists an existing PaymentIntent.
func (s *Service) Update(ctx context.Context, value *domain.PaymentIntent) error {
	return s.repository.Update(ctx, value)
}
