// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/carpool.yaml

// Package api exposes carpool transport adapters.
package api

import "github.com/weouc-plus/campus-platform/internal/modules/carpool/application"

// Handler is the extension point for generated OpenAPI operations.
type Handler struct{ service *application.Service }

// NewHandler creates a carpool API handler.
func NewHandler(service *application.Service) *Handler { return &Handler{service: service} }
