// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/payment.yaml

// Package infrastructure implements payment persistence contracts.
package infrastructure

import (
	"context"
	"fmt"

	platformquery "github.com/weouc-plus/campus-platform/internal/infrastructure/mysql/query"
	"github.com/weouc-plus/campus-platform/internal/modules/payment/domain"
	"gorm.io/gorm"
)

// Repository is the generated type-safe GORM Query persistence adapter.
type Repository struct{ query *platformquery.Query }

// NewRepository creates a payment repository.
func NewRepository(db *gorm.DB) *Repository { return &Repository{query: platformquery.Use(db)} }

// Create inserts a PaymentIntent.
func (r *Repository) Create(ctx context.Context, value *domain.PaymentIntent) error {
	if err := r.query.PaymentIntent.WithContext(ctx).Create(value); err != nil {
		return fmt.Errorf("create payment: %w", err)
	}
	return nil
}

// Get returns one PaymentIntent by primary key.
func (r *Repository) Get(ctx context.Context, id uint64) (*domain.PaymentIntent, error) {
	q := r.query.PaymentIntent
	value, err := q.WithContext(ctx).Where(q.ID.Eq(id)).First()
	if err != nil {
		return nil, fmt.Errorf("get payment: %w", err)
	}
	return value, nil
}

// List returns a deterministic page ordered by primary key.
func (r *Repository) List(ctx context.Context, page, pageSize int) ([]domain.PaymentIntent, int64, error) {
	if page < 1 {
		page = 1
	}
	if pageSize < 1 {
		pageSize = 20
	}
	q := r.query.PaymentIntent
	dao := q.WithContext(ctx)
	total, err := dao.Count()
	if err != nil {
		return nil, 0, fmt.Errorf("count payment: %w", err)
	}
	values, err := dao.Order(q.ID).Offset((page - 1) * pageSize).Limit(pageSize).Find()
	if err != nil {
		return nil, 0, fmt.Errorf("list payment: %w", err)
	}
	rows := make([]domain.PaymentIntent, len(values))
	for i := range values {
		rows[i] = *values[i]
	}
	return rows, total, nil
}

// Update saves a PaymentIntent by primary key.
func (r *Repository) Update(ctx context.Context, value *domain.PaymentIntent) error {
	if err := r.query.PaymentIntent.WithContext(ctx).Save(value); err != nil {
		return fmt.Errorf("update payment: %w", err)
	}
	return nil
}

var _ domain.Repository = (*Repository)(nil)
