// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/academic_verification.yaml

// Package api exposes academic_verification transport adapters.
package api

import "github.com/weouc-plus/campus-platform/internal/modules/academic_verification/application"

// Handler is the extension point for generated OpenAPI operations.
type Handler struct{ service *application.Service }

// NewHandler creates a academic_verification API handler.
func NewHandler(service *application.Service) *Handler { return &Handler{service: service} }
