// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/errand.yaml

// Package application coordinates errand use cases.
package application

import (
	"context"

	"github.com/weouc-plus/campus-platform/internal/modules/errand/domain"
)

// Service coordinates generated CRUD operations and handwritten domain rules.
type Service struct{ repository domain.Repository }

// NewService creates a errand application service.
func NewService(repository domain.Repository) *Service { return &Service{repository: repository} }

// Create persists a new Task.
func (s *Service) Create(ctx context.Context, value *domain.Task) error {
	return s.repository.Create(ctx, value)
}

// Get returns one Task by ID.
func (s *Service) Get(ctx context.Context, id uint64) (*domain.Task, error) {
	return s.repository.Get(ctx, id)
}

// List returns a page of Task values.
func (s *Service) List(ctx context.Context, page, pageSize int) ([]domain.Task, int64, error) {
	return s.repository.List(ctx, page, pageSize)
}

// Update persists an existing Task.
func (s *Service) Update(ctx context.Context, value *domain.Task) error {
	return s.repository.Update(ctx, value)
}
