// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/academic_verification.yaml

package httpapi

import (
	"github.com/gin-gonic/gin"
	"github.com/weouc-plus/campus-platform/internal/api/generated"
)

// GetAcademicVerification adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) GetAcademicVerification(c *gin.Context) {
	h.getAcademicVerification(c)
}

// VerifyAcademicCredentials adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) VerifyAcademicCredentials(c *gin.Context, params generated.VerifyAcademicCredentialsParams) {
	setGeneratedParams(c, "VerifyAcademicCredentials", params)
	h.idempotent(c, "VerifyAcademicCredentials", func() {
		h.verifyAcademicCredentials(c)
	})
}

// UploadAcademicVerificationMaterial adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) UploadAcademicVerificationMaterial(c *gin.Context) {
	h.uploadAcademicVerificationMaterial(c)
}

// SubmitStudentCardVerification adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) SubmitStudentCardVerification(c *gin.Context, params generated.SubmitStudentCardVerificationParams) {
	setGeneratedParams(c, "SubmitStudentCardVerification", params)
	h.idempotent(c, "SubmitStudentCardVerification", func() {
		h.submitStudentCardVerification(c)
	})
}

// RevokeAcademicIdentity adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) RevokeAcademicIdentity(c *gin.Context, id uint64, params generated.RevokeAcademicIdentityParams) {
	setGeneratedPathParam(c, "id", id)
	setGeneratedParams(c, "RevokeAcademicIdentity", params)
	h.idempotent(c, "RevokeAcademicIdentity", func() {
		h.revokeAcademicIdentity(c)
	})
}

// GetAdminAcademicVerificationMaterial adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) GetAdminAcademicVerificationMaterial(c *gin.Context, id uint64) {
	setGeneratedPathParam(c, "id", id)
	h.getAdminAcademicVerificationMaterial(c)
}

// ListAdminAcademicVerificationRequests adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) ListAdminAcademicVerificationRequests(c *gin.Context, params generated.ListAdminAcademicVerificationRequestsParams) {
	setGeneratedParams(c, "ListAdminAcademicVerificationRequests", params)
	h.listAdminAcademicVerificationRequests(c)
}

// GetAdminAcademicVerificationRequest adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) GetAdminAcademicVerificationRequest(c *gin.Context, id uint64) {
	setGeneratedPathParam(c, "id", id)
	h.getAdminAcademicVerificationRequest(c)
}

// ApproveAcademicVerificationRequest adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) ApproveAcademicVerificationRequest(c *gin.Context, id uint64, params generated.ApproveAcademicVerificationRequestParams) {
	setGeneratedPathParam(c, "id", id)
	setGeneratedParams(c, "ApproveAcademicVerificationRequest", params)
	h.idempotent(c, "ApproveAcademicVerificationRequest", func() {
		h.approveAcademicVerificationRequest(c)
	})
}

// RejectAcademicVerificationRequest adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) RejectAcademicVerificationRequest(c *gin.Context, id uint64, params generated.RejectAcademicVerificationRequestParams) {
	setGeneratedPathParam(c, "id", id)
	setGeneratedParams(c, "RejectAcademicVerificationRequest", params)
	h.idempotent(c, "RejectAcademicVerificationRequest", func() {
		h.rejectAcademicVerificationRequest(c)
	})
}
