// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/activity.yaml

package httpapi

import (
	"github.com/gin-gonic/gin"
	"github.com/weouc-plus/campus-platform/internal/api/generated"
)

// ListActivities adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) ListActivities(c *gin.Context, params generated.ListActivitiesParams) {
	setGeneratedParams(c, "ListActivities", params)
	h.listActivities(c)
}

// ListMyActivityRegistrations adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) ListMyActivityRegistrations(c *gin.Context, params generated.ListMyActivityRegistrationsParams) {
	setGeneratedParams(c, "ListMyActivityRegistrations", params)
	h.listMyActivityRegistrations(c)
}

// GetActivity adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) GetActivity(c *gin.Context, id uint64) {
	setGeneratedPathParam(c, "id", id)
	h.getActivity(c)
}

// CreateActivityRegistration adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) CreateActivityRegistration(c *gin.Context, id uint64, params generated.CreateActivityRegistrationParams) {
	setGeneratedPathParam(c, "id", id)
	setGeneratedParams(c, "CreateActivityRegistration", params)
	if !h.requireAcademicVerification(c) {
		return
	}
	h.idempotent(c, "CreateActivityRegistration", func() {
		h.createActivityRegistration(c)
	})
}

// CancelMyActivityRegistration adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) CancelMyActivityRegistration(c *gin.Context, id uint64, params generated.CancelMyActivityRegistrationParams) {
	setGeneratedPathParam(c, "id", id)
	setGeneratedParams(c, "CancelMyActivityRegistration", params)
	if !h.requireAcademicVerification(c) {
		return
	}
	h.idempotent(c, "CancelMyActivityRegistration", func() {
		h.cancelMyActivityRegistration(c)
	})
}

// ListAdminActivities adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) ListAdminActivities(c *gin.Context, params generated.ListAdminActivitiesParams) {
	setGeneratedParams(c, "ListAdminActivities", params)
	h.listAdminActivities(c)
}

// CreateAdminActivity adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) CreateAdminActivity(c *gin.Context, params generated.CreateAdminActivityParams) {
	setGeneratedParams(c, "CreateAdminActivity", params)
	h.idempotent(c, "CreateAdminActivity", func() {
		h.createAdminActivity(c)
	})
}

// GetAdminActivity adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) GetAdminActivity(c *gin.Context, id uint64) {
	setGeneratedPathParam(c, "id", id)
	h.getAdminActivity(c)
}

// UpdateAdminActivity adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) UpdateAdminActivity(c *gin.Context, id uint64, params generated.UpdateAdminActivityParams) {
	setGeneratedPathParam(c, "id", id)
	setGeneratedParams(c, "UpdateAdminActivity", params)
	h.idempotent(c, "UpdateAdminActivity", func() {
		h.updateAdminActivity(c)
	})
}

// ApproveAdminActivity adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) ApproveAdminActivity(c *gin.Context, id uint64, params generated.ApproveAdminActivityParams) {
	setGeneratedPathParam(c, "id", id)
	setGeneratedParams(c, "ApproveAdminActivity", params)
	h.idempotent(c, "ApproveAdminActivity", func() {
		h.approveAdminActivity(c)
	})
}

// CancelAdminActivity adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) CancelAdminActivity(c *gin.Context, id uint64, params generated.CancelAdminActivityParams) {
	setGeneratedPathParam(c, "id", id)
	setGeneratedParams(c, "CancelAdminActivity", params)
	h.idempotent(c, "CancelAdminActivity", func() {
		h.cancelAdminActivity(c)
	})
}

// FinishAdminActivity adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) FinishAdminActivity(c *gin.Context, id uint64, params generated.FinishAdminActivityParams) {
	setGeneratedPathParam(c, "id", id)
	setGeneratedParams(c, "FinishAdminActivity", params)
	h.idempotent(c, "FinishAdminActivity", func() {
		h.finishAdminActivity(c)
	})
}

// PublishAdminActivity adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) PublishAdminActivity(c *gin.Context, id uint64, params generated.PublishAdminActivityParams) {
	setGeneratedPathParam(c, "id", id)
	setGeneratedParams(c, "PublishAdminActivity", params)
	h.idempotent(c, "PublishAdminActivity", func() {
		h.publishAdminActivity(c)
	})
}

// RejectAdminActivity adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) RejectAdminActivity(c *gin.Context, id uint64, params generated.RejectAdminActivityParams) {
	setGeneratedPathParam(c, "id", id)
	setGeneratedParams(c, "RejectAdminActivity", params)
	h.idempotent(c, "RejectAdminActivity", func() {
		h.rejectAdminActivity(c)
	})
}

// SubmitAdminActivityReview adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) SubmitAdminActivityReview(c *gin.Context, id uint64, params generated.SubmitAdminActivityReviewParams) {
	setGeneratedPathParam(c, "id", id)
	setGeneratedParams(c, "SubmitAdminActivityReview", params)
	h.idempotent(c, "SubmitAdminActivityReview", func() {
		h.submitAdminActivityReview(c)
	})
}
