// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/activity.yaml

package httpapi

import (
	"github.com/gin-gonic/gin"
	"github.com/weouc-plus/campus-platform/internal/api/generated"
)

// ListActivities adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) ListActivities(c *gin.Context, _ generated.ListActivitiesParams) {
	h.listActivities(c)
}

// ListMyActivityRegistrations adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) ListMyActivityRegistrations(c *gin.Context, _ generated.ListMyActivityRegistrationsParams) {
	h.listMyActivityRegistrations(c)
}

// GetActivity adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) GetActivity(c *gin.Context, _ uint64) {
	h.getActivity(c)
}

// CreateActivityRegistration adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) CreateActivityRegistration(c *gin.Context, _ uint64, _ generated.CreateActivityRegistrationParams) {
	h.createActivityRegistration(c)
}

// CancelMyActivityRegistration adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) CancelMyActivityRegistration(c *gin.Context, _ uint64) {
	h.cancelMyActivityRegistration(c)
}

// ListAdminActivities adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) ListAdminActivities(c *gin.Context, _ generated.ListAdminActivitiesParams) {
	h.listAdminActivities(c)
}

// CreateAdminActivity adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) CreateAdminActivity(c *gin.Context) {
	h.createAdminActivity(c)
}

// GetAdminActivity adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) GetAdminActivity(c *gin.Context, _ uint64) {
	h.getAdminActivity(c)
}

// UpdateAdminActivity adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) UpdateAdminActivity(c *gin.Context, _ uint64) {
	h.updateAdminActivity(c)
}

// ApproveAdminActivity adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) ApproveAdminActivity(c *gin.Context, _ uint64) {
	h.approveAdminActivity(c)
}

// CancelAdminActivity adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) CancelAdminActivity(c *gin.Context, _ uint64) {
	h.cancelAdminActivity(c)
}

// FinishAdminActivity adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) FinishAdminActivity(c *gin.Context, _ uint64) {
	h.finishAdminActivity(c)
}

// PublishAdminActivity adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) PublishAdminActivity(c *gin.Context, _ uint64) {
	h.publishAdminActivity(c)
}

// RejectAdminActivity adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) RejectAdminActivity(c *gin.Context, _ uint64) {
	h.rejectAdminActivity(c)
}

// SubmitAdminActivityReview adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) SubmitAdminActivityReview(c *gin.Context, _ uint64) {
	h.submitAdminActivityReview(c)
}
