// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/carpool.yaml

package httpapi

import (
	"github.com/gin-gonic/gin"
	"github.com/weouc-plus/campus-platform/internal/api/generated"
)

// ListCarpoolTrips adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) ListCarpoolTrips(c *gin.Context, _ generated.ListCarpoolTripsParams) {
	h.listCarpoolTrips(c)
}

// CreateCarpoolTrip adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) CreateCarpoolTrip(c *gin.Context) {
	h.createCarpoolTrip(c)
}

// GetCarpoolTrip adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) GetCarpoolTrip(c *gin.Context, _ uint64) {
	h.getCarpoolTrip(c)
}

// CancelCarpoolTrip adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) CancelCarpoolTrip(c *gin.Context, _ uint64) {
	h.cancelCarpoolTrip(c)
}

// JoinCarpoolTrip adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) JoinCarpoolTrip(c *gin.Context, _ uint64) {
	h.joinCarpoolTrip(c)
}

// LeaveCarpoolTrip adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) LeaveCarpoolTrip(c *gin.Context, _ uint64) {
	h.leaveCarpoolTrip(c)
}
