// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/comment.yaml

package httpapi

import (
	"github.com/gin-gonic/gin"
	"github.com/weouc-plus/campus-platform/internal/api/generated"
)

// ListAdminComments adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) ListAdminComments(c *gin.Context, params generated.ListAdminCommentsParams) {
	setGeneratedParams(c, "ListAdminComments", params)
	h.listAdminComments(c)
}

// ReviewComment adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) ReviewComment(c *gin.Context, id uint64, params generated.ReviewCommentParams) {
	setGeneratedPathParam(c, "id", id)
	setGeneratedParams(c, "ReviewComment", params)
	h.idempotent(c, "ReviewComment", func() {
		h.reviewComment(c)
	})
}

// RevokeCommentReview adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) RevokeCommentReview(c *gin.Context, id uint64, params generated.RevokeCommentReviewParams) {
	setGeneratedPathParam(c, "id", id)
	setGeneratedParams(c, "RevokeCommentReview", params)
	h.idempotent(c, "RevokeCommentReview", func() {
		h.revokeCommentReview(c)
	})
}

// ListComments adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) ListComments(c *gin.Context, params generated.ListCommentsParams) {
	setGeneratedParams(c, "ListComments", params)
	h.listComments(c)
}

// CreateComment adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) CreateComment(c *gin.Context, params generated.CreateCommentParams) {
	setGeneratedParams(c, "CreateComment", params)
	if !h.requireAcademicVerification(c) {
		return
	}
	h.idempotent(c, "CreateComment", func() {
		h.createComment(c)
	})
}

// ListMyComments adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) ListMyComments(c *gin.Context, params generated.ListMyCommentsParams) {
	setGeneratedParams(c, "ListMyComments", params)
	h.listMyComments(c)
}

// UpdateComment adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) UpdateComment(c *gin.Context, id uint64, params generated.UpdateCommentParams) {
	setGeneratedPathParam(c, "id", id)
	setGeneratedParams(c, "UpdateComment", params)
	if !h.requireAcademicVerification(c) {
		return
	}
	h.idempotent(c, "UpdateComment", func() {
		h.updateComment(c)
	})
}

// UnpinComment adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) UnpinComment(c *gin.Context, id uint64, params generated.UnpinCommentParams) {
	setGeneratedPathParam(c, "id", id)
	setGeneratedParams(c, "UnpinComment", params)
	h.idempotent(c, "UnpinComment", func() {
		h.unpinComment(c)
	})
}

// PinComment adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) PinComment(c *gin.Context, id uint64, params generated.PinCommentParams) {
	setGeneratedPathParam(c, "id", id)
	setGeneratedParams(c, "PinComment", params)
	h.idempotent(c, "PinComment", func() {
		h.pinComment(c)
	})
}

// SubmitCommentReview adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) SubmitCommentReview(c *gin.Context, id uint64, params generated.SubmitCommentReviewParams) {
	setGeneratedPathParam(c, "id", id)
	setGeneratedParams(c, "SubmitCommentReview", params)
	if !h.requireAcademicVerification(c) {
		return
	}
	h.idempotent(c, "SubmitCommentReview", func() {
		h.submitCommentReview(c)
	})
}

// GetCommentThread adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) GetCommentThread(c *gin.Context, id uint64) {
	setGeneratedPathParam(c, "id", id)
	h.getCommentThread(c)
}

// WithdrawComment adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) WithdrawComment(c *gin.Context, id uint64, params generated.WithdrawCommentParams) {
	setGeneratedPathParam(c, "id", id)
	setGeneratedParams(c, "WithdrawComment", params)
	h.idempotent(c, "WithdrawComment", func() {
		h.withdrawComment(c)
	})
}
