// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/errand.yaml

package httpapi

import (
	"github.com/gin-gonic/gin"
	"github.com/weouc-plus/campus-platform/internal/api/generated"
)

// ListErrands adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) ListErrands(c *gin.Context, _ generated.ListErrandsParams) {
	h.listErrands(c)
}

// CreateErrand adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) CreateErrand(c *gin.Context) {
	h.createErrand(c)
}

// ListMyErrands adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) ListMyErrands(c *gin.Context, _ generated.ListMyErrandsParams) {
	h.listMyErrands(c)
}

// GetErrand adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) GetErrand(c *gin.Context, _ uint64) {
	h.getErrand(c)
}

// UpdateErrand adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) UpdateErrand(c *gin.Context, _ uint64) {
	h.updateErrand(c)
}

// AcceptErrand adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) AcceptErrand(c *gin.Context, _ uint64, _ generated.AcceptErrandParams) {
	h.acceptErrand(c)
}

// CancelErrand adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) CancelErrand(c *gin.Context, _ uint64) {
	h.cancelErrand(c)
}

// CompleteErrand adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) CompleteErrand(c *gin.Context, _ uint64) {
	h.completeErrand(c)
}

// DeliverErrand adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) DeliverErrand(c *gin.Context, _ uint64) {
	h.deliverErrand(c)
}

// PickupErrand adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) PickupErrand(c *gin.Context, _ uint64) {
	h.pickupErrand(c)
}
