// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/errand.yaml

package httpapi

import (
	"github.com/gin-gonic/gin"
	"github.com/weouc-plus/campus-platform/internal/api/generated"
)

// ListAdminErrands adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) ListAdminErrands(c *gin.Context, params generated.ListAdminErrandsParams) {
	setGeneratedParams(c, "ListAdminErrands", params)
	h.listAdminErrands(c)
}

// ReviewErrand adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) ReviewErrand(c *gin.Context, id uint64, params generated.ReviewErrandParams) {
	setGeneratedPathParam(c, "id", id)
	setGeneratedParams(c, "ReviewErrand", params)
	h.idempotent(c, "ReviewErrand", func() {
		h.reviewErrand(c)
	})
}

// RevokeErrandReview adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) RevokeErrandReview(c *gin.Context, id uint64, params generated.RevokeErrandReviewParams) {
	setGeneratedPathParam(c, "id", id)
	setGeneratedParams(c, "RevokeErrandReview", params)
	h.idempotent(c, "RevokeErrandReview", func() {
		h.revokeErrandReview(c)
	})
}

// ListErrands adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) ListErrands(c *gin.Context, params generated.ListErrandsParams) {
	setGeneratedParams(c, "ListErrands", params)
	h.listErrands(c)
}

// CreateErrand adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) CreateErrand(c *gin.Context, params generated.CreateErrandParams) {
	setGeneratedParams(c, "CreateErrand", params)
	if !h.requireAcademicVerification(c) {
		return
	}
	h.idempotent(c, "CreateErrand", func() {
		h.createErrand(c)
	})
}

// ListMyErrands adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) ListMyErrands(c *gin.Context, params generated.ListMyErrandsParams) {
	setGeneratedParams(c, "ListMyErrands", params)
	h.listMyErrands(c)
}

// GetErrand adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) GetErrand(c *gin.Context, id uint64) {
	setGeneratedPathParam(c, "id", id)
	h.getErrand(c)
}

// UpdateErrand adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) UpdateErrand(c *gin.Context, id uint64, params generated.UpdateErrandParams) {
	setGeneratedPathParam(c, "id", id)
	setGeneratedParams(c, "UpdateErrand", params)
	if !h.requireAcademicVerification(c) {
		return
	}
	h.idempotent(c, "UpdateErrand", func() {
		h.updateErrand(c)
	})
}

// AcceptErrand adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) AcceptErrand(c *gin.Context, id uint64, params generated.AcceptErrandParams) {
	setGeneratedPathParam(c, "id", id)
	setGeneratedParams(c, "AcceptErrand", params)
	if !h.requireAcademicVerification(c) {
		return
	}
	h.idempotent(c, "AcceptErrand", func() {
		h.acceptErrand(c)
	})
}

// CancelErrand adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) CancelErrand(c *gin.Context, id uint64, params generated.CancelErrandParams) {
	setGeneratedPathParam(c, "id", id)
	setGeneratedParams(c, "CancelErrand", params)
	if !h.requireAcademicVerification(c) {
		return
	}
	h.idempotent(c, "CancelErrand", func() {
		h.cancelErrand(c)
	})
}

// CompleteErrand adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) CompleteErrand(c *gin.Context, id uint64, params generated.CompleteErrandParams) {
	setGeneratedPathParam(c, "id", id)
	setGeneratedParams(c, "CompleteErrand", params)
	if !h.requireAcademicVerification(c) {
		return
	}
	h.idempotent(c, "CompleteErrand", func() {
		h.completeErrand(c)
	})
}

// DeliverErrand adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) DeliverErrand(c *gin.Context, id uint64, params generated.DeliverErrandParams) {
	setGeneratedPathParam(c, "id", id)
	setGeneratedParams(c, "DeliverErrand", params)
	if !h.requireAcademicVerification(c) {
		return
	}
	h.idempotent(c, "DeliverErrand", func() {
		h.deliverErrand(c)
	})
}

// PickupErrand adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) PickupErrand(c *gin.Context, id uint64, params generated.PickupErrandParams) {
	setGeneratedPathParam(c, "id", id)
	setGeneratedParams(c, "PickupErrand", params)
	if !h.requireAcademicVerification(c) {
		return
	}
	h.idempotent(c, "PickupErrand", func() {
		h.pickupErrand(c)
	})
}

// SubmitErrandReview adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) SubmitErrandReview(c *gin.Context, id uint64, params generated.SubmitErrandReviewParams) {
	setGeneratedPathParam(c, "id", id)
	setGeneratedParams(c, "SubmitErrandReview", params)
	if !h.requireAcademicVerification(c) {
		return
	}
	h.idempotent(c, "SubmitErrandReview", func() {
		h.submitErrandReview(c)
	})
}
