// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/marketplace.yaml

package httpapi

import (
	"github.com/gin-gonic/gin"
	"github.com/weouc-plus/campus-platform/internal/api/generated"
)

// CreateMarketplaceListing adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) CreateMarketplaceListing(c *gin.Context) {
	h.createMarketplaceListing(c)
}

// SubmitMarketplaceListing adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) SubmitMarketplaceListing(c *gin.Context, _ uint64) {
	h.submitMarketplaceListing(c)
}

// WithdrawMarketplaceListing adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) WithdrawMarketplaceListing(c *gin.Context, _ uint64) {
	h.withdrawMarketplaceListing(c)
}

// CreateMarketplaceOrder adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) CreateMarketplaceOrder(c *gin.Context, _ generated.CreateMarketplaceOrderParams) {
	h.createMarketplaceOrder(c)
}
