// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/trade.yaml

package httpapi

import (
	"github.com/gin-gonic/gin"
	"github.com/weouc-plus/campus-platform/internal/api/generated"
)

// ListMyTradeOrders adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) ListMyTradeOrders(c *gin.Context, params generated.ListMyTradeOrdersParams) {
	setGeneratedParams(c, "ListMyTradeOrders", params)
	h.listMyTradeOrders(c)
}

// GetMyTradeOrder adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) GetMyTradeOrder(c *gin.Context, id uint64) {
	setGeneratedPathParam(c, "id", id)
	h.getMyTradeOrder(c)
}

// CancelTradeOrder adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) CancelTradeOrder(c *gin.Context, id uint64, params generated.CancelTradeOrderParams) {
	setGeneratedPathParam(c, "id", id)
	setGeneratedParams(c, "CancelTradeOrder", params)
	if !h.requireAcademicVerification(c) {
		return
	}
	h.idempotent(c, "CancelTradeOrder", func() {
		h.cancelTradeOrder(c)
	})
}

// CompleteTradeOrder adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) CompleteTradeOrder(c *gin.Context, id uint64, params generated.CompleteTradeOrderParams) {
	setGeneratedPathParam(c, "id", id)
	setGeneratedParams(c, "CompleteTradeOrder", params)
	if !h.requireAcademicVerification(c) {
		return
	}
	h.idempotent(c, "CompleteTradeOrder", func() {
		h.completeTradeOrder(c)
	})
}
