// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/trade.yaml

package httpapi

import (
	"github.com/gin-gonic/gin"
	"github.com/weouc-plus/campus-platform/internal/api/generated"
)

// ListMyTradeOrders adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) ListMyTradeOrders(c *gin.Context, _ generated.ListMyTradeOrdersParams) {
	h.listMyTradeOrders(c)
}

// GetMyTradeOrder adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) GetMyTradeOrder(c *gin.Context, _ uint64) {
	h.getMyTradeOrder(c)
}

// CancelTradeOrder adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) CancelTradeOrder(c *gin.Context, _ uint64) {
	h.cancelTradeOrder(c)
}

// CompleteTradeOrder adapts the generated OpenAPI operation to handwritten business handling.
func (h *Handler) CompleteTradeOrder(c *gin.Context, _ uint64) {
	h.completeTradeOrder(c)
}
