// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/notice.yaml

// Package application coordinates notice use cases.
package application

import (
	"context"

	"github.com/weouc-plus/campus-platform/internal/modules/notice/domain"
)

// Service coordinates generated CRUD operations and handwritten domain rules.
type Service struct{ repository domain.Repository }

// NewService creates a notice application service.
func NewService(repository domain.Repository) *Service { return &Service{repository: repository} }

// Create persists a new Notice.
func (s *Service) Create(ctx context.Context, value *domain.Notice) error {
	return s.repository.Create(ctx, value)
}

// Get returns one Notice by ID.
func (s *Service) Get(ctx context.Context, id uint64) (*domain.Notice, error) {
	return s.repository.Get(ctx, id)
}

// List returns a page of Notice values.
func (s *Service) List(ctx context.Context, page, pageSize int) ([]domain.Notice, int64, error) {
	return s.repository.List(ctx, page, pageSize)
}

// Update persists an existing Notice.
func (s *Service) Update(ctx context.Context, value *domain.Notice) error {
	return s.repository.Update(ctx, value)
}

// Delete removes one Notice by ID.
func (s *Service) Delete(ctx context.Context, id uint64) error {
	return s.repository.Delete(ctx, id)
}
