// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/carpool.yaml

package domain

import "time"

// Participant is the persistent domain entity for the carpool module.
type Participant struct {
	ID          uint64     `gorm:"primaryKey;autoIncrement" json:"id"`
	TripId      uint64     `gorm:"column:trip_id;not null" json:"trip_id"`
	UserId      uint64     `gorm:"column:user_id;not null" json:"user_id"`
	Status      string     `gorm:"column:status;not null;index" json:"status"`
	JoinedAt    time.Time  `gorm:"column:joined_at;not null" json:"joined_at"`
	CancelledAt *time.Time `gorm:"column:cancelled_at" json:"cancelled_at"`
	Version     uint64     `gorm:"column:version;not null" json:"version"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
}

// TableName returns the schema-controlled database table.
func (Participant) TableName() string { return "carpool_participants" }
