// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/carpool.yaml

package domain

import "context"

// Repository defines persistence operations enabled by the module schema.
type Repository interface {
	Create(context.Context, *Trip) error
	Get(context.Context, uint64) (*Trip, error)
	List(context.Context, int, int) ([]Trip, int64, error)
	Update(context.Context, *Trip) error
}
