// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/marketplace.yaml

package domain

import "time"

// MarketplaceReservation is the persistent domain entity for the marketplace module.
type MarketplaceReservation struct {
	ID           uint64    `gorm:"primaryKey;autoIncrement" json:"id"`
	ListingId    uint64    `gorm:"column:listing_id;not null;index" json:"listing_id"`
	TradeOrderId uint64    `gorm:"column:trade_order_id;not null;uniqueIndex" json:"trade_order_id"`
	BuyerId      uint64    `gorm:"column:buyer_id;not null;index" json:"buyer_id"`
	Status       string    `gorm:"column:status;not null;index" json:"status"`
	ExpiresAt    time.Time `gorm:"column:expires_at;not null;index" json:"expires_at"`
	Version      uint64    `gorm:"column:version;not null" json:"version"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

// TableName returns the schema-controlled database table.
func (MarketplaceReservation) TableName() string { return "marketplace_reservations" }
