// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/marketplace.yaml

package domain

import "time"

// ListingImage is the persistent domain entity for the marketplace module.
type ListingImage struct {
	ID        uint64    `gorm:"primaryKey;autoIncrement" json:"id"`
	ListingId uint64    `gorm:"column:listing_id;not null" json:"listing_id"`
	Url       string    `gorm:"column:url;not null" json:"url"`
	Position  int64     `gorm:"column:position;not null" json:"position"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// TableName returns the schema-controlled database table.
func (ListingImage) TableName() string { return "marketplace_listing_images" }
