// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/marketplace.yaml

package domain

import "context"

// Repository defines persistence operations enabled by the module schema.
type Repository interface {
	Create(context.Context, *Listing) error
	Get(context.Context, uint64) (*Listing, error)
	List(context.Context, int, int) ([]Listing, int64, error)
	Update(context.Context, *Listing) error
	Delete(context.Context, uint64) error
}
