// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/activity.yaml

package domain

import "time"

// Activity is the persistent domain entity for the activity module.
type Activity struct {
	ID                uint64    `gorm:"primaryKey;autoIncrement" json:"id"`
	Title             string    `gorm:"column:title;not null" json:"title"`
	Summary           string    `gorm:"column:summary;not null" json:"summary"`
	Body              string    `gorm:"column:body;not null" json:"body"`
	Location          string    `gorm:"column:location;not null" json:"location"`
	SignupStartAt     time.Time `gorm:"column:signup_start_at;not null;index" json:"signup_start_at"`
	SignupEndAt       time.Time `gorm:"column:signup_end_at;not null;index" json:"signup_end_at"`
	StartAt           time.Time `gorm:"column:start_at;not null;index" json:"start_at"`
	EndAt             time.Time `gorm:"column:end_at;not null;index" json:"end_at"`
	Capacity          int64     `gorm:"column:capacity;not null" json:"capacity"`
	RegisteredCount   int64     `gorm:"column:registered_count;not null" json:"registered_count"`
	Status            string    `gorm:"column:status;not null;index" json:"status"`
	ReviewStatus      string    `gorm:"column:review_status;not null;index" json:"review_status"`
	ReviewComment     *string   `gorm:"column:review_comment" json:"review_comment"`
	ContactType       string    `gorm:"column:contact_type;not null" json:"contact_type"`
	ContactCiphertext string    `gorm:"column:contact_ciphertext;not null" json:"contact_ciphertext"`
	CreatedBy         uint64    `gorm:"column:created_by;not null;index" json:"created_by"`
	UpdatedBy         uint64    `gorm:"column:updated_by;not null;index" json:"updated_by"`
	Version           uint64    `gorm:"column:version;not null" json:"version"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

// TableName returns the schema-controlled database table.
func (Activity) TableName() string { return "activities" }
