// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/activity.yaml

package domain

import "time"

// ActivityRegistration is the persistent domain entity for the activity module.
type ActivityRegistration struct {
	ID             uint64     `gorm:"primaryKey;autoIncrement" json:"id"`
	ActivityId     uint64     `gorm:"column:activity_id;not null" json:"activity_id"`
	UserId         uint64     `gorm:"column:user_id;not null" json:"user_id"`
	Status         string     `gorm:"column:status;not null;index" json:"status"`
	RegisteredAt   time.Time  `gorm:"column:registered_at;not null" json:"registered_at"`
	CancelledAt    *time.Time `gorm:"column:cancelled_at" json:"cancelled_at"`
	IdempotencyKey string     `gorm:"column:idempotency_key;not null" json:"idempotency_key"`
	Version        uint64     `gorm:"column:version;not null" json:"version"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
}

// TableName returns the schema-controlled database table.
func (ActivityRegistration) TableName() string { return "activity_registrations" }
