// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/academic_verification.yaml

// Package academic_verification wires the generated module components.
package academic_verification

import (
	"github.com/weouc-plus/campus-platform/internal/modules/academic_verification/api"
	"github.com/weouc-plus/campus-platform/internal/modules/academic_verification/application"
	"github.com/weouc-plus/campus-platform/internal/modules/academic_verification/infrastructure"
	"gorm.io/gorm"
)

// Module contains the public runtime components of the academic_verification module.
type Module struct{ Handler *api.Handler }

// New creates a academic_verification module from shared infrastructure.
func New(db *gorm.DB) *Module {
	repository := infrastructure.NewRepository(db)
	service := application.NewService(repository)
	return &Module{Handler: api.NewHandler(service)}
}
