// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/notice.yaml

package domain

import "time"

// NoticeDelivery is the persistent domain entity for the notice module.
type NoticeDelivery struct {
	ID                uint64     `gorm:"primaryKey;autoIncrement" json:"id"`
	NoticeId          uint64     `gorm:"column:notice_id;not null" json:"notice_id"`
	UserId            uint64     `gorm:"column:user_id;not null" json:"user_id"`
	Channel           string     `gorm:"column:channel;not null" json:"channel"`
	Status            string     `gorm:"column:status;not null;index" json:"status"`
	Attempts          int64      `gorm:"column:attempts;not null" json:"attempts"`
	LockedAt          *time.Time `gorm:"column:locked_at" json:"locked_at"`
	IdempotencyKey    string     `gorm:"column:idempotency_key;not null;uniqueIndex" json:"idempotency_key"`
	ProviderMessageId *string    `gorm:"column:provider_message_id" json:"provider_message_id"`
	LastError         *string    `gorm:"column:last_error" json:"last_error"`
	CreatedAt         time.Time  `json:"created_at"`
	UpdatedAt         time.Time  `json:"updated_at"`
}

// TableName returns the schema-controlled database table.
func (NoticeDelivery) TableName() string { return "notice_deliveries" }
