// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/notice.yaml

package domain

import "time"

// NoticeRecipient is the persistent domain entity for the notice module.
type NoticeRecipient struct {
	ID        uint64     `gorm:"primaryKey;autoIncrement" json:"id"`
	NoticeId  uint64     `gorm:"column:notice_id;not null" json:"notice_id"`
	UserId    uint64     `gorm:"column:user_id;not null" json:"user_id"`
	ReadAt    *time.Time `gorm:"column:read_at" json:"read_at"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
}

// TableName returns the schema-controlled database table.
func (NoticeRecipient) TableName() string { return "notice_recipients" }
