// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/notice.yaml

package domain

import "time"

// NoticeAudience is the persistent domain entity for the notice module.
type NoticeAudience struct {
	ID            uint64    `gorm:"primaryKey;autoIncrement" json:"id"`
	NoticeId      uint64    `gorm:"column:notice_id;not null" json:"notice_id"`
	AudienceType  string    `gorm:"column:audience_type;not null" json:"audience_type"`
	AudienceValue string    `gorm:"column:audience_value;not null" json:"audience_value"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

// TableName returns the schema-controlled database table.
func (NoticeAudience) TableName() string { return "notice_audiences" }
