// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/notice.yaml

package domain

import "time"

// OutboxEvent is the persistent domain entity for the notice module.
type OutboxEvent struct {
	ID            uint64     `gorm:"primaryKey;autoIncrement" json:"id"`
	AggregateType string     `gorm:"column:aggregate_type;not null" json:"aggregate_type"`
	AggregateId   uint64     `gorm:"column:aggregate_id;not null" json:"aggregate_id"`
	EventType     string     `gorm:"column:event_type;not null" json:"event_type"`
	Payload       []byte     `gorm:"column:payload;not null" json:"payload"`
	Status        string     `gorm:"column:status;not null;index" json:"status"`
	AvailableAt   time.Time  `gorm:"column:available_at;not null;index" json:"available_at"`
	LockedAt      *time.Time `gorm:"column:locked_at" json:"locked_at"`
	Attempts      int64      `gorm:"column:attempts;not null" json:"attempts"`
	LastError     *string    `gorm:"column:last_error" json:"last_error"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
}

// TableName returns the schema-controlled database table.
func (OutboxEvent) TableName() string { return "outbox_events" }
