// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/marketplace.yaml

// Package infrastructure implements marketplace persistence contracts.
package infrastructure

import (
	"context"
	"fmt"

	platformquery "github.com/weouc-plus/campus-platform/internal/infrastructure/mysql/query"
	"github.com/weouc-plus/campus-platform/internal/modules/marketplace/domain"
	"gorm.io/gorm"
)

// Repository is the generated type-safe GORM Query persistence adapter.
type Repository struct{ query *platformquery.Query }

// NewRepository creates a marketplace repository.
func NewRepository(db *gorm.DB) *Repository { return &Repository{query: platformquery.Use(db)} }

// Create inserts a Listing.
func (r *Repository) Create(ctx context.Context, value *domain.Listing) error {
	if err := r.query.Listing.WithContext(ctx).Create(value); err != nil {
		return fmt.Errorf("create marketplace: %w", err)
	}
	return nil
}

// Get returns one Listing by primary key.
func (r *Repository) Get(ctx context.Context, id uint64) (*domain.Listing, error) {
	q := r.query.Listing
	value, err := q.WithContext(ctx).Where(q.ID.Eq(id)).First()
	if err != nil {
		return nil, fmt.Errorf("get marketplace: %w", err)
	}
	return value, nil
}

// List returns a deterministic page ordered by primary key.
func (r *Repository) List(ctx context.Context, page, pageSize int) ([]domain.Listing, int64, error) {
	if page < 1 {
		page = 1
	}
	if pageSize < 1 {
		pageSize = 20
	}
	q := r.query.Listing
	dao := q.WithContext(ctx)
	total, err := dao.Count()
	if err != nil {
		return nil, 0, fmt.Errorf("count marketplace: %w", err)
	}
	values, err := dao.Order(q.ID).Offset((page - 1) * pageSize).Limit(pageSize).Find()
	if err != nil {
		return nil, 0, fmt.Errorf("list marketplace: %w", err)
	}
	rows := make([]domain.Listing, len(values))
	for i := range values {
		rows[i] = *values[i]
	}
	return rows, total, nil
}

// Update saves a Listing by primary key.
func (r *Repository) Update(ctx context.Context, value *domain.Listing) error {
	if err := r.query.Listing.WithContext(ctx).Save(value); err != nil {
		return fmt.Errorf("update marketplace: %w", err)
	}
	return nil
}

// Delete removes a Listing by primary key.
func (r *Repository) Delete(ctx context.Context, id uint64) error {
	q := r.query.Listing
	if _, err := q.WithContext(ctx).Where(q.ID.Eq(id)).Delete(); err != nil {
		return fmt.Errorf("delete marketplace: %w", err)
	}
	return nil
}

var _ domain.Repository = (*Repository)(nil)
