// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/trade.yaml

// Package application coordinates trade use cases.
package application

import (
	"context"

	"github.com/weouc-plus/campus-platform/internal/modules/trade/domain"
)

// Service coordinates generated CRUD operations and handwritten domain rules.
type Service struct{ repository domain.Repository }

// NewService creates a trade application service.
func NewService(repository domain.Repository) *Service { return &Service{repository: repository} }

// Create persists a new Order.
func (s *Service) Create(ctx context.Context, value *domain.Order) error {
	return s.repository.Create(ctx, value)
}

// Get returns one Order by ID.
func (s *Service) Get(ctx context.Context, id uint64) (*domain.Order, error) {
	return s.repository.Get(ctx, id)
}

// List returns a page of Order values.
func (s *Service) List(ctx context.Context, page, pageSize int) ([]domain.Order, int64, error) {
	return s.repository.List(ctx, page, pageSize)
}

// Update persists an existing Order.
func (s *Service) Update(ctx context.Context, value *domain.Order) error {
	return s.repository.Update(ctx, value)
}
