// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/payment.yaml

// Package payment wires the generated module components.
package payment

import (
	"github.com/weouc-plus/campus-platform/internal/modules/payment/api"
	"github.com/weouc-plus/campus-platform/internal/modules/payment/application"
	"github.com/weouc-plus/campus-platform/internal/modules/payment/infrastructure"
	"gorm.io/gorm"
)

// Module contains the public runtime components of the payment module.
type Module struct{ Handler *api.Handler }

// New creates a payment module from shared infrastructure.
func New(db *gorm.DB) *Module {
	repository := infrastructure.NewRepository(db)
	service := application.NewService(repository)
	return &Module{Handler: api.NewHandler(service)}
}
