// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/campus_circle.yaml

// Package api exposes campus_circle transport adapters.
package api

import "github.com/weouc-plus/campus-platform/internal/modules/campus_circle/application"

// Handler is the extension point for generated OpenAPI operations.
type Handler struct{ service *application.Service }

// NewHandler creates a campus_circle API handler.
func NewHandler(service *application.Service) *Handler { return &Handler{service: service} }
