// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/errand.yaml

package domain

import "time"

// Task is the persistent domain entity for the errand module.
type Task struct {
	ID                uint64     `gorm:"primaryKey;autoIncrement" json:"id"`
	Title             string     `gorm:"column:title;not null" json:"title"`
	Description       string     `gorm:"column:description;not null" json:"description"`
	RewardCents       int64      `gorm:"column:reward_cents;not null" json:"reward_cents"`
	Currency          string     `gorm:"column:currency;not null" json:"currency"`
	PickupLocation    string     `gorm:"column:pickup_location;not null" json:"pickup_location"`
	DropoffLocation   string     `gorm:"column:dropoff_location;not null" json:"dropoff_location"`
	Deadline          time.Time  `gorm:"column:deadline;not null;index" json:"deadline"`
	Status            string     `gorm:"column:status;not null;index" json:"status"`
	ReviewStatus      string     `gorm:"column:review_status;not null;index" json:"review_status"`
	ReviewReason      *string    `gorm:"column:review_reason" json:"review_reason"`
	ReviewedBy        *uint64    `gorm:"column:reviewed_by" json:"reviewed_by"`
	ReviewedAt        *time.Time `gorm:"column:reviewed_at" json:"reviewed_at"`
	RequesterId       uint64     `gorm:"column:requester_id;not null;index" json:"requester_id"`
	ContactType       string     `gorm:"column:contact_type;not null" json:"contact_type"`
	ContactCiphertext string     `gorm:"column:contact_ciphertext;not null" json:"contact_ciphertext"`
	RunnerId          *uint64    `gorm:"column:runner_id;index" json:"runner_id"`
	TradeOrderId      *uint64    `gorm:"column:trade_order_id;uniqueIndex" json:"trade_order_id"`
	AcceptedAt        *time.Time `gorm:"column:accepted_at" json:"accepted_at"`
	PickedUpAt        *time.Time `gorm:"column:picked_up_at" json:"picked_up_at"`
	DeliveredAt       *time.Time `gorm:"column:delivered_at" json:"delivered_at"`
	CompletedAt       *time.Time `gorm:"column:completed_at" json:"completed_at"`
	CancelledAt       *time.Time `gorm:"column:cancelled_at" json:"cancelled_at"`
	Version           uint64     `gorm:"column:version;not null" json:"version"`
	CreatedAt         time.Time  `json:"created_at"`
	UpdatedAt         time.Time  `json:"updated_at"`
}

// TableName returns the schema-controlled database table.
func (Task) TableName() string { return "errand_tasks" }
