// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/errand.yaml

package domain

import "time"

// Transition is the persistent domain entity for the errand module.
type Transition struct {
	ID             uint64    `gorm:"primaryKey;autoIncrement" json:"id"`
	TaskId         uint64    `gorm:"column:task_id;not null" json:"task_id"`
	FromStatus     string    `gorm:"column:from_status;not null" json:"from_status"`
	ToStatus       string    `gorm:"column:to_status;not null" json:"to_status"`
	ActorId        *uint64   `gorm:"column:actor_id" json:"actor_id"`
	Reason         *string   `gorm:"column:reason" json:"reason"`
	IdempotencyKey string    `gorm:"column:idempotency_key;not null;uniqueIndex" json:"idempotency_key"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

// TableName returns the schema-controlled database table.
func (Transition) TableName() string { return "errand_transitions" }
