// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/errand.yaml

package domain

import "context"

// Repository defines persistence operations enabled by the module schema.
type Repository interface {
	Create(context.Context, *Task) error
	Get(context.Context, uint64) (*Task, error)
	List(context.Context, int, int) ([]Task, int64, error)
	Update(context.Context, *Task) error
}
