-- Code generated by campusctl from a module schema. DO NOT EDIT.
-- Source: schemas/activity.yaml
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS activities;
DROP TABLE IF EXISTS activity_registrations;
SET FOREIGN_KEY_CHECKS = 1;
