-- Code generated by campusctl from a module schema. DO NOT EDIT.
-- Source: schemas/carpool.yaml
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS carpool_trips;
DROP TABLE IF EXISTS carpool_participants;
SET FOREIGN_KEY_CHECKS = 1;
