-- Code generated by campusctl from a module schema. DO NOT EDIT.
-- Source: schemas/errand.yaml
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS errand_tasks;
DROP TABLE IF EXISTS errand_transitions;
SET FOREIGN_KEY_CHECKS = 1;
