-- Code generated by campusctl from a module schema. DO NOT EDIT.
-- Source: schemas/notice.yaml
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS notices;
DROP TABLE IF EXISTS notice_audiences;
DROP TABLE IF EXISTS notice_recipients;
DROP TABLE IF EXISTS notice_deliveries;
DROP TABLE IF EXISTS outbox_events;
SET FOREIGN_KEY_CHECKS = 1;
