-- Code generated by campusctl from a module schema. DO NOT EDIT.
-- Source: schemas/payment.yaml

CREATE TABLE payment_intents (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    intent_no VARCHAR(40) NOT NULL,
    resource_type VARCHAR(64) NOT NULL,
    resource_id BIGINT UNSIGNED NOT NULL,
    payer_id BIGINT UNSIGNED NOT NULL,
    payee_id BIGINT UNSIGNED NOT NULL,
    amount_cents BIGINT NOT NULL,
    currency VARCHAR(3) NOT NULL,
    method VARCHAR(32) NOT NULL,
    provider VARCHAR(32) NOT NULL,
    status VARCHAR(24) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    provider_intent_id VARCHAR(128) NULL,
    expires_at DATETIME(3) NULL,
    version BIGINT UNSIGNED NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_payment_intents_intent_no (intent_no),
    KEY idx_payment_intents_payer_id (payer_id),
    KEY idx_payment_intents_payee_id (payee_id),
    KEY idx_payment_intents_status (status),
    UNIQUE KEY uk_payment_payer_idempotency (payer_id, idempotency_key),
    KEY idx_payment_resource (resource_type, resource_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE payment_transactions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    intent_id BIGINT UNSIGNED NOT NULL,
    attempt_no BIGINT NOT NULL,
    provider VARCHAR(32) NOT NULL,
    provider_transaction_id VARCHAR(128) NULL,
    status VARCHAR(24) NOT NULL,
    failure_code VARCHAR(64) NULL,
    failure_message VARCHAR(500) NULL,
    paid_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_payment_transactions_status (status),
    UNIQUE KEY uk_payment_attempt (intent_id, attempt_no),
    FOREIGN KEY (intent_id) REFERENCES payment_intents(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE payment_refunds (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    intent_id BIGINT UNSIGNED NOT NULL,
    refund_no VARCHAR(40) NOT NULL,
    amount_cents BIGINT NOT NULL,
    status VARCHAR(24) NOT NULL,
    reason VARCHAR(500) NOT NULL,
    provider_refund_id VARCHAR(128) NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    refunded_at DATETIME(3) NULL,
    version BIGINT UNSIGNED NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_payment_refunds_refund_no (refund_no),
    KEY idx_payment_refunds_status (status),
    UNIQUE KEY uk_payment_refunds_idempotency_key (idempotency_key),
    FOREIGN KEY (intent_id) REFERENCES payment_intents(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE payment_callbacks (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    provider VARCHAR(32) NOT NULL,
    provider_event_id VARCHAR(128) NOT NULL,
    payload_digest VARCHAR(64) NOT NULL,
    status VARCHAR(24) NOT NULL,
    processed_at DATETIME(3) NULL,
    last_error VARCHAR(500) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_payment_callbacks_status (status),
    UNIQUE KEY uk_payment_callback_event (provider, provider_event_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

