-- Code generated by campusctl from a module schema. DO NOT EDIT.
-- Source: schemas/payment.yaml
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS payment_intents;
DROP TABLE IF EXISTS payment_transactions;
DROP TABLE IF EXISTS payment_refunds;
DROP TABLE IF EXISTS payment_callbacks;
SET FOREIGN_KEY_CHECKS = 1;
