-- Code generated by campusctl from a module schema. DO NOT EDIT.
-- Source: schemas/trade.yaml
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS trade_orders;
DROP TABLE IF EXISTS trade_order_transitions;
SET FOREIGN_KEY_CHECKS = 1;
