-- Code generated by campusctl from a module schema. DO NOT EDIT.
-- Source: schemas/trade.yaml

CREATE TABLE trade_orders (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    order_no VARCHAR(40) NOT NULL,
    order_type VARCHAR(32) NOT NULL,
    resource_type VARCHAR(64) NOT NULL,
    resource_id BIGINT UNSIGNED NOT NULL,
    buyer_id BIGINT UNSIGNED NOT NULL,
    seller_id BIGINT UNSIGNED NOT NULL,
    amount_cents BIGINT NOT NULL,
    currency VARCHAR(3) NOT NULL,
    payment_mode VARCHAR(16) NOT NULL,
    trade_status VARCHAR(24) NOT NULL,
    fulfillment_status VARCHAR(24) NOT NULL,
    title_snapshot VARCHAR(200) NOT NULL,
    resource_snapshot JSON NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    expires_at DATETIME(3) NULL,
    paid_at DATETIME(3) NULL,
    completed_at DATETIME(3) NULL,
    cancelled_at DATETIME(3) NULL,
    closed_at DATETIME(3) NULL,
    version BIGINT UNSIGNED NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_trade_orders_order_no (order_no),
    KEY idx_trade_orders_order_type (order_type),
    KEY idx_trade_orders_buyer_id (buyer_id),
    KEY idx_trade_orders_seller_id (seller_id),
    KEY idx_trade_orders_trade_status (trade_status),
    KEY idx_trade_orders_expires_at (expires_at),
    UNIQUE KEY uk_trade_buyer_idempotency (buyer_id, idempotency_key),
    KEY idx_trade_resource (resource_type, resource_id),
    KEY idx_trade_expiry (trade_status, expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE trade_order_transitions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    order_id BIGINT UNSIGNED NOT NULL,
    from_status VARCHAR(24) NOT NULL,
    to_status VARCHAR(24) NOT NULL,
    actor_type VARCHAR(16) NOT NULL,
    actor_id BIGINT UNSIGNED NULL,
    reason_code VARCHAR(64) NULL,
    reason_text VARCHAR(500) NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_trade_order_transitions_idempotency_key (idempotency_key),
    KEY idx_trade_transition_order (order_id),
    FOREIGN KEY (order_id) REFERENCES trade_orders(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

