// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/notice.yaml

// Package notice wires the generated module components.
package notice

import (
	"github.com/weouc-plus/campus-platform/internal/modules/notice/api"
	"github.com/weouc-plus/campus-platform/internal/modules/notice/application"
	"github.com/weouc-plus/campus-platform/internal/modules/notice/infrastructure"
	"gorm.io/gorm"
)

// Module contains the public runtime components of the notice module.
type Module struct{ Handler *api.Handler }

// New creates a notice module from shared infrastructure.
func New(db *gorm.DB) *Module {
	repository := infrastructure.NewRepository(db)
	service := application.NewService(repository)
	return &Module{Handler: api.NewHandler(service)}
}
