// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/marketplace.yaml

// Package api exposes marketplace transport adapters.
package api

import "github.com/weouc-plus/campus-platform/internal/modules/marketplace/application"

// Handler is the extension point for generated OpenAPI operations.
type Handler struct{ service *application.Service }

// NewHandler creates a marketplace API handler.
func NewHandler(service *application.Service) *Handler { return &Handler{service: service} }
