// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/carpool.yaml

// Package carpool wires the generated module components.
package carpool

import (
	"github.com/weouc-plus/campus-platform/internal/modules/carpool/api"
	"github.com/weouc-plus/campus-platform/internal/modules/carpool/application"
	"github.com/weouc-plus/campus-platform/internal/modules/carpool/infrastructure"
	"gorm.io/gorm"
)

// Module contains the public runtime components of the carpool module.
type Module struct{ Handler *api.Handler }

// New creates a carpool module from shared infrastructure.
func New(db *gorm.DB) *Module {
	repository := infrastructure.NewRepository(db)
	service := application.NewService(repository)
	return &Module{Handler: api.NewHandler(service)}
}
