// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/activity.yaml

// Package activity wires the generated module components.
package activity

import (
	"github.com/weouc-plus/campus-platform/internal/modules/activity/api"
	"github.com/weouc-plus/campus-platform/internal/modules/activity/application"
	"github.com/weouc-plus/campus-platform/internal/modules/activity/infrastructure"
	"gorm.io/gorm"
)

// Module contains the public runtime components of the activity module.
type Module struct{ Handler *api.Handler }

// New creates a activity module from shared infrastructure.
func New(db *gorm.DB) *Module {
	repository := infrastructure.NewRepository(db)
	service := application.NewService(repository)
	return &Module{Handler: api.NewHandler(service)}
}
