// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/trade.yaml

package domain

import "context"

// Repository defines persistence operations enabled by the module schema.
type Repository interface {
	Create(context.Context, *Order) error
	Get(context.Context, uint64) (*Order, error)
	List(context.Context, int, int) ([]Order, int64, error)
	Update(context.Context, *Order) error
}
