// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/trade.yaml

package domain

import "time"

// Order is the persistent domain entity for the trade module.
type Order struct {
	ID                uint64     `gorm:"primaryKey;autoIncrement" json:"id"`
	OrderNo           string     `gorm:"column:order_no;not null;uniqueIndex" json:"order_no"`
	OrderType         string     `gorm:"column:order_type;not null;index" json:"order_type"`
	ResourceType      string     `gorm:"column:resource_type;not null" json:"resource_type"`
	ResourceId        uint64     `gorm:"column:resource_id;not null" json:"resource_id"`
	BuyerId           uint64     `gorm:"column:buyer_id;not null;index" json:"buyer_id"`
	SellerId          uint64     `gorm:"column:seller_id;not null;index" json:"seller_id"`
	AmountCents       int64      `gorm:"column:amount_cents;not null" json:"amount_cents"`
	Currency          string     `gorm:"column:currency;not null" json:"currency"`
	PaymentMode       string     `gorm:"column:payment_mode;not null" json:"payment_mode"`
	TradeStatus       string     `gorm:"column:trade_status;not null;index" json:"trade_status"`
	FulfillmentStatus string     `gorm:"column:fulfillment_status;not null" json:"fulfillment_status"`
	TitleSnapshot     string     `gorm:"column:title_snapshot;not null" json:"title_snapshot"`
	ResourceSnapshot  []byte     `gorm:"column:resource_snapshot;not null" json:"resource_snapshot"`
	IdempotencyKey    string     `gorm:"column:idempotency_key;not null" json:"idempotency_key"`
	ExpiresAt         *time.Time `gorm:"column:expires_at;index" json:"expires_at"`
	PaidAt            *time.Time `gorm:"column:paid_at" json:"paid_at"`
	CompletedAt       *time.Time `gorm:"column:completed_at" json:"completed_at"`
	CancelledAt       *time.Time `gorm:"column:cancelled_at" json:"cancelled_at"`
	ClosedAt          *time.Time `gorm:"column:closed_at" json:"closed_at"`
	Version           uint64     `gorm:"column:version;not null" json:"version"`
	CreatedAt         time.Time  `json:"created_at"`
	UpdatedAt         time.Time  `json:"updated_at"`
}

// TableName returns the schema-controlled database table.
func (Order) TableName() string { return "trade_orders" }
