// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/trade.yaml

package domain

import "time"

// OrderTransition is the persistent domain entity for the trade module.
type OrderTransition struct {
	ID             uint64    `gorm:"primaryKey;autoIncrement" json:"id"`
	OrderId        uint64    `gorm:"column:order_id;not null" json:"order_id"`
	FromStatus     string    `gorm:"column:from_status;not null" json:"from_status"`
	ToStatus       string    `gorm:"column:to_status;not null" json:"to_status"`
	ActorType      string    `gorm:"column:actor_type;not null" json:"actor_type"`
	ActorId        *uint64   `gorm:"column:actor_id" json:"actor_id"`
	ReasonCode     *string   `gorm:"column:reason_code" json:"reason_code"`
	ReasonText     *string   `gorm:"column:reason_text" json:"reason_text"`
	IdempotencyKey string    `gorm:"column:idempotency_key;not null;uniqueIndex" json:"idempotency_key"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

// TableName returns the schema-controlled database table.
func (OrderTransition) TableName() string { return "trade_order_transitions" }
