// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/academic_verification.yaml

// Package application coordinates academic_verification use cases.
package application

import (
	"context"

	"github.com/weouc-plus/campus-platform/internal/modules/academic_verification/domain"
)

// Service coordinates generated CRUD operations and handwritten domain rules.
type Service struct{ repository domain.Repository }

// NewService creates a academic_verification application service.
func NewService(repository domain.Repository) *Service { return &Service{repository: repository} }

// Create persists a new AcademicIdentity.
func (s *Service) Create(ctx context.Context, value *domain.AcademicIdentity) error {
	return s.repository.Create(ctx, value)
}

// Get returns one AcademicIdentity by ID.
func (s *Service) Get(ctx context.Context, id uint64) (*domain.AcademicIdentity, error) {
	return s.repository.Get(ctx, id)
}

// List returns a page of AcademicIdentity values.
func (s *Service) List(ctx context.Context, page, pageSize int) ([]domain.AcademicIdentity, int64, error) {
	return s.repository.List(ctx, page, pageSize)
}

// Update persists an existing AcademicIdentity.
func (s *Service) Update(ctx context.Context, value *domain.AcademicIdentity) error {
	return s.repository.Update(ctx, value)
}
