// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/comment.yaml

// Package comment wires the generated module components.
package comment

import (
	"github.com/weouc-plus/campus-platform/internal/modules/comment/api"
	"github.com/weouc-plus/campus-platform/internal/modules/comment/application"
	"github.com/weouc-plus/campus-platform/internal/modules/comment/infrastructure"
	"gorm.io/gorm"
)

// Module contains the public runtime components of the comment module.
type Module struct{ Handler *api.Handler }

// New creates a comment module from shared infrastructure.
func New(db *gorm.DB) *Module {
	repository := infrastructure.NewRepository(db)
	service := application.NewService(repository)
	return &Module{Handler: api.NewHandler(service)}
}
