// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/marketplace.yaml

// Package marketplace wires the generated module components.
package marketplace

import (
	"github.com/weouc-plus/campus-platform/internal/modules/marketplace/api"
	"github.com/weouc-plus/campus-platform/internal/modules/marketplace/application"
	"github.com/weouc-plus/campus-platform/internal/modules/marketplace/infrastructure"
	"gorm.io/gorm"
)

// Module contains the public runtime components of the marketplace module.
type Module struct{ Handler *api.Handler }

// New creates a marketplace module from shared infrastructure.
func New(db *gorm.DB) *Module {
	repository := infrastructure.NewRepository(db)
	service := application.NewService(repository)
	return &Module{Handler: api.NewHandler(service)}
}
