// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/comment.yaml

// Package application coordinates comment use cases.
package application

import (
	"context"

	"github.com/weouc-plus/campus-platform/internal/modules/comment/domain"
)

// Service coordinates generated CRUD operations and handwritten domain rules.
type Service struct{ repository domain.Repository }

// NewService creates a comment application service.
func NewService(repository domain.Repository) *Service { return &Service{repository: repository} }

// Create persists a new Comment.
func (s *Service) Create(ctx context.Context, value *domain.Comment) error {
	return s.repository.Create(ctx, value)
}

// Get returns one Comment by ID.
func (s *Service) Get(ctx context.Context, id uint64) (*domain.Comment, error) {
	return s.repository.Get(ctx, id)
}

// List returns a page of Comment values.
func (s *Service) List(ctx context.Context, page, pageSize int) ([]domain.Comment, int64, error) {
	return s.repository.List(ctx, page, pageSize)
}

// Update persists an existing Comment.
func (s *Service) Update(ctx context.Context, value *domain.Comment) error {
	return s.repository.Update(ctx, value)
}
