// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/payment.yaml

package domain

import "time"

// PaymentTransaction is the persistent domain entity for the payment module.
type PaymentTransaction struct {
	ID                    uint64     `gorm:"primaryKey;autoIncrement" json:"id"`
	IntentId              uint64     `gorm:"column:intent_id;not null" json:"intent_id"`
	AttemptNo             int64      `gorm:"column:attempt_no;not null" json:"attempt_no"`
	Provider              string     `gorm:"column:provider;not null" json:"provider"`
	ProviderTransactionId *string    `gorm:"column:provider_transaction_id" json:"provider_transaction_id"`
	Status                string     `gorm:"column:status;not null;index" json:"status"`
	FailureCode           *string    `gorm:"column:failure_code" json:"failure_code"`
	FailureMessage        *string    `gorm:"column:failure_message" json:"failure_message"`
	PaidAt                *time.Time `gorm:"column:paid_at" json:"paid_at"`
	CreatedAt             time.Time  `json:"created_at"`
	UpdatedAt             time.Time  `json:"updated_at"`
}

// TableName returns the schema-controlled database table.
func (PaymentTransaction) TableName() string { return "payment_transactions" }
