// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/payment.yaml

package domain

import "time"

// PaymentRefund is the persistent domain entity for the payment module.
type PaymentRefund struct {
	ID               uint64     `gorm:"primaryKey;autoIncrement" json:"id"`
	IntentId         uint64     `gorm:"column:intent_id;not null" json:"intent_id"`
	RefundNo         string     `gorm:"column:refund_no;not null;uniqueIndex" json:"refund_no"`
	AmountCents      int64      `gorm:"column:amount_cents;not null" json:"amount_cents"`
	Status           string     `gorm:"column:status;not null;index" json:"status"`
	Reason           string     `gorm:"column:reason;not null" json:"reason"`
	ProviderRefundId *string    `gorm:"column:provider_refund_id" json:"provider_refund_id"`
	IdempotencyKey   string     `gorm:"column:idempotency_key;not null;uniqueIndex" json:"idempotency_key"`
	RefundedAt       *time.Time `gorm:"column:refunded_at" json:"refunded_at"`
	Version          uint64     `gorm:"column:version;not null" json:"version"`
	CreatedAt        time.Time  `json:"created_at"`
	UpdatedAt        time.Time  `json:"updated_at"`
}

// TableName returns the schema-controlled database table.
func (PaymentRefund) TableName() string { return "payment_refunds" }
