// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/payment.yaml

package domain

import "time"

// PaymentIntent is the persistent domain entity for the payment module.
type PaymentIntent struct {
	ID               uint64     `gorm:"primaryKey;autoIncrement" json:"id"`
	IntentNo         string     `gorm:"column:intent_no;not null;uniqueIndex" json:"intent_no"`
	ResourceType     string     `gorm:"column:resource_type;not null" json:"resource_type"`
	ResourceId       uint64     `gorm:"column:resource_id;not null" json:"resource_id"`
	PayerId          uint64     `gorm:"column:payer_id;not null;index" json:"payer_id"`
	PayeeId          uint64     `gorm:"column:payee_id;not null;index" json:"payee_id"`
	AmountCents      int64      `gorm:"column:amount_cents;not null" json:"amount_cents"`
	Currency         string     `gorm:"column:currency;not null" json:"currency"`
	Method           string     `gorm:"column:method;not null" json:"method"`
	Provider         string     `gorm:"column:provider;not null" json:"provider"`
	Status           string     `gorm:"column:status;not null;index" json:"status"`
	IdempotencyKey   string     `gorm:"column:idempotency_key;not null" json:"idempotency_key"`
	ProviderIntentId *string    `gorm:"column:provider_intent_id" json:"provider_intent_id"`
	ExpiresAt        *time.Time `gorm:"column:expires_at" json:"expires_at"`
	Version          uint64     `gorm:"column:version;not null" json:"version"`
	CreatedAt        time.Time  `json:"created_at"`
	UpdatedAt        time.Time  `json:"updated_at"`
}

// TableName returns the schema-controlled database table.
func (PaymentIntent) TableName() string { return "payment_intents" }
