// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/payment.yaml

package domain

import "context"

// Repository defines persistence operations enabled by the module schema.
type Repository interface {
	Create(context.Context, *PaymentIntent) error
	Get(context.Context, uint64) (*PaymentIntent, error)
	List(context.Context, int, int) ([]PaymentIntent, int64, error)
	Update(context.Context, *PaymentIntent) error
}
