// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/comment.yaml

package domain

import "time"

// Comment is the persistent domain entity for the comment module.
type Comment struct {
	ID            uint64     `gorm:"primaryKey;autoIncrement" json:"id"`
	TargetType    string     `gorm:"column:target_type;not null;index" json:"target_type"`
	TargetId      uint64     `gorm:"column:target_id;not null;index" json:"target_id"`
	AuthorId      uint64     `gorm:"column:author_id;not null;index" json:"author_id"`
	ParentId      *uint64    `gorm:"column:parent_id;index" json:"parent_id"`
	RootId        *uint64    `gorm:"column:root_id;index" json:"root_id"`
	Depth         int64      `gorm:"column:depth;not null" json:"depth"`
	ReplyToUserId *uint64    `gorm:"column:reply_to_user_id" json:"reply_to_user_id"`
	Content       string     `gorm:"column:content;not null" json:"content"`
	Status        string     `gorm:"column:status;not null;index" json:"status"`
	ReviewReason  *string    `gorm:"column:review_reason" json:"review_reason"`
	ReviewedBy    *uint64    `gorm:"column:reviewed_by" json:"reviewed_by"`
	ReviewedAt    *time.Time `gorm:"column:reviewed_at" json:"reviewed_at"`
	Version       uint64     `gorm:"column:version;not null" json:"version"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
}

// TableName returns the schema-controlled database table.
func (Comment) TableName() string { return "comments" }
