// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/comment.yaml

package domain

import "time"

// CommentPin is the persistent domain entity for the comment module.
type CommentPin struct {
	ID         uint64    `gorm:"primaryKey;autoIncrement" json:"id"`
	TargetType string    `gorm:"column:target_type;not null" json:"target_type"`
	TargetId   uint64    `gorm:"column:target_id;not null" json:"target_id"`
	CommentId  uint64    `gorm:"column:comment_id;not null" json:"comment_id"`
	PinnedBy   uint64    `gorm:"column:pinned_by;not null" json:"pinned_by"`
	PinnedAt   time.Time `gorm:"column:pinned_at;not null" json:"pinned_at"`
	Version    uint64    `gorm:"column:version;not null" json:"version"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

// TableName returns the schema-controlled database table.
func (CommentPin) TableName() string { return "comment_pins" }
