// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/weouc-plus/campus-platform/internal/modules/academic_verification/domain"
)

func newAcademicIdentity(db *gorm.DB, opts ...gen.DOOption) academicIdentity {
	_academicIdentity := academicIdentity{}

	_academicIdentity.academicIdentityDo.UseDB(db, opts...)
	_academicIdentity.academicIdentityDo.UseModel(&domain.AcademicIdentity{})

	tableName := _academicIdentity.academicIdentityDo.TableName()
	_academicIdentity.ALL = field.NewAsterisk(tableName)
	_academicIdentity.ID = field.NewUint64(tableName, "id")
	_academicIdentity.UserId = field.NewUint64(tableName, "user_id")
	_academicIdentity.StudentNo = field.NewString(tableName, "student_no")
	_academicIdentity.RealName = field.NewString(tableName, "real_name")
	_academicIdentity.Method = field.NewString(tableName, "method")
	_academicIdentity.Status = field.NewString(tableName, "status")
	_academicIdentity.VerifiedAt = field.NewTime(tableName, "verified_at")
	_academicIdentity.RevokedAt = field.NewTime(tableName, "revoked_at")
	_academicIdentity.RevokeReason = field.NewString(tableName, "revoke_reason")
	_academicIdentity.Version = field.NewUint64(tableName, "version")
	_academicIdentity.CreatedAt = field.NewTime(tableName, "created_at")
	_academicIdentity.UpdatedAt = field.NewTime(tableName, "updated_at")

	_academicIdentity.fillFieldMap()

	return _academicIdentity
}

type academicIdentity struct {
	academicIdentityDo academicIdentityDo

	ALL          field.Asterisk
	ID           field.Uint64
	UserId       field.Uint64
	StudentNo    field.String
	RealName     field.String
	Method       field.String
	Status       field.String
	VerifiedAt   field.Time
	RevokedAt    field.Time
	RevokeReason field.String
	Version      field.Uint64
	CreatedAt    field.Time
	UpdatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (a academicIdentity) Table(newTableName string) *academicIdentity {
	a.academicIdentityDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a academicIdentity) As(alias string) *academicIdentity {
	a.academicIdentityDo.DO = *(a.academicIdentityDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *academicIdentity) updateTableName(table string) *academicIdentity {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewUint64(table, "id")
	a.UserId = field.NewUint64(table, "user_id")
	a.StudentNo = field.NewString(table, "student_no")
	a.RealName = field.NewString(table, "real_name")
	a.Method = field.NewString(table, "method")
	a.Status = field.NewString(table, "status")
	a.VerifiedAt = field.NewTime(table, "verified_at")
	a.RevokedAt = field.NewTime(table, "revoked_at")
	a.RevokeReason = field.NewString(table, "revoke_reason")
	a.Version = field.NewUint64(table, "version")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")

	a.fillFieldMap()

	return a
}

func (a *academicIdentity) WithContext(ctx context.Context) IAcademicIdentityDo {
	return a.academicIdentityDo.WithContext(ctx)
}

func (a academicIdentity) TableName() string { return a.academicIdentityDo.TableName() }

func (a academicIdentity) Alias() string { return a.academicIdentityDo.Alias() }

func (a academicIdentity) Columns(cols ...field.Expr) gen.Columns {
	return a.academicIdentityDo.Columns(cols...)
}

func (a *academicIdentity) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *academicIdentity) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 12)
	a.fieldMap["id"] = a.ID
	a.fieldMap["user_id"] = a.UserId
	a.fieldMap["student_no"] = a.StudentNo
	a.fieldMap["real_name"] = a.RealName
	a.fieldMap["method"] = a.Method
	a.fieldMap["status"] = a.Status
	a.fieldMap["verified_at"] = a.VerifiedAt
	a.fieldMap["revoked_at"] = a.RevokedAt
	a.fieldMap["revoke_reason"] = a.RevokeReason
	a.fieldMap["version"] = a.Version
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
}

func (a academicIdentity) clone(db *gorm.DB) academicIdentity {
	a.academicIdentityDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a academicIdentity) replaceDB(db *gorm.DB) academicIdentity {
	a.academicIdentityDo.ReplaceDB(db)
	return a
}

type academicIdentityDo struct{ gen.DO }

type IAcademicIdentityDo interface {
	gen.SubQuery
	Debug() IAcademicIdentityDo
	WithContext(ctx context.Context) IAcademicIdentityDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAcademicIdentityDo
	WriteDB() IAcademicIdentityDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAcademicIdentityDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAcademicIdentityDo
	Not(conds ...gen.Condition) IAcademicIdentityDo
	Or(conds ...gen.Condition) IAcademicIdentityDo
	Select(conds ...field.Expr) IAcademicIdentityDo
	Where(conds ...gen.Condition) IAcademicIdentityDo
	Order(conds ...field.Expr) IAcademicIdentityDo
	Distinct(cols ...field.Expr) IAcademicIdentityDo
	Omit(cols ...field.Expr) IAcademicIdentityDo
	Join(table schema.Tabler, on ...field.Expr) IAcademicIdentityDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAcademicIdentityDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAcademicIdentityDo
	Group(cols ...field.Expr) IAcademicIdentityDo
	Having(conds ...gen.Condition) IAcademicIdentityDo
	Limit(limit int) IAcademicIdentityDo
	Offset(offset int) IAcademicIdentityDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAcademicIdentityDo
	Unscoped() IAcademicIdentityDo
	Create(values ...*domain.AcademicIdentity) error
	CreateInBatches(values []*domain.AcademicIdentity, batchSize int) error
	Save(values ...*domain.AcademicIdentity) error
	First() (*domain.AcademicIdentity, error)
	Take() (*domain.AcademicIdentity, error)
	Last() (*domain.AcademicIdentity, error)
	Find() ([]*domain.AcademicIdentity, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.AcademicIdentity, err error)
	FindInBatches(result *[]*domain.AcademicIdentity, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*domain.AcademicIdentity) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAcademicIdentityDo
	Assign(attrs ...field.AssignExpr) IAcademicIdentityDo
	Joins(fields ...field.RelationField) IAcademicIdentityDo
	Preload(fields ...field.RelationField) IAcademicIdentityDo
	FirstOrInit() (*domain.AcademicIdentity, error)
	FirstOrCreate() (*domain.AcademicIdentity, error)
	FindByPage(offset int, limit int) (result []*domain.AcademicIdentity, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAcademicIdentityDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a academicIdentityDo) Debug() IAcademicIdentityDo {
	return a.withDO(a.DO.Debug())
}

func (a academicIdentityDo) WithContext(ctx context.Context) IAcademicIdentityDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a academicIdentityDo) ReadDB() IAcademicIdentityDo {
	return a.Clauses(dbresolver.Read)
}

func (a academicIdentityDo) WriteDB() IAcademicIdentityDo {
	return a.Clauses(dbresolver.Write)
}

func (a academicIdentityDo) Session(config *gorm.Session) IAcademicIdentityDo {
	return a.withDO(a.DO.Session(config))
}

func (a academicIdentityDo) Clauses(conds ...clause.Expression) IAcademicIdentityDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a academicIdentityDo) Returning(value interface{}, columns ...string) IAcademicIdentityDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a academicIdentityDo) Not(conds ...gen.Condition) IAcademicIdentityDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a academicIdentityDo) Or(conds ...gen.Condition) IAcademicIdentityDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a academicIdentityDo) Select(conds ...field.Expr) IAcademicIdentityDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a academicIdentityDo) Where(conds ...gen.Condition) IAcademicIdentityDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a academicIdentityDo) Order(conds ...field.Expr) IAcademicIdentityDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a academicIdentityDo) Distinct(cols ...field.Expr) IAcademicIdentityDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a academicIdentityDo) Omit(cols ...field.Expr) IAcademicIdentityDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a academicIdentityDo) Join(table schema.Tabler, on ...field.Expr) IAcademicIdentityDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a academicIdentityDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAcademicIdentityDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a academicIdentityDo) RightJoin(table schema.Tabler, on ...field.Expr) IAcademicIdentityDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a academicIdentityDo) Group(cols ...field.Expr) IAcademicIdentityDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a academicIdentityDo) Having(conds ...gen.Condition) IAcademicIdentityDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a academicIdentityDo) Limit(limit int) IAcademicIdentityDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a academicIdentityDo) Offset(offset int) IAcademicIdentityDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a academicIdentityDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAcademicIdentityDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a academicIdentityDo) Unscoped() IAcademicIdentityDo {
	return a.withDO(a.DO.Unscoped())
}

func (a academicIdentityDo) Create(values ...*domain.AcademicIdentity) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a academicIdentityDo) CreateInBatches(values []*domain.AcademicIdentity, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a academicIdentityDo) Save(values ...*domain.AcademicIdentity) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a academicIdentityDo) First() (*domain.AcademicIdentity, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*domain.AcademicIdentity), nil
	}
}

func (a academicIdentityDo) Take() (*domain.AcademicIdentity, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*domain.AcademicIdentity), nil
	}
}

func (a academicIdentityDo) Last() (*domain.AcademicIdentity, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*domain.AcademicIdentity), nil
	}
}

func (a academicIdentityDo) Find() ([]*domain.AcademicIdentity, error) {
	result, err := a.DO.Find()
	return result.([]*domain.AcademicIdentity), err
}

func (a academicIdentityDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.AcademicIdentity, err error) {
	buf := make([]*domain.AcademicIdentity, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a academicIdentityDo) FindInBatches(result *[]*domain.AcademicIdentity, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a academicIdentityDo) Attrs(attrs ...field.AssignExpr) IAcademicIdentityDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a academicIdentityDo) Assign(attrs ...field.AssignExpr) IAcademicIdentityDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a academicIdentityDo) Joins(fields ...field.RelationField) IAcademicIdentityDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a academicIdentityDo) Preload(fields ...field.RelationField) IAcademicIdentityDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a academicIdentityDo) FirstOrInit() (*domain.AcademicIdentity, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*domain.AcademicIdentity), nil
	}
}

func (a academicIdentityDo) FirstOrCreate() (*domain.AcademicIdentity, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*domain.AcademicIdentity), nil
	}
}

func (a academicIdentityDo) FindByPage(offset int, limit int) (result []*domain.AcademicIdentity, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a academicIdentityDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a academicIdentityDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a academicIdentityDo) Delete(models ...*domain.AcademicIdentity) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *academicIdentityDo) withDO(do gen.Dao) *academicIdentityDo {
	a.DO = *do.(*gen.DO)
	return a
}
