// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/weouc-plus/campus-platform/internal/modules/academic_verification/domain"
)

func newAcademicVerificationMaterial(db *gorm.DB, opts ...gen.DOOption) academicVerificationMaterial {
	_academicVerificationMaterial := academicVerificationMaterial{}

	_academicVerificationMaterial.academicVerificationMaterialDo.UseDB(db, opts...)
	_academicVerificationMaterial.academicVerificationMaterialDo.UseModel(&domain.AcademicVerificationMaterial{})

	tableName := _academicVerificationMaterial.academicVerificationMaterialDo.TableName()
	_academicVerificationMaterial.ALL = field.NewAsterisk(tableName)
	_academicVerificationMaterial.ID = field.NewUint64(tableName, "id")
	_academicVerificationMaterial.UserId = field.NewUint64(tableName, "user_id")
	_academicVerificationMaterial.StorageKey = field.NewString(tableName, "storage_key")
	_academicVerificationMaterial.MimeType = field.NewString(tableName, "mime_type")
	_academicVerificationMaterial.SizeBytes = field.NewInt64(tableName, "size_bytes")
	_academicVerificationMaterial.Sha256 = field.NewString(tableName, "sha256")
	_academicVerificationMaterial.Status = field.NewString(tableName, "status")
	_academicVerificationMaterial.BoundRequestId = field.NewUint64(tableName, "bound_request_id")
	_academicVerificationMaterial.ExpiresAt = field.NewTime(tableName, "expires_at")
	_academicVerificationMaterial.DeleteAfter = field.NewTime(tableName, "delete_after")
	_academicVerificationMaterial.DeletedAt = field.NewTime(tableName, "deleted_at")
	_academicVerificationMaterial.Version = field.NewUint64(tableName, "version")
	_academicVerificationMaterial.CreatedAt = field.NewTime(tableName, "created_at")
	_academicVerificationMaterial.UpdatedAt = field.NewTime(tableName, "updated_at")

	_academicVerificationMaterial.fillFieldMap()

	return _academicVerificationMaterial
}

type academicVerificationMaterial struct {
	academicVerificationMaterialDo academicVerificationMaterialDo

	ALL            field.Asterisk
	ID             field.Uint64
	UserId         field.Uint64
	StorageKey     field.String
	MimeType       field.String
	SizeBytes      field.Int64
	Sha256         field.String
	Status         field.String
	BoundRequestId field.Uint64
	ExpiresAt      field.Time
	DeleteAfter    field.Time
	DeletedAt      field.Time
	Version        field.Uint64
	CreatedAt      field.Time
	UpdatedAt      field.Time

	fieldMap map[string]field.Expr
}

func (a academicVerificationMaterial) Table(newTableName string) *academicVerificationMaterial {
	a.academicVerificationMaterialDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a academicVerificationMaterial) As(alias string) *academicVerificationMaterial {
	a.academicVerificationMaterialDo.DO = *(a.academicVerificationMaterialDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *academicVerificationMaterial) updateTableName(table string) *academicVerificationMaterial {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewUint64(table, "id")
	a.UserId = field.NewUint64(table, "user_id")
	a.StorageKey = field.NewString(table, "storage_key")
	a.MimeType = field.NewString(table, "mime_type")
	a.SizeBytes = field.NewInt64(table, "size_bytes")
	a.Sha256 = field.NewString(table, "sha256")
	a.Status = field.NewString(table, "status")
	a.BoundRequestId = field.NewUint64(table, "bound_request_id")
	a.ExpiresAt = field.NewTime(table, "expires_at")
	a.DeleteAfter = field.NewTime(table, "delete_after")
	a.DeletedAt = field.NewTime(table, "deleted_at")
	a.Version = field.NewUint64(table, "version")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")

	a.fillFieldMap()

	return a
}

func (a *academicVerificationMaterial) WithContext(ctx context.Context) IAcademicVerificationMaterialDo {
	return a.academicVerificationMaterialDo.WithContext(ctx)
}

func (a academicVerificationMaterial) TableName() string {
	return a.academicVerificationMaterialDo.TableName()
}

func (a academicVerificationMaterial) Alias() string { return a.academicVerificationMaterialDo.Alias() }

func (a academicVerificationMaterial) Columns(cols ...field.Expr) gen.Columns {
	return a.academicVerificationMaterialDo.Columns(cols...)
}

func (a *academicVerificationMaterial) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *academicVerificationMaterial) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 14)
	a.fieldMap["id"] = a.ID
	a.fieldMap["user_id"] = a.UserId
	a.fieldMap["storage_key"] = a.StorageKey
	a.fieldMap["mime_type"] = a.MimeType
	a.fieldMap["size_bytes"] = a.SizeBytes
	a.fieldMap["sha256"] = a.Sha256
	a.fieldMap["status"] = a.Status
	a.fieldMap["bound_request_id"] = a.BoundRequestId
	a.fieldMap["expires_at"] = a.ExpiresAt
	a.fieldMap["delete_after"] = a.DeleteAfter
	a.fieldMap["deleted_at"] = a.DeletedAt
	a.fieldMap["version"] = a.Version
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
}

func (a academicVerificationMaterial) clone(db *gorm.DB) academicVerificationMaterial {
	a.academicVerificationMaterialDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a academicVerificationMaterial) replaceDB(db *gorm.DB) academicVerificationMaterial {
	a.academicVerificationMaterialDo.ReplaceDB(db)
	return a
}

type academicVerificationMaterialDo struct{ gen.DO }

type IAcademicVerificationMaterialDo interface {
	gen.SubQuery
	Debug() IAcademicVerificationMaterialDo
	WithContext(ctx context.Context) IAcademicVerificationMaterialDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAcademicVerificationMaterialDo
	WriteDB() IAcademicVerificationMaterialDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAcademicVerificationMaterialDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAcademicVerificationMaterialDo
	Not(conds ...gen.Condition) IAcademicVerificationMaterialDo
	Or(conds ...gen.Condition) IAcademicVerificationMaterialDo
	Select(conds ...field.Expr) IAcademicVerificationMaterialDo
	Where(conds ...gen.Condition) IAcademicVerificationMaterialDo
	Order(conds ...field.Expr) IAcademicVerificationMaterialDo
	Distinct(cols ...field.Expr) IAcademicVerificationMaterialDo
	Omit(cols ...field.Expr) IAcademicVerificationMaterialDo
	Join(table schema.Tabler, on ...field.Expr) IAcademicVerificationMaterialDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAcademicVerificationMaterialDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAcademicVerificationMaterialDo
	Group(cols ...field.Expr) IAcademicVerificationMaterialDo
	Having(conds ...gen.Condition) IAcademicVerificationMaterialDo
	Limit(limit int) IAcademicVerificationMaterialDo
	Offset(offset int) IAcademicVerificationMaterialDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAcademicVerificationMaterialDo
	Unscoped() IAcademicVerificationMaterialDo
	Create(values ...*domain.AcademicVerificationMaterial) error
	CreateInBatches(values []*domain.AcademicVerificationMaterial, batchSize int) error
	Save(values ...*domain.AcademicVerificationMaterial) error
	First() (*domain.AcademicVerificationMaterial, error)
	Take() (*domain.AcademicVerificationMaterial, error)
	Last() (*domain.AcademicVerificationMaterial, error)
	Find() ([]*domain.AcademicVerificationMaterial, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.AcademicVerificationMaterial, err error)
	FindInBatches(result *[]*domain.AcademicVerificationMaterial, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*domain.AcademicVerificationMaterial) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAcademicVerificationMaterialDo
	Assign(attrs ...field.AssignExpr) IAcademicVerificationMaterialDo
	Joins(fields ...field.RelationField) IAcademicVerificationMaterialDo
	Preload(fields ...field.RelationField) IAcademicVerificationMaterialDo
	FirstOrInit() (*domain.AcademicVerificationMaterial, error)
	FirstOrCreate() (*domain.AcademicVerificationMaterial, error)
	FindByPage(offset int, limit int) (result []*domain.AcademicVerificationMaterial, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAcademicVerificationMaterialDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a academicVerificationMaterialDo) Debug() IAcademicVerificationMaterialDo {
	return a.withDO(a.DO.Debug())
}

func (a academicVerificationMaterialDo) WithContext(ctx context.Context) IAcademicVerificationMaterialDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a academicVerificationMaterialDo) ReadDB() IAcademicVerificationMaterialDo {
	return a.Clauses(dbresolver.Read)
}

func (a academicVerificationMaterialDo) WriteDB() IAcademicVerificationMaterialDo {
	return a.Clauses(dbresolver.Write)
}

func (a academicVerificationMaterialDo) Session(config *gorm.Session) IAcademicVerificationMaterialDo {
	return a.withDO(a.DO.Session(config))
}

func (a academicVerificationMaterialDo) Clauses(conds ...clause.Expression) IAcademicVerificationMaterialDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a academicVerificationMaterialDo) Returning(value interface{}, columns ...string) IAcademicVerificationMaterialDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a academicVerificationMaterialDo) Not(conds ...gen.Condition) IAcademicVerificationMaterialDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a academicVerificationMaterialDo) Or(conds ...gen.Condition) IAcademicVerificationMaterialDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a academicVerificationMaterialDo) Select(conds ...field.Expr) IAcademicVerificationMaterialDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a academicVerificationMaterialDo) Where(conds ...gen.Condition) IAcademicVerificationMaterialDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a academicVerificationMaterialDo) Order(conds ...field.Expr) IAcademicVerificationMaterialDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a academicVerificationMaterialDo) Distinct(cols ...field.Expr) IAcademicVerificationMaterialDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a academicVerificationMaterialDo) Omit(cols ...field.Expr) IAcademicVerificationMaterialDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a academicVerificationMaterialDo) Join(table schema.Tabler, on ...field.Expr) IAcademicVerificationMaterialDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a academicVerificationMaterialDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAcademicVerificationMaterialDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a academicVerificationMaterialDo) RightJoin(table schema.Tabler, on ...field.Expr) IAcademicVerificationMaterialDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a academicVerificationMaterialDo) Group(cols ...field.Expr) IAcademicVerificationMaterialDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a academicVerificationMaterialDo) Having(conds ...gen.Condition) IAcademicVerificationMaterialDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a academicVerificationMaterialDo) Limit(limit int) IAcademicVerificationMaterialDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a academicVerificationMaterialDo) Offset(offset int) IAcademicVerificationMaterialDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a academicVerificationMaterialDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAcademicVerificationMaterialDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a academicVerificationMaterialDo) Unscoped() IAcademicVerificationMaterialDo {
	return a.withDO(a.DO.Unscoped())
}

func (a academicVerificationMaterialDo) Create(values ...*domain.AcademicVerificationMaterial) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a academicVerificationMaterialDo) CreateInBatches(values []*domain.AcademicVerificationMaterial, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a academicVerificationMaterialDo) Save(values ...*domain.AcademicVerificationMaterial) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a academicVerificationMaterialDo) First() (*domain.AcademicVerificationMaterial, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*domain.AcademicVerificationMaterial), nil
	}
}

func (a academicVerificationMaterialDo) Take() (*domain.AcademicVerificationMaterial, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*domain.AcademicVerificationMaterial), nil
	}
}

func (a academicVerificationMaterialDo) Last() (*domain.AcademicVerificationMaterial, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*domain.AcademicVerificationMaterial), nil
	}
}

func (a academicVerificationMaterialDo) Find() ([]*domain.AcademicVerificationMaterial, error) {
	result, err := a.DO.Find()
	return result.([]*domain.AcademicVerificationMaterial), err
}

func (a academicVerificationMaterialDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.AcademicVerificationMaterial, err error) {
	buf := make([]*domain.AcademicVerificationMaterial, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a academicVerificationMaterialDo) FindInBatches(result *[]*domain.AcademicVerificationMaterial, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a academicVerificationMaterialDo) Attrs(attrs ...field.AssignExpr) IAcademicVerificationMaterialDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a academicVerificationMaterialDo) Assign(attrs ...field.AssignExpr) IAcademicVerificationMaterialDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a academicVerificationMaterialDo) Joins(fields ...field.RelationField) IAcademicVerificationMaterialDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a academicVerificationMaterialDo) Preload(fields ...field.RelationField) IAcademicVerificationMaterialDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a academicVerificationMaterialDo) FirstOrInit() (*domain.AcademicVerificationMaterial, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*domain.AcademicVerificationMaterial), nil
	}
}

func (a academicVerificationMaterialDo) FirstOrCreate() (*domain.AcademicVerificationMaterial, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*domain.AcademicVerificationMaterial), nil
	}
}

func (a academicVerificationMaterialDo) FindByPage(offset int, limit int) (result []*domain.AcademicVerificationMaterial, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a academicVerificationMaterialDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a academicVerificationMaterialDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a academicVerificationMaterialDo) Delete(models ...*domain.AcademicVerificationMaterial) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *academicVerificationMaterialDo) withDO(do gen.Dao) *academicVerificationMaterialDo {
	a.DO = *do.(*gen.DO)
	return a
}
