// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/weouc-plus/campus-platform/internal/modules/activity/domain"
)

func newActivityRegistration(db *gorm.DB, opts ...gen.DOOption) activityRegistration {
	_activityRegistration := activityRegistration{}

	_activityRegistration.activityRegistrationDo.UseDB(db, opts...)
	_activityRegistration.activityRegistrationDo.UseModel(&domain.ActivityRegistration{})

	tableName := _activityRegistration.activityRegistrationDo.TableName()
	_activityRegistration.ALL = field.NewAsterisk(tableName)
	_activityRegistration.ID = field.NewUint64(tableName, "id")
	_activityRegistration.ActivityId = field.NewUint64(tableName, "activity_id")
	_activityRegistration.UserId = field.NewUint64(tableName, "user_id")
	_activityRegistration.Status = field.NewString(tableName, "status")
	_activityRegistration.RegisteredAt = field.NewTime(tableName, "registered_at")
	_activityRegistration.CancelledAt = field.NewTime(tableName, "cancelled_at")
	_activityRegistration.IdempotencyKey = field.NewString(tableName, "idempotency_key")
	_activityRegistration.Version = field.NewUint64(tableName, "version")
	_activityRegistration.CreatedAt = field.NewTime(tableName, "created_at")
	_activityRegistration.UpdatedAt = field.NewTime(tableName, "updated_at")

	_activityRegistration.fillFieldMap()

	return _activityRegistration
}

type activityRegistration struct {
	activityRegistrationDo activityRegistrationDo

	ALL            field.Asterisk
	ID             field.Uint64
	ActivityId     field.Uint64
	UserId         field.Uint64
	Status         field.String
	RegisteredAt   field.Time
	CancelledAt    field.Time
	IdempotencyKey field.String
	Version        field.Uint64
	CreatedAt      field.Time
	UpdatedAt      field.Time

	fieldMap map[string]field.Expr
}

func (a activityRegistration) Table(newTableName string) *activityRegistration {
	a.activityRegistrationDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a activityRegistration) As(alias string) *activityRegistration {
	a.activityRegistrationDo.DO = *(a.activityRegistrationDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *activityRegistration) updateTableName(table string) *activityRegistration {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewUint64(table, "id")
	a.ActivityId = field.NewUint64(table, "activity_id")
	a.UserId = field.NewUint64(table, "user_id")
	a.Status = field.NewString(table, "status")
	a.RegisteredAt = field.NewTime(table, "registered_at")
	a.CancelledAt = field.NewTime(table, "cancelled_at")
	a.IdempotencyKey = field.NewString(table, "idempotency_key")
	a.Version = field.NewUint64(table, "version")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")

	a.fillFieldMap()

	return a
}

func (a *activityRegistration) WithContext(ctx context.Context) IActivityRegistrationDo {
	return a.activityRegistrationDo.WithContext(ctx)
}

func (a activityRegistration) TableName() string { return a.activityRegistrationDo.TableName() }

func (a activityRegistration) Alias() string { return a.activityRegistrationDo.Alias() }

func (a activityRegistration) Columns(cols ...field.Expr) gen.Columns {
	return a.activityRegistrationDo.Columns(cols...)
}

func (a *activityRegistration) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *activityRegistration) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 10)
	a.fieldMap["id"] = a.ID
	a.fieldMap["activity_id"] = a.ActivityId
	a.fieldMap["user_id"] = a.UserId
	a.fieldMap["status"] = a.Status
	a.fieldMap["registered_at"] = a.RegisteredAt
	a.fieldMap["cancelled_at"] = a.CancelledAt
	a.fieldMap["idempotency_key"] = a.IdempotencyKey
	a.fieldMap["version"] = a.Version
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
}

func (a activityRegistration) clone(db *gorm.DB) activityRegistration {
	a.activityRegistrationDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a activityRegistration) replaceDB(db *gorm.DB) activityRegistration {
	a.activityRegistrationDo.ReplaceDB(db)
	return a
}

type activityRegistrationDo struct{ gen.DO }

type IActivityRegistrationDo interface {
	gen.SubQuery
	Debug() IActivityRegistrationDo
	WithContext(ctx context.Context) IActivityRegistrationDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IActivityRegistrationDo
	WriteDB() IActivityRegistrationDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IActivityRegistrationDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IActivityRegistrationDo
	Not(conds ...gen.Condition) IActivityRegistrationDo
	Or(conds ...gen.Condition) IActivityRegistrationDo
	Select(conds ...field.Expr) IActivityRegistrationDo
	Where(conds ...gen.Condition) IActivityRegistrationDo
	Order(conds ...field.Expr) IActivityRegistrationDo
	Distinct(cols ...field.Expr) IActivityRegistrationDo
	Omit(cols ...field.Expr) IActivityRegistrationDo
	Join(table schema.Tabler, on ...field.Expr) IActivityRegistrationDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IActivityRegistrationDo
	RightJoin(table schema.Tabler, on ...field.Expr) IActivityRegistrationDo
	Group(cols ...field.Expr) IActivityRegistrationDo
	Having(conds ...gen.Condition) IActivityRegistrationDo
	Limit(limit int) IActivityRegistrationDo
	Offset(offset int) IActivityRegistrationDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IActivityRegistrationDo
	Unscoped() IActivityRegistrationDo
	Create(values ...*domain.ActivityRegistration) error
	CreateInBatches(values []*domain.ActivityRegistration, batchSize int) error
	Save(values ...*domain.ActivityRegistration) error
	First() (*domain.ActivityRegistration, error)
	Take() (*domain.ActivityRegistration, error)
	Last() (*domain.ActivityRegistration, error)
	Find() ([]*domain.ActivityRegistration, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.ActivityRegistration, err error)
	FindInBatches(result *[]*domain.ActivityRegistration, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*domain.ActivityRegistration) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IActivityRegistrationDo
	Assign(attrs ...field.AssignExpr) IActivityRegistrationDo
	Joins(fields ...field.RelationField) IActivityRegistrationDo
	Preload(fields ...field.RelationField) IActivityRegistrationDo
	FirstOrInit() (*domain.ActivityRegistration, error)
	FirstOrCreate() (*domain.ActivityRegistration, error)
	FindByPage(offset int, limit int) (result []*domain.ActivityRegistration, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IActivityRegistrationDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a activityRegistrationDo) Debug() IActivityRegistrationDo {
	return a.withDO(a.DO.Debug())
}

func (a activityRegistrationDo) WithContext(ctx context.Context) IActivityRegistrationDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a activityRegistrationDo) ReadDB() IActivityRegistrationDo {
	return a.Clauses(dbresolver.Read)
}

func (a activityRegistrationDo) WriteDB() IActivityRegistrationDo {
	return a.Clauses(dbresolver.Write)
}

func (a activityRegistrationDo) Session(config *gorm.Session) IActivityRegistrationDo {
	return a.withDO(a.DO.Session(config))
}

func (a activityRegistrationDo) Clauses(conds ...clause.Expression) IActivityRegistrationDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a activityRegistrationDo) Returning(value interface{}, columns ...string) IActivityRegistrationDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a activityRegistrationDo) Not(conds ...gen.Condition) IActivityRegistrationDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a activityRegistrationDo) Or(conds ...gen.Condition) IActivityRegistrationDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a activityRegistrationDo) Select(conds ...field.Expr) IActivityRegistrationDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a activityRegistrationDo) Where(conds ...gen.Condition) IActivityRegistrationDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a activityRegistrationDo) Order(conds ...field.Expr) IActivityRegistrationDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a activityRegistrationDo) Distinct(cols ...field.Expr) IActivityRegistrationDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a activityRegistrationDo) Omit(cols ...field.Expr) IActivityRegistrationDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a activityRegistrationDo) Join(table schema.Tabler, on ...field.Expr) IActivityRegistrationDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a activityRegistrationDo) LeftJoin(table schema.Tabler, on ...field.Expr) IActivityRegistrationDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a activityRegistrationDo) RightJoin(table schema.Tabler, on ...field.Expr) IActivityRegistrationDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a activityRegistrationDo) Group(cols ...field.Expr) IActivityRegistrationDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a activityRegistrationDo) Having(conds ...gen.Condition) IActivityRegistrationDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a activityRegistrationDo) Limit(limit int) IActivityRegistrationDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a activityRegistrationDo) Offset(offset int) IActivityRegistrationDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a activityRegistrationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IActivityRegistrationDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a activityRegistrationDo) Unscoped() IActivityRegistrationDo {
	return a.withDO(a.DO.Unscoped())
}

func (a activityRegistrationDo) Create(values ...*domain.ActivityRegistration) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a activityRegistrationDo) CreateInBatches(values []*domain.ActivityRegistration, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a activityRegistrationDo) Save(values ...*domain.ActivityRegistration) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a activityRegistrationDo) First() (*domain.ActivityRegistration, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*domain.ActivityRegistration), nil
	}
}

func (a activityRegistrationDo) Take() (*domain.ActivityRegistration, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*domain.ActivityRegistration), nil
	}
}

func (a activityRegistrationDo) Last() (*domain.ActivityRegistration, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*domain.ActivityRegistration), nil
	}
}

func (a activityRegistrationDo) Find() ([]*domain.ActivityRegistration, error) {
	result, err := a.DO.Find()
	return result.([]*domain.ActivityRegistration), err
}

func (a activityRegistrationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.ActivityRegistration, err error) {
	buf := make([]*domain.ActivityRegistration, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a activityRegistrationDo) FindInBatches(result *[]*domain.ActivityRegistration, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a activityRegistrationDo) Attrs(attrs ...field.AssignExpr) IActivityRegistrationDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a activityRegistrationDo) Assign(attrs ...field.AssignExpr) IActivityRegistrationDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a activityRegistrationDo) Joins(fields ...field.RelationField) IActivityRegistrationDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a activityRegistrationDo) Preload(fields ...field.RelationField) IActivityRegistrationDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a activityRegistrationDo) FirstOrInit() (*domain.ActivityRegistration, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*domain.ActivityRegistration), nil
	}
}

func (a activityRegistrationDo) FirstOrCreate() (*domain.ActivityRegistration, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*domain.ActivityRegistration), nil
	}
}

func (a activityRegistrationDo) FindByPage(offset int, limit int) (result []*domain.ActivityRegistration, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a activityRegistrationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a activityRegistrationDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a activityRegistrationDo) Delete(models ...*domain.ActivityRegistration) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *activityRegistrationDo) withDO(do gen.Dao) *activityRegistrationDo {
	a.DO = *do.(*gen.DO)
	return a
}
