// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/weouc-plus/campus-platform/internal/modules/campus_circle/domain"
)

func newCampusCirclePost(db *gorm.DB, opts ...gen.DOOption) campusCirclePost {
	_campusCirclePost := campusCirclePost{}

	_campusCirclePost.campusCirclePostDo.UseDB(db, opts...)
	_campusCirclePost.campusCirclePostDo.UseModel(&domain.CampusCirclePost{})

	tableName := _campusCirclePost.campusCirclePostDo.TableName()
	_campusCirclePost.ALL = field.NewAsterisk(tableName)
	_campusCirclePost.ID = field.NewUint64(tableName, "id")
	_campusCirclePost.SectionId = field.NewUint64(tableName, "section_id")
	_campusCirclePost.AuthorId = field.NewUint64(tableName, "author_id")
	_campusCirclePost.Title = field.NewString(tableName, "title")
	_campusCirclePost.Content = field.NewString(tableName, "content")
	_campusCirclePost.Status = field.NewString(tableName, "status")
	_campusCirclePost.ReviewReason = field.NewString(tableName, "review_reason")
	_campusCirclePost.ReviewedBy = field.NewUint64(tableName, "reviewed_by")
	_campusCirclePost.ReviewedAt = field.NewTime(tableName, "reviewed_at")
	_campusCirclePost.PublishedAt = field.NewTime(tableName, "published_at")
	_campusCirclePost.Version = field.NewUint64(tableName, "version")
	_campusCirclePost.CreatedAt = field.NewTime(tableName, "created_at")
	_campusCirclePost.UpdatedAt = field.NewTime(tableName, "updated_at")

	_campusCirclePost.fillFieldMap()

	return _campusCirclePost
}

type campusCirclePost struct {
	campusCirclePostDo campusCirclePostDo

	ALL          field.Asterisk
	ID           field.Uint64
	SectionId    field.Uint64
	AuthorId     field.Uint64
	Title        field.String
	Content      field.String
	Status       field.String
	ReviewReason field.String
	ReviewedBy   field.Uint64
	ReviewedAt   field.Time
	PublishedAt  field.Time
	Version      field.Uint64
	CreatedAt    field.Time
	UpdatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (c campusCirclePost) Table(newTableName string) *campusCirclePost {
	c.campusCirclePostDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c campusCirclePost) As(alias string) *campusCirclePost {
	c.campusCirclePostDo.DO = *(c.campusCirclePostDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *campusCirclePost) updateTableName(table string) *campusCirclePost {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewUint64(table, "id")
	c.SectionId = field.NewUint64(table, "section_id")
	c.AuthorId = field.NewUint64(table, "author_id")
	c.Title = field.NewString(table, "title")
	c.Content = field.NewString(table, "content")
	c.Status = field.NewString(table, "status")
	c.ReviewReason = field.NewString(table, "review_reason")
	c.ReviewedBy = field.NewUint64(table, "reviewed_by")
	c.ReviewedAt = field.NewTime(table, "reviewed_at")
	c.PublishedAt = field.NewTime(table, "published_at")
	c.Version = field.NewUint64(table, "version")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")

	c.fillFieldMap()

	return c
}

func (c *campusCirclePost) WithContext(ctx context.Context) ICampusCirclePostDo {
	return c.campusCirclePostDo.WithContext(ctx)
}

func (c campusCirclePost) TableName() string { return c.campusCirclePostDo.TableName() }

func (c campusCirclePost) Alias() string { return c.campusCirclePostDo.Alias() }

func (c campusCirclePost) Columns(cols ...field.Expr) gen.Columns {
	return c.campusCirclePostDo.Columns(cols...)
}

func (c *campusCirclePost) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *campusCirclePost) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 13)
	c.fieldMap["id"] = c.ID
	c.fieldMap["section_id"] = c.SectionId
	c.fieldMap["author_id"] = c.AuthorId
	c.fieldMap["title"] = c.Title
	c.fieldMap["content"] = c.Content
	c.fieldMap["status"] = c.Status
	c.fieldMap["review_reason"] = c.ReviewReason
	c.fieldMap["reviewed_by"] = c.ReviewedBy
	c.fieldMap["reviewed_at"] = c.ReviewedAt
	c.fieldMap["published_at"] = c.PublishedAt
	c.fieldMap["version"] = c.Version
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
}

func (c campusCirclePost) clone(db *gorm.DB) campusCirclePost {
	c.campusCirclePostDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c campusCirclePost) replaceDB(db *gorm.DB) campusCirclePost {
	c.campusCirclePostDo.ReplaceDB(db)
	return c
}

type campusCirclePostDo struct{ gen.DO }

type ICampusCirclePostDo interface {
	gen.SubQuery
	Debug() ICampusCirclePostDo
	WithContext(ctx context.Context) ICampusCirclePostDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICampusCirclePostDo
	WriteDB() ICampusCirclePostDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICampusCirclePostDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICampusCirclePostDo
	Not(conds ...gen.Condition) ICampusCirclePostDo
	Or(conds ...gen.Condition) ICampusCirclePostDo
	Select(conds ...field.Expr) ICampusCirclePostDo
	Where(conds ...gen.Condition) ICampusCirclePostDo
	Order(conds ...field.Expr) ICampusCirclePostDo
	Distinct(cols ...field.Expr) ICampusCirclePostDo
	Omit(cols ...field.Expr) ICampusCirclePostDo
	Join(table schema.Tabler, on ...field.Expr) ICampusCirclePostDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICampusCirclePostDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICampusCirclePostDo
	Group(cols ...field.Expr) ICampusCirclePostDo
	Having(conds ...gen.Condition) ICampusCirclePostDo
	Limit(limit int) ICampusCirclePostDo
	Offset(offset int) ICampusCirclePostDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICampusCirclePostDo
	Unscoped() ICampusCirclePostDo
	Create(values ...*domain.CampusCirclePost) error
	CreateInBatches(values []*domain.CampusCirclePost, batchSize int) error
	Save(values ...*domain.CampusCirclePost) error
	First() (*domain.CampusCirclePost, error)
	Take() (*domain.CampusCirclePost, error)
	Last() (*domain.CampusCirclePost, error)
	Find() ([]*domain.CampusCirclePost, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.CampusCirclePost, err error)
	FindInBatches(result *[]*domain.CampusCirclePost, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*domain.CampusCirclePost) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICampusCirclePostDo
	Assign(attrs ...field.AssignExpr) ICampusCirclePostDo
	Joins(fields ...field.RelationField) ICampusCirclePostDo
	Preload(fields ...field.RelationField) ICampusCirclePostDo
	FirstOrInit() (*domain.CampusCirclePost, error)
	FirstOrCreate() (*domain.CampusCirclePost, error)
	FindByPage(offset int, limit int) (result []*domain.CampusCirclePost, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICampusCirclePostDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c campusCirclePostDo) Debug() ICampusCirclePostDo {
	return c.withDO(c.DO.Debug())
}

func (c campusCirclePostDo) WithContext(ctx context.Context) ICampusCirclePostDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c campusCirclePostDo) ReadDB() ICampusCirclePostDo {
	return c.Clauses(dbresolver.Read)
}

func (c campusCirclePostDo) WriteDB() ICampusCirclePostDo {
	return c.Clauses(dbresolver.Write)
}

func (c campusCirclePostDo) Session(config *gorm.Session) ICampusCirclePostDo {
	return c.withDO(c.DO.Session(config))
}

func (c campusCirclePostDo) Clauses(conds ...clause.Expression) ICampusCirclePostDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c campusCirclePostDo) Returning(value interface{}, columns ...string) ICampusCirclePostDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c campusCirclePostDo) Not(conds ...gen.Condition) ICampusCirclePostDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c campusCirclePostDo) Or(conds ...gen.Condition) ICampusCirclePostDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c campusCirclePostDo) Select(conds ...field.Expr) ICampusCirclePostDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c campusCirclePostDo) Where(conds ...gen.Condition) ICampusCirclePostDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c campusCirclePostDo) Order(conds ...field.Expr) ICampusCirclePostDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c campusCirclePostDo) Distinct(cols ...field.Expr) ICampusCirclePostDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c campusCirclePostDo) Omit(cols ...field.Expr) ICampusCirclePostDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c campusCirclePostDo) Join(table schema.Tabler, on ...field.Expr) ICampusCirclePostDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c campusCirclePostDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICampusCirclePostDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c campusCirclePostDo) RightJoin(table schema.Tabler, on ...field.Expr) ICampusCirclePostDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c campusCirclePostDo) Group(cols ...field.Expr) ICampusCirclePostDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c campusCirclePostDo) Having(conds ...gen.Condition) ICampusCirclePostDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c campusCirclePostDo) Limit(limit int) ICampusCirclePostDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c campusCirclePostDo) Offset(offset int) ICampusCirclePostDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c campusCirclePostDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICampusCirclePostDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c campusCirclePostDo) Unscoped() ICampusCirclePostDo {
	return c.withDO(c.DO.Unscoped())
}

func (c campusCirclePostDo) Create(values ...*domain.CampusCirclePost) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c campusCirclePostDo) CreateInBatches(values []*domain.CampusCirclePost, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c campusCirclePostDo) Save(values ...*domain.CampusCirclePost) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c campusCirclePostDo) First() (*domain.CampusCirclePost, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*domain.CampusCirclePost), nil
	}
}

func (c campusCirclePostDo) Take() (*domain.CampusCirclePost, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*domain.CampusCirclePost), nil
	}
}

func (c campusCirclePostDo) Last() (*domain.CampusCirclePost, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*domain.CampusCirclePost), nil
	}
}

func (c campusCirclePostDo) Find() ([]*domain.CampusCirclePost, error) {
	result, err := c.DO.Find()
	return result.([]*domain.CampusCirclePost), err
}

func (c campusCirclePostDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.CampusCirclePost, err error) {
	buf := make([]*domain.CampusCirclePost, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c campusCirclePostDo) FindInBatches(result *[]*domain.CampusCirclePost, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c campusCirclePostDo) Attrs(attrs ...field.AssignExpr) ICampusCirclePostDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c campusCirclePostDo) Assign(attrs ...field.AssignExpr) ICampusCirclePostDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c campusCirclePostDo) Joins(fields ...field.RelationField) ICampusCirclePostDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c campusCirclePostDo) Preload(fields ...field.RelationField) ICampusCirclePostDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c campusCirclePostDo) FirstOrInit() (*domain.CampusCirclePost, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*domain.CampusCirclePost), nil
	}
}

func (c campusCirclePostDo) FirstOrCreate() (*domain.CampusCirclePost, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*domain.CampusCirclePost), nil
	}
}

func (c campusCirclePostDo) FindByPage(offset int, limit int) (result []*domain.CampusCirclePost, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c campusCirclePostDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c campusCirclePostDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c campusCirclePostDo) Delete(models ...*domain.CampusCirclePost) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *campusCirclePostDo) withDO(do gen.Dao) *campusCirclePostDo {
	c.DO = *do.(*gen.DO)
	return c
}
