// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/weouc-plus/campus-platform/internal/modules/campus_circle/domain"
)

func newCampusCirclePostImage(db *gorm.DB, opts ...gen.DOOption) campusCirclePostImage {
	_campusCirclePostImage := campusCirclePostImage{}

	_campusCirclePostImage.campusCirclePostImageDo.UseDB(db, opts...)
	_campusCirclePostImage.campusCirclePostImageDo.UseModel(&domain.CampusCirclePostImage{})

	tableName := _campusCirclePostImage.campusCirclePostImageDo.TableName()
	_campusCirclePostImage.ALL = field.NewAsterisk(tableName)
	_campusCirclePostImage.ID = field.NewUint64(tableName, "id")
	_campusCirclePostImage.PostId = field.NewUint64(tableName, "post_id")
	_campusCirclePostImage.Url = field.NewString(tableName, "url")
	_campusCirclePostImage.SortOrder = field.NewInt64(tableName, "sort_order")
	_campusCirclePostImage.CreatedAt = field.NewTime(tableName, "created_at")
	_campusCirclePostImage.UpdatedAt = field.NewTime(tableName, "updated_at")

	_campusCirclePostImage.fillFieldMap()

	return _campusCirclePostImage
}

type campusCirclePostImage struct {
	campusCirclePostImageDo campusCirclePostImageDo

	ALL       field.Asterisk
	ID        field.Uint64
	PostId    field.Uint64
	Url       field.String
	SortOrder field.Int64
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (c campusCirclePostImage) Table(newTableName string) *campusCirclePostImage {
	c.campusCirclePostImageDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c campusCirclePostImage) As(alias string) *campusCirclePostImage {
	c.campusCirclePostImageDo.DO = *(c.campusCirclePostImageDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *campusCirclePostImage) updateTableName(table string) *campusCirclePostImage {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewUint64(table, "id")
	c.PostId = field.NewUint64(table, "post_id")
	c.Url = field.NewString(table, "url")
	c.SortOrder = field.NewInt64(table, "sort_order")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")

	c.fillFieldMap()

	return c
}

func (c *campusCirclePostImage) WithContext(ctx context.Context) ICampusCirclePostImageDo {
	return c.campusCirclePostImageDo.WithContext(ctx)
}

func (c campusCirclePostImage) TableName() string { return c.campusCirclePostImageDo.TableName() }

func (c campusCirclePostImage) Alias() string { return c.campusCirclePostImageDo.Alias() }

func (c campusCirclePostImage) Columns(cols ...field.Expr) gen.Columns {
	return c.campusCirclePostImageDo.Columns(cols...)
}

func (c *campusCirclePostImage) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *campusCirclePostImage) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 6)
	c.fieldMap["id"] = c.ID
	c.fieldMap["post_id"] = c.PostId
	c.fieldMap["url"] = c.Url
	c.fieldMap["sort_order"] = c.SortOrder
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
}

func (c campusCirclePostImage) clone(db *gorm.DB) campusCirclePostImage {
	c.campusCirclePostImageDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c campusCirclePostImage) replaceDB(db *gorm.DB) campusCirclePostImage {
	c.campusCirclePostImageDo.ReplaceDB(db)
	return c
}

type campusCirclePostImageDo struct{ gen.DO }

type ICampusCirclePostImageDo interface {
	gen.SubQuery
	Debug() ICampusCirclePostImageDo
	WithContext(ctx context.Context) ICampusCirclePostImageDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICampusCirclePostImageDo
	WriteDB() ICampusCirclePostImageDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICampusCirclePostImageDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICampusCirclePostImageDo
	Not(conds ...gen.Condition) ICampusCirclePostImageDo
	Or(conds ...gen.Condition) ICampusCirclePostImageDo
	Select(conds ...field.Expr) ICampusCirclePostImageDo
	Where(conds ...gen.Condition) ICampusCirclePostImageDo
	Order(conds ...field.Expr) ICampusCirclePostImageDo
	Distinct(cols ...field.Expr) ICampusCirclePostImageDo
	Omit(cols ...field.Expr) ICampusCirclePostImageDo
	Join(table schema.Tabler, on ...field.Expr) ICampusCirclePostImageDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICampusCirclePostImageDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICampusCirclePostImageDo
	Group(cols ...field.Expr) ICampusCirclePostImageDo
	Having(conds ...gen.Condition) ICampusCirclePostImageDo
	Limit(limit int) ICampusCirclePostImageDo
	Offset(offset int) ICampusCirclePostImageDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICampusCirclePostImageDo
	Unscoped() ICampusCirclePostImageDo
	Create(values ...*domain.CampusCirclePostImage) error
	CreateInBatches(values []*domain.CampusCirclePostImage, batchSize int) error
	Save(values ...*domain.CampusCirclePostImage) error
	First() (*domain.CampusCirclePostImage, error)
	Take() (*domain.CampusCirclePostImage, error)
	Last() (*domain.CampusCirclePostImage, error)
	Find() ([]*domain.CampusCirclePostImage, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.CampusCirclePostImage, err error)
	FindInBatches(result *[]*domain.CampusCirclePostImage, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*domain.CampusCirclePostImage) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICampusCirclePostImageDo
	Assign(attrs ...field.AssignExpr) ICampusCirclePostImageDo
	Joins(fields ...field.RelationField) ICampusCirclePostImageDo
	Preload(fields ...field.RelationField) ICampusCirclePostImageDo
	FirstOrInit() (*domain.CampusCirclePostImage, error)
	FirstOrCreate() (*domain.CampusCirclePostImage, error)
	FindByPage(offset int, limit int) (result []*domain.CampusCirclePostImage, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICampusCirclePostImageDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c campusCirclePostImageDo) Debug() ICampusCirclePostImageDo {
	return c.withDO(c.DO.Debug())
}

func (c campusCirclePostImageDo) WithContext(ctx context.Context) ICampusCirclePostImageDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c campusCirclePostImageDo) ReadDB() ICampusCirclePostImageDo {
	return c.Clauses(dbresolver.Read)
}

func (c campusCirclePostImageDo) WriteDB() ICampusCirclePostImageDo {
	return c.Clauses(dbresolver.Write)
}

func (c campusCirclePostImageDo) Session(config *gorm.Session) ICampusCirclePostImageDo {
	return c.withDO(c.DO.Session(config))
}

func (c campusCirclePostImageDo) Clauses(conds ...clause.Expression) ICampusCirclePostImageDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c campusCirclePostImageDo) Returning(value interface{}, columns ...string) ICampusCirclePostImageDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c campusCirclePostImageDo) Not(conds ...gen.Condition) ICampusCirclePostImageDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c campusCirclePostImageDo) Or(conds ...gen.Condition) ICampusCirclePostImageDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c campusCirclePostImageDo) Select(conds ...field.Expr) ICampusCirclePostImageDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c campusCirclePostImageDo) Where(conds ...gen.Condition) ICampusCirclePostImageDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c campusCirclePostImageDo) Order(conds ...field.Expr) ICampusCirclePostImageDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c campusCirclePostImageDo) Distinct(cols ...field.Expr) ICampusCirclePostImageDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c campusCirclePostImageDo) Omit(cols ...field.Expr) ICampusCirclePostImageDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c campusCirclePostImageDo) Join(table schema.Tabler, on ...field.Expr) ICampusCirclePostImageDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c campusCirclePostImageDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICampusCirclePostImageDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c campusCirclePostImageDo) RightJoin(table schema.Tabler, on ...field.Expr) ICampusCirclePostImageDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c campusCirclePostImageDo) Group(cols ...field.Expr) ICampusCirclePostImageDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c campusCirclePostImageDo) Having(conds ...gen.Condition) ICampusCirclePostImageDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c campusCirclePostImageDo) Limit(limit int) ICampusCirclePostImageDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c campusCirclePostImageDo) Offset(offset int) ICampusCirclePostImageDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c campusCirclePostImageDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICampusCirclePostImageDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c campusCirclePostImageDo) Unscoped() ICampusCirclePostImageDo {
	return c.withDO(c.DO.Unscoped())
}

func (c campusCirclePostImageDo) Create(values ...*domain.CampusCirclePostImage) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c campusCirclePostImageDo) CreateInBatches(values []*domain.CampusCirclePostImage, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c campusCirclePostImageDo) Save(values ...*domain.CampusCirclePostImage) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c campusCirclePostImageDo) First() (*domain.CampusCirclePostImage, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*domain.CampusCirclePostImage), nil
	}
}

func (c campusCirclePostImageDo) Take() (*domain.CampusCirclePostImage, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*domain.CampusCirclePostImage), nil
	}
}

func (c campusCirclePostImageDo) Last() (*domain.CampusCirclePostImage, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*domain.CampusCirclePostImage), nil
	}
}

func (c campusCirclePostImageDo) Find() ([]*domain.CampusCirclePostImage, error) {
	result, err := c.DO.Find()
	return result.([]*domain.CampusCirclePostImage), err
}

func (c campusCirclePostImageDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.CampusCirclePostImage, err error) {
	buf := make([]*domain.CampusCirclePostImage, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c campusCirclePostImageDo) FindInBatches(result *[]*domain.CampusCirclePostImage, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c campusCirclePostImageDo) Attrs(attrs ...field.AssignExpr) ICampusCirclePostImageDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c campusCirclePostImageDo) Assign(attrs ...field.AssignExpr) ICampusCirclePostImageDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c campusCirclePostImageDo) Joins(fields ...field.RelationField) ICampusCirclePostImageDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c campusCirclePostImageDo) Preload(fields ...field.RelationField) ICampusCirclePostImageDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c campusCirclePostImageDo) FirstOrInit() (*domain.CampusCirclePostImage, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*domain.CampusCirclePostImage), nil
	}
}

func (c campusCirclePostImageDo) FirstOrCreate() (*domain.CampusCirclePostImage, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*domain.CampusCirclePostImage), nil
	}
}

func (c campusCirclePostImageDo) FindByPage(offset int, limit int) (result []*domain.CampusCirclePostImage, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c campusCirclePostImageDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c campusCirclePostImageDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c campusCirclePostImageDo) Delete(models ...*domain.CampusCirclePostImage) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *campusCirclePostImageDo) withDO(do gen.Dao) *campusCirclePostImageDo {
	c.DO = *do.(*gen.DO)
	return c
}
