// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/weouc-plus/campus-platform/internal/modules/campus_circle/domain"
)

func newCampusCirclePostLike(db *gorm.DB, opts ...gen.DOOption) campusCirclePostLike {
	_campusCirclePostLike := campusCirclePostLike{}

	_campusCirclePostLike.campusCirclePostLikeDo.UseDB(db, opts...)
	_campusCirclePostLike.campusCirclePostLikeDo.UseModel(&domain.CampusCirclePostLike{})

	tableName := _campusCirclePostLike.campusCirclePostLikeDo.TableName()
	_campusCirclePostLike.ALL = field.NewAsterisk(tableName)
	_campusCirclePostLike.ID = field.NewUint64(tableName, "id")
	_campusCirclePostLike.PostId = field.NewUint64(tableName, "post_id")
	_campusCirclePostLike.UserId = field.NewUint64(tableName, "user_id")
	_campusCirclePostLike.CreatedAt = field.NewTime(tableName, "created_at")
	_campusCirclePostLike.UpdatedAt = field.NewTime(tableName, "updated_at")

	_campusCirclePostLike.fillFieldMap()

	return _campusCirclePostLike
}

type campusCirclePostLike struct {
	campusCirclePostLikeDo campusCirclePostLikeDo

	ALL       field.Asterisk
	ID        field.Uint64
	PostId    field.Uint64
	UserId    field.Uint64
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (c campusCirclePostLike) Table(newTableName string) *campusCirclePostLike {
	c.campusCirclePostLikeDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c campusCirclePostLike) As(alias string) *campusCirclePostLike {
	c.campusCirclePostLikeDo.DO = *(c.campusCirclePostLikeDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *campusCirclePostLike) updateTableName(table string) *campusCirclePostLike {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewUint64(table, "id")
	c.PostId = field.NewUint64(table, "post_id")
	c.UserId = field.NewUint64(table, "user_id")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")

	c.fillFieldMap()

	return c
}

func (c *campusCirclePostLike) WithContext(ctx context.Context) ICampusCirclePostLikeDo {
	return c.campusCirclePostLikeDo.WithContext(ctx)
}

func (c campusCirclePostLike) TableName() string { return c.campusCirclePostLikeDo.TableName() }

func (c campusCirclePostLike) Alias() string { return c.campusCirclePostLikeDo.Alias() }

func (c campusCirclePostLike) Columns(cols ...field.Expr) gen.Columns {
	return c.campusCirclePostLikeDo.Columns(cols...)
}

func (c *campusCirclePostLike) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *campusCirclePostLike) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 5)
	c.fieldMap["id"] = c.ID
	c.fieldMap["post_id"] = c.PostId
	c.fieldMap["user_id"] = c.UserId
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
}

func (c campusCirclePostLike) clone(db *gorm.DB) campusCirclePostLike {
	c.campusCirclePostLikeDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c campusCirclePostLike) replaceDB(db *gorm.DB) campusCirclePostLike {
	c.campusCirclePostLikeDo.ReplaceDB(db)
	return c
}

type campusCirclePostLikeDo struct{ gen.DO }

type ICampusCirclePostLikeDo interface {
	gen.SubQuery
	Debug() ICampusCirclePostLikeDo
	WithContext(ctx context.Context) ICampusCirclePostLikeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICampusCirclePostLikeDo
	WriteDB() ICampusCirclePostLikeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICampusCirclePostLikeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICampusCirclePostLikeDo
	Not(conds ...gen.Condition) ICampusCirclePostLikeDo
	Or(conds ...gen.Condition) ICampusCirclePostLikeDo
	Select(conds ...field.Expr) ICampusCirclePostLikeDo
	Where(conds ...gen.Condition) ICampusCirclePostLikeDo
	Order(conds ...field.Expr) ICampusCirclePostLikeDo
	Distinct(cols ...field.Expr) ICampusCirclePostLikeDo
	Omit(cols ...field.Expr) ICampusCirclePostLikeDo
	Join(table schema.Tabler, on ...field.Expr) ICampusCirclePostLikeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICampusCirclePostLikeDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICampusCirclePostLikeDo
	Group(cols ...field.Expr) ICampusCirclePostLikeDo
	Having(conds ...gen.Condition) ICampusCirclePostLikeDo
	Limit(limit int) ICampusCirclePostLikeDo
	Offset(offset int) ICampusCirclePostLikeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICampusCirclePostLikeDo
	Unscoped() ICampusCirclePostLikeDo
	Create(values ...*domain.CampusCirclePostLike) error
	CreateInBatches(values []*domain.CampusCirclePostLike, batchSize int) error
	Save(values ...*domain.CampusCirclePostLike) error
	First() (*domain.CampusCirclePostLike, error)
	Take() (*domain.CampusCirclePostLike, error)
	Last() (*domain.CampusCirclePostLike, error)
	Find() ([]*domain.CampusCirclePostLike, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.CampusCirclePostLike, err error)
	FindInBatches(result *[]*domain.CampusCirclePostLike, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*domain.CampusCirclePostLike) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICampusCirclePostLikeDo
	Assign(attrs ...field.AssignExpr) ICampusCirclePostLikeDo
	Joins(fields ...field.RelationField) ICampusCirclePostLikeDo
	Preload(fields ...field.RelationField) ICampusCirclePostLikeDo
	FirstOrInit() (*domain.CampusCirclePostLike, error)
	FirstOrCreate() (*domain.CampusCirclePostLike, error)
	FindByPage(offset int, limit int) (result []*domain.CampusCirclePostLike, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICampusCirclePostLikeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c campusCirclePostLikeDo) Debug() ICampusCirclePostLikeDo {
	return c.withDO(c.DO.Debug())
}

func (c campusCirclePostLikeDo) WithContext(ctx context.Context) ICampusCirclePostLikeDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c campusCirclePostLikeDo) ReadDB() ICampusCirclePostLikeDo {
	return c.Clauses(dbresolver.Read)
}

func (c campusCirclePostLikeDo) WriteDB() ICampusCirclePostLikeDo {
	return c.Clauses(dbresolver.Write)
}

func (c campusCirclePostLikeDo) Session(config *gorm.Session) ICampusCirclePostLikeDo {
	return c.withDO(c.DO.Session(config))
}

func (c campusCirclePostLikeDo) Clauses(conds ...clause.Expression) ICampusCirclePostLikeDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c campusCirclePostLikeDo) Returning(value interface{}, columns ...string) ICampusCirclePostLikeDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c campusCirclePostLikeDo) Not(conds ...gen.Condition) ICampusCirclePostLikeDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c campusCirclePostLikeDo) Or(conds ...gen.Condition) ICampusCirclePostLikeDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c campusCirclePostLikeDo) Select(conds ...field.Expr) ICampusCirclePostLikeDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c campusCirclePostLikeDo) Where(conds ...gen.Condition) ICampusCirclePostLikeDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c campusCirclePostLikeDo) Order(conds ...field.Expr) ICampusCirclePostLikeDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c campusCirclePostLikeDo) Distinct(cols ...field.Expr) ICampusCirclePostLikeDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c campusCirclePostLikeDo) Omit(cols ...field.Expr) ICampusCirclePostLikeDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c campusCirclePostLikeDo) Join(table schema.Tabler, on ...field.Expr) ICampusCirclePostLikeDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c campusCirclePostLikeDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICampusCirclePostLikeDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c campusCirclePostLikeDo) RightJoin(table schema.Tabler, on ...field.Expr) ICampusCirclePostLikeDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c campusCirclePostLikeDo) Group(cols ...field.Expr) ICampusCirclePostLikeDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c campusCirclePostLikeDo) Having(conds ...gen.Condition) ICampusCirclePostLikeDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c campusCirclePostLikeDo) Limit(limit int) ICampusCirclePostLikeDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c campusCirclePostLikeDo) Offset(offset int) ICampusCirclePostLikeDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c campusCirclePostLikeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICampusCirclePostLikeDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c campusCirclePostLikeDo) Unscoped() ICampusCirclePostLikeDo {
	return c.withDO(c.DO.Unscoped())
}

func (c campusCirclePostLikeDo) Create(values ...*domain.CampusCirclePostLike) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c campusCirclePostLikeDo) CreateInBatches(values []*domain.CampusCirclePostLike, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c campusCirclePostLikeDo) Save(values ...*domain.CampusCirclePostLike) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c campusCirclePostLikeDo) First() (*domain.CampusCirclePostLike, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*domain.CampusCirclePostLike), nil
	}
}

func (c campusCirclePostLikeDo) Take() (*domain.CampusCirclePostLike, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*domain.CampusCirclePostLike), nil
	}
}

func (c campusCirclePostLikeDo) Last() (*domain.CampusCirclePostLike, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*domain.CampusCirclePostLike), nil
	}
}

func (c campusCirclePostLikeDo) Find() ([]*domain.CampusCirclePostLike, error) {
	result, err := c.DO.Find()
	return result.([]*domain.CampusCirclePostLike), err
}

func (c campusCirclePostLikeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.CampusCirclePostLike, err error) {
	buf := make([]*domain.CampusCirclePostLike, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c campusCirclePostLikeDo) FindInBatches(result *[]*domain.CampusCirclePostLike, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c campusCirclePostLikeDo) Attrs(attrs ...field.AssignExpr) ICampusCirclePostLikeDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c campusCirclePostLikeDo) Assign(attrs ...field.AssignExpr) ICampusCirclePostLikeDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c campusCirclePostLikeDo) Joins(fields ...field.RelationField) ICampusCirclePostLikeDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c campusCirclePostLikeDo) Preload(fields ...field.RelationField) ICampusCirclePostLikeDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c campusCirclePostLikeDo) FirstOrInit() (*domain.CampusCirclePostLike, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*domain.CampusCirclePostLike), nil
	}
}

func (c campusCirclePostLikeDo) FirstOrCreate() (*domain.CampusCirclePostLike, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*domain.CampusCirclePostLike), nil
	}
}

func (c campusCirclePostLikeDo) FindByPage(offset int, limit int) (result []*domain.CampusCirclePostLike, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c campusCirclePostLikeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c campusCirclePostLikeDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c campusCirclePostLikeDo) Delete(models ...*domain.CampusCirclePostLike) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *campusCirclePostLikeDo) withDO(do gen.Dao) *campusCirclePostLikeDo {
	c.DO = *do.(*gen.DO)
	return c
}
