// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/weouc-plus/campus-platform/internal/modules/campus_circle/domain"
)

func newCampusCircleSection(db *gorm.DB, opts ...gen.DOOption) campusCircleSection {
	_campusCircleSection := campusCircleSection{}

	_campusCircleSection.campusCircleSectionDo.UseDB(db, opts...)
	_campusCircleSection.campusCircleSectionDo.UseModel(&domain.CampusCircleSection{})

	tableName := _campusCircleSection.campusCircleSectionDo.TableName()
	_campusCircleSection.ALL = field.NewAsterisk(tableName)
	_campusCircleSection.ID = field.NewUint64(tableName, "id")
	_campusCircleSection.ParentId = field.NewUint64(tableName, "parent_id")
	_campusCircleSection.Slug = field.NewString(tableName, "slug")
	_campusCircleSection.Name = field.NewString(tableName, "name")
	_campusCircleSection.Description = field.NewString(tableName, "description")
	_campusCircleSection.IconUrl = field.NewString(tableName, "icon_url")
	_campusCircleSection.CoverUrl = field.NewString(tableName, "cover_url")
	_campusCircleSection.SortOrder = field.NewInt64(tableName, "sort_order")
	_campusCircleSection.Status = field.NewString(tableName, "status")
	_campusCircleSection.CreatedBy = field.NewUint64(tableName, "created_by")
	_campusCircleSection.UpdatedBy = field.NewUint64(tableName, "updated_by")
	_campusCircleSection.Version = field.NewUint64(tableName, "version")
	_campusCircleSection.CreatedAt = field.NewTime(tableName, "created_at")
	_campusCircleSection.UpdatedAt = field.NewTime(tableName, "updated_at")

	_campusCircleSection.fillFieldMap()

	return _campusCircleSection
}

type campusCircleSection struct {
	campusCircleSectionDo campusCircleSectionDo

	ALL         field.Asterisk
	ID          field.Uint64
	ParentId    field.Uint64
	Slug        field.String
	Name        field.String
	Description field.String
	IconUrl     field.String
	CoverUrl    field.String
	SortOrder   field.Int64
	Status      field.String
	CreatedBy   field.Uint64
	UpdatedBy   field.Uint64
	Version     field.Uint64
	CreatedAt   field.Time
	UpdatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (c campusCircleSection) Table(newTableName string) *campusCircleSection {
	c.campusCircleSectionDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c campusCircleSection) As(alias string) *campusCircleSection {
	c.campusCircleSectionDo.DO = *(c.campusCircleSectionDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *campusCircleSection) updateTableName(table string) *campusCircleSection {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewUint64(table, "id")
	c.ParentId = field.NewUint64(table, "parent_id")
	c.Slug = field.NewString(table, "slug")
	c.Name = field.NewString(table, "name")
	c.Description = field.NewString(table, "description")
	c.IconUrl = field.NewString(table, "icon_url")
	c.CoverUrl = field.NewString(table, "cover_url")
	c.SortOrder = field.NewInt64(table, "sort_order")
	c.Status = field.NewString(table, "status")
	c.CreatedBy = field.NewUint64(table, "created_by")
	c.UpdatedBy = field.NewUint64(table, "updated_by")
	c.Version = field.NewUint64(table, "version")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")

	c.fillFieldMap()

	return c
}

func (c *campusCircleSection) WithContext(ctx context.Context) ICampusCircleSectionDo {
	return c.campusCircleSectionDo.WithContext(ctx)
}

func (c campusCircleSection) TableName() string { return c.campusCircleSectionDo.TableName() }

func (c campusCircleSection) Alias() string { return c.campusCircleSectionDo.Alias() }

func (c campusCircleSection) Columns(cols ...field.Expr) gen.Columns {
	return c.campusCircleSectionDo.Columns(cols...)
}

func (c *campusCircleSection) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *campusCircleSection) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 14)
	c.fieldMap["id"] = c.ID
	c.fieldMap["parent_id"] = c.ParentId
	c.fieldMap["slug"] = c.Slug
	c.fieldMap["name"] = c.Name
	c.fieldMap["description"] = c.Description
	c.fieldMap["icon_url"] = c.IconUrl
	c.fieldMap["cover_url"] = c.CoverUrl
	c.fieldMap["sort_order"] = c.SortOrder
	c.fieldMap["status"] = c.Status
	c.fieldMap["created_by"] = c.CreatedBy
	c.fieldMap["updated_by"] = c.UpdatedBy
	c.fieldMap["version"] = c.Version
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
}

func (c campusCircleSection) clone(db *gorm.DB) campusCircleSection {
	c.campusCircleSectionDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c campusCircleSection) replaceDB(db *gorm.DB) campusCircleSection {
	c.campusCircleSectionDo.ReplaceDB(db)
	return c
}

type campusCircleSectionDo struct{ gen.DO }

type ICampusCircleSectionDo interface {
	gen.SubQuery
	Debug() ICampusCircleSectionDo
	WithContext(ctx context.Context) ICampusCircleSectionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICampusCircleSectionDo
	WriteDB() ICampusCircleSectionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICampusCircleSectionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICampusCircleSectionDo
	Not(conds ...gen.Condition) ICampusCircleSectionDo
	Or(conds ...gen.Condition) ICampusCircleSectionDo
	Select(conds ...field.Expr) ICampusCircleSectionDo
	Where(conds ...gen.Condition) ICampusCircleSectionDo
	Order(conds ...field.Expr) ICampusCircleSectionDo
	Distinct(cols ...field.Expr) ICampusCircleSectionDo
	Omit(cols ...field.Expr) ICampusCircleSectionDo
	Join(table schema.Tabler, on ...field.Expr) ICampusCircleSectionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICampusCircleSectionDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICampusCircleSectionDo
	Group(cols ...field.Expr) ICampusCircleSectionDo
	Having(conds ...gen.Condition) ICampusCircleSectionDo
	Limit(limit int) ICampusCircleSectionDo
	Offset(offset int) ICampusCircleSectionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICampusCircleSectionDo
	Unscoped() ICampusCircleSectionDo
	Create(values ...*domain.CampusCircleSection) error
	CreateInBatches(values []*domain.CampusCircleSection, batchSize int) error
	Save(values ...*domain.CampusCircleSection) error
	First() (*domain.CampusCircleSection, error)
	Take() (*domain.CampusCircleSection, error)
	Last() (*domain.CampusCircleSection, error)
	Find() ([]*domain.CampusCircleSection, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.CampusCircleSection, err error)
	FindInBatches(result *[]*domain.CampusCircleSection, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*domain.CampusCircleSection) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICampusCircleSectionDo
	Assign(attrs ...field.AssignExpr) ICampusCircleSectionDo
	Joins(fields ...field.RelationField) ICampusCircleSectionDo
	Preload(fields ...field.RelationField) ICampusCircleSectionDo
	FirstOrInit() (*domain.CampusCircleSection, error)
	FirstOrCreate() (*domain.CampusCircleSection, error)
	FindByPage(offset int, limit int) (result []*domain.CampusCircleSection, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICampusCircleSectionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c campusCircleSectionDo) Debug() ICampusCircleSectionDo {
	return c.withDO(c.DO.Debug())
}

func (c campusCircleSectionDo) WithContext(ctx context.Context) ICampusCircleSectionDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c campusCircleSectionDo) ReadDB() ICampusCircleSectionDo {
	return c.Clauses(dbresolver.Read)
}

func (c campusCircleSectionDo) WriteDB() ICampusCircleSectionDo {
	return c.Clauses(dbresolver.Write)
}

func (c campusCircleSectionDo) Session(config *gorm.Session) ICampusCircleSectionDo {
	return c.withDO(c.DO.Session(config))
}

func (c campusCircleSectionDo) Clauses(conds ...clause.Expression) ICampusCircleSectionDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c campusCircleSectionDo) Returning(value interface{}, columns ...string) ICampusCircleSectionDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c campusCircleSectionDo) Not(conds ...gen.Condition) ICampusCircleSectionDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c campusCircleSectionDo) Or(conds ...gen.Condition) ICampusCircleSectionDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c campusCircleSectionDo) Select(conds ...field.Expr) ICampusCircleSectionDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c campusCircleSectionDo) Where(conds ...gen.Condition) ICampusCircleSectionDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c campusCircleSectionDo) Order(conds ...field.Expr) ICampusCircleSectionDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c campusCircleSectionDo) Distinct(cols ...field.Expr) ICampusCircleSectionDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c campusCircleSectionDo) Omit(cols ...field.Expr) ICampusCircleSectionDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c campusCircleSectionDo) Join(table schema.Tabler, on ...field.Expr) ICampusCircleSectionDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c campusCircleSectionDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICampusCircleSectionDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c campusCircleSectionDo) RightJoin(table schema.Tabler, on ...field.Expr) ICampusCircleSectionDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c campusCircleSectionDo) Group(cols ...field.Expr) ICampusCircleSectionDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c campusCircleSectionDo) Having(conds ...gen.Condition) ICampusCircleSectionDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c campusCircleSectionDo) Limit(limit int) ICampusCircleSectionDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c campusCircleSectionDo) Offset(offset int) ICampusCircleSectionDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c campusCircleSectionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICampusCircleSectionDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c campusCircleSectionDo) Unscoped() ICampusCircleSectionDo {
	return c.withDO(c.DO.Unscoped())
}

func (c campusCircleSectionDo) Create(values ...*domain.CampusCircleSection) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c campusCircleSectionDo) CreateInBatches(values []*domain.CampusCircleSection, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c campusCircleSectionDo) Save(values ...*domain.CampusCircleSection) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c campusCircleSectionDo) First() (*domain.CampusCircleSection, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*domain.CampusCircleSection), nil
	}
}

func (c campusCircleSectionDo) Take() (*domain.CampusCircleSection, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*domain.CampusCircleSection), nil
	}
}

func (c campusCircleSectionDo) Last() (*domain.CampusCircleSection, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*domain.CampusCircleSection), nil
	}
}

func (c campusCircleSectionDo) Find() ([]*domain.CampusCircleSection, error) {
	result, err := c.DO.Find()
	return result.([]*domain.CampusCircleSection), err
}

func (c campusCircleSectionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.CampusCircleSection, err error) {
	buf := make([]*domain.CampusCircleSection, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c campusCircleSectionDo) FindInBatches(result *[]*domain.CampusCircleSection, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c campusCircleSectionDo) Attrs(attrs ...field.AssignExpr) ICampusCircleSectionDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c campusCircleSectionDo) Assign(attrs ...field.AssignExpr) ICampusCircleSectionDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c campusCircleSectionDo) Joins(fields ...field.RelationField) ICampusCircleSectionDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c campusCircleSectionDo) Preload(fields ...field.RelationField) ICampusCircleSectionDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c campusCircleSectionDo) FirstOrInit() (*domain.CampusCircleSection, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*domain.CampusCircleSection), nil
	}
}

func (c campusCircleSectionDo) FirstOrCreate() (*domain.CampusCircleSection, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*domain.CampusCircleSection), nil
	}
}

func (c campusCircleSectionDo) FindByPage(offset int, limit int) (result []*domain.CampusCircleSection, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c campusCircleSectionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c campusCircleSectionDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c campusCircleSectionDo) Delete(models ...*domain.CampusCircleSection) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *campusCircleSectionDo) withDO(do gen.Dao) *campusCircleSectionDo {
	c.DO = *do.(*gen.DO)
	return c
}
