// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/weouc-plus/campus-platform/internal/modules/errand/domain"
)

func newTransition(db *gorm.DB, opts ...gen.DOOption) transition {
	_transition := transition{}

	_transition.transitionDo.UseDB(db, opts...)
	_transition.transitionDo.UseModel(&domain.Transition{})

	tableName := _transition.transitionDo.TableName()
	_transition.ALL = field.NewAsterisk(tableName)
	_transition.ID = field.NewUint64(tableName, "id")
	_transition.TaskId = field.NewUint64(tableName, "task_id")
	_transition.FromStatus = field.NewString(tableName, "from_status")
	_transition.ToStatus = field.NewString(tableName, "to_status")
	_transition.ActorId = field.NewUint64(tableName, "actor_id")
	_transition.Reason = field.NewString(tableName, "reason")
	_transition.IdempotencyKey = field.NewString(tableName, "idempotency_key")
	_transition.CreatedAt = field.NewTime(tableName, "created_at")
	_transition.UpdatedAt = field.NewTime(tableName, "updated_at")

	_transition.fillFieldMap()

	return _transition
}

type transition struct {
	transitionDo transitionDo

	ALL            field.Asterisk
	ID             field.Uint64
	TaskId         field.Uint64
	FromStatus     field.String
	ToStatus       field.String
	ActorId        field.Uint64
	Reason         field.String
	IdempotencyKey field.String
	CreatedAt      field.Time
	UpdatedAt      field.Time

	fieldMap map[string]field.Expr
}

func (t transition) Table(newTableName string) *transition {
	t.transitionDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t transition) As(alias string) *transition {
	t.transitionDo.DO = *(t.transitionDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *transition) updateTableName(table string) *transition {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewUint64(table, "id")
	t.TaskId = field.NewUint64(table, "task_id")
	t.FromStatus = field.NewString(table, "from_status")
	t.ToStatus = field.NewString(table, "to_status")
	t.ActorId = field.NewUint64(table, "actor_id")
	t.Reason = field.NewString(table, "reason")
	t.IdempotencyKey = field.NewString(table, "idempotency_key")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")

	t.fillFieldMap()

	return t
}

func (t *transition) WithContext(ctx context.Context) ITransitionDo {
	return t.transitionDo.WithContext(ctx)
}

func (t transition) TableName() string { return t.transitionDo.TableName() }

func (t transition) Alias() string { return t.transitionDo.Alias() }

func (t transition) Columns(cols ...field.Expr) gen.Columns { return t.transitionDo.Columns(cols...) }

func (t *transition) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *transition) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 9)
	t.fieldMap["id"] = t.ID
	t.fieldMap["task_id"] = t.TaskId
	t.fieldMap["from_status"] = t.FromStatus
	t.fieldMap["to_status"] = t.ToStatus
	t.fieldMap["actor_id"] = t.ActorId
	t.fieldMap["reason"] = t.Reason
	t.fieldMap["idempotency_key"] = t.IdempotencyKey
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
}

func (t transition) clone(db *gorm.DB) transition {
	t.transitionDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t transition) replaceDB(db *gorm.DB) transition {
	t.transitionDo.ReplaceDB(db)
	return t
}

type transitionDo struct{ gen.DO }

type ITransitionDo interface {
	gen.SubQuery
	Debug() ITransitionDo
	WithContext(ctx context.Context) ITransitionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITransitionDo
	WriteDB() ITransitionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITransitionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITransitionDo
	Not(conds ...gen.Condition) ITransitionDo
	Or(conds ...gen.Condition) ITransitionDo
	Select(conds ...field.Expr) ITransitionDo
	Where(conds ...gen.Condition) ITransitionDo
	Order(conds ...field.Expr) ITransitionDo
	Distinct(cols ...field.Expr) ITransitionDo
	Omit(cols ...field.Expr) ITransitionDo
	Join(table schema.Tabler, on ...field.Expr) ITransitionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITransitionDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITransitionDo
	Group(cols ...field.Expr) ITransitionDo
	Having(conds ...gen.Condition) ITransitionDo
	Limit(limit int) ITransitionDo
	Offset(offset int) ITransitionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITransitionDo
	Unscoped() ITransitionDo
	Create(values ...*domain.Transition) error
	CreateInBatches(values []*domain.Transition, batchSize int) error
	Save(values ...*domain.Transition) error
	First() (*domain.Transition, error)
	Take() (*domain.Transition, error)
	Last() (*domain.Transition, error)
	Find() ([]*domain.Transition, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.Transition, err error)
	FindInBatches(result *[]*domain.Transition, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*domain.Transition) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITransitionDo
	Assign(attrs ...field.AssignExpr) ITransitionDo
	Joins(fields ...field.RelationField) ITransitionDo
	Preload(fields ...field.RelationField) ITransitionDo
	FirstOrInit() (*domain.Transition, error)
	FirstOrCreate() (*domain.Transition, error)
	FindByPage(offset int, limit int) (result []*domain.Transition, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITransitionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t transitionDo) Debug() ITransitionDo {
	return t.withDO(t.DO.Debug())
}

func (t transitionDo) WithContext(ctx context.Context) ITransitionDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t transitionDo) ReadDB() ITransitionDo {
	return t.Clauses(dbresolver.Read)
}

func (t transitionDo) WriteDB() ITransitionDo {
	return t.Clauses(dbresolver.Write)
}

func (t transitionDo) Session(config *gorm.Session) ITransitionDo {
	return t.withDO(t.DO.Session(config))
}

func (t transitionDo) Clauses(conds ...clause.Expression) ITransitionDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t transitionDo) Returning(value interface{}, columns ...string) ITransitionDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t transitionDo) Not(conds ...gen.Condition) ITransitionDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t transitionDo) Or(conds ...gen.Condition) ITransitionDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t transitionDo) Select(conds ...field.Expr) ITransitionDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t transitionDo) Where(conds ...gen.Condition) ITransitionDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t transitionDo) Order(conds ...field.Expr) ITransitionDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t transitionDo) Distinct(cols ...field.Expr) ITransitionDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t transitionDo) Omit(cols ...field.Expr) ITransitionDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t transitionDo) Join(table schema.Tabler, on ...field.Expr) ITransitionDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t transitionDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITransitionDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t transitionDo) RightJoin(table schema.Tabler, on ...field.Expr) ITransitionDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t transitionDo) Group(cols ...field.Expr) ITransitionDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t transitionDo) Having(conds ...gen.Condition) ITransitionDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t transitionDo) Limit(limit int) ITransitionDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t transitionDo) Offset(offset int) ITransitionDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t transitionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITransitionDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t transitionDo) Unscoped() ITransitionDo {
	return t.withDO(t.DO.Unscoped())
}

func (t transitionDo) Create(values ...*domain.Transition) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t transitionDo) CreateInBatches(values []*domain.Transition, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t transitionDo) Save(values ...*domain.Transition) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t transitionDo) First() (*domain.Transition, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*domain.Transition), nil
	}
}

func (t transitionDo) Take() (*domain.Transition, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*domain.Transition), nil
	}
}

func (t transitionDo) Last() (*domain.Transition, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*domain.Transition), nil
	}
}

func (t transitionDo) Find() ([]*domain.Transition, error) {
	result, err := t.DO.Find()
	return result.([]*domain.Transition), err
}

func (t transitionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.Transition, err error) {
	buf := make([]*domain.Transition, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t transitionDo) FindInBatches(result *[]*domain.Transition, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t transitionDo) Attrs(attrs ...field.AssignExpr) ITransitionDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t transitionDo) Assign(attrs ...field.AssignExpr) ITransitionDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t transitionDo) Joins(fields ...field.RelationField) ITransitionDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t transitionDo) Preload(fields ...field.RelationField) ITransitionDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t transitionDo) FirstOrInit() (*domain.Transition, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*domain.Transition), nil
	}
}

func (t transitionDo) FirstOrCreate() (*domain.Transition, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*domain.Transition), nil
	}
}

func (t transitionDo) FindByPage(offset int, limit int) (result []*domain.Transition, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t transitionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t transitionDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t transitionDo) Delete(models ...*domain.Transition) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *transitionDo) withDO(do gen.Dao) *transitionDo {
	t.DO = *do.(*gen.DO)
	return t
}
