// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/weouc-plus/campus-platform/internal/modules/errand/domain"
)

func newTask(db *gorm.DB, opts ...gen.DOOption) task {
	_task := task{}

	_task.taskDo.UseDB(db, opts...)
	_task.taskDo.UseModel(&domain.Task{})

	tableName := _task.taskDo.TableName()
	_task.ALL = field.NewAsterisk(tableName)
	_task.ID = field.NewUint64(tableName, "id")
	_task.Title = field.NewString(tableName, "title")
	_task.Description = field.NewString(tableName, "description")
	_task.RewardCents = field.NewInt64(tableName, "reward_cents")
	_task.Currency = field.NewString(tableName, "currency")
	_task.PickupLocation = field.NewString(tableName, "pickup_location")
	_task.DropoffLocation = field.NewString(tableName, "dropoff_location")
	_task.Deadline = field.NewTime(tableName, "deadline")
	_task.Status = field.NewString(tableName, "status")
	_task.ReviewStatus = field.NewString(tableName, "review_status")
	_task.ReviewReason = field.NewString(tableName, "review_reason")
	_task.ReviewedBy = field.NewUint64(tableName, "reviewed_by")
	_task.ReviewedAt = field.NewTime(tableName, "reviewed_at")
	_task.RequesterId = field.NewUint64(tableName, "requester_id")
	_task.ContactType = field.NewString(tableName, "contact_type")
	_task.ContactCiphertext = field.NewString(tableName, "contact_ciphertext")
	_task.RunnerId = field.NewUint64(tableName, "runner_id")
	_task.TradeOrderId = field.NewUint64(tableName, "trade_order_id")
	_task.AcceptedAt = field.NewTime(tableName, "accepted_at")
	_task.PickedUpAt = field.NewTime(tableName, "picked_up_at")
	_task.DeliveredAt = field.NewTime(tableName, "delivered_at")
	_task.CompletedAt = field.NewTime(tableName, "completed_at")
	_task.CancelledAt = field.NewTime(tableName, "cancelled_at")
	_task.Version = field.NewUint64(tableName, "version")
	_task.CreatedAt = field.NewTime(tableName, "created_at")
	_task.UpdatedAt = field.NewTime(tableName, "updated_at")

	_task.fillFieldMap()

	return _task
}

type task struct {
	taskDo taskDo

	ALL               field.Asterisk
	ID                field.Uint64
	Title             field.String
	Description       field.String
	RewardCents       field.Int64
	Currency          field.String
	PickupLocation    field.String
	DropoffLocation   field.String
	Deadline          field.Time
	Status            field.String
	ReviewStatus      field.String
	ReviewReason      field.String
	ReviewedBy        field.Uint64
	ReviewedAt        field.Time
	RequesterId       field.Uint64
	ContactType       field.String
	ContactCiphertext field.String
	RunnerId          field.Uint64
	TradeOrderId      field.Uint64
	AcceptedAt        field.Time
	PickedUpAt        field.Time
	DeliveredAt       field.Time
	CompletedAt       field.Time
	CancelledAt       field.Time
	Version           field.Uint64
	CreatedAt         field.Time
	UpdatedAt         field.Time

	fieldMap map[string]field.Expr
}

func (t task) Table(newTableName string) *task {
	t.taskDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t task) As(alias string) *task {
	t.taskDo.DO = *(t.taskDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *task) updateTableName(table string) *task {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewUint64(table, "id")
	t.Title = field.NewString(table, "title")
	t.Description = field.NewString(table, "description")
	t.RewardCents = field.NewInt64(table, "reward_cents")
	t.Currency = field.NewString(table, "currency")
	t.PickupLocation = field.NewString(table, "pickup_location")
	t.DropoffLocation = field.NewString(table, "dropoff_location")
	t.Deadline = field.NewTime(table, "deadline")
	t.Status = field.NewString(table, "status")
	t.ReviewStatus = field.NewString(table, "review_status")
	t.ReviewReason = field.NewString(table, "review_reason")
	t.ReviewedBy = field.NewUint64(table, "reviewed_by")
	t.ReviewedAt = field.NewTime(table, "reviewed_at")
	t.RequesterId = field.NewUint64(table, "requester_id")
	t.ContactType = field.NewString(table, "contact_type")
	t.ContactCiphertext = field.NewString(table, "contact_ciphertext")
	t.RunnerId = field.NewUint64(table, "runner_id")
	t.TradeOrderId = field.NewUint64(table, "trade_order_id")
	t.AcceptedAt = field.NewTime(table, "accepted_at")
	t.PickedUpAt = field.NewTime(table, "picked_up_at")
	t.DeliveredAt = field.NewTime(table, "delivered_at")
	t.CompletedAt = field.NewTime(table, "completed_at")
	t.CancelledAt = field.NewTime(table, "cancelled_at")
	t.Version = field.NewUint64(table, "version")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")

	t.fillFieldMap()

	return t
}

func (t *task) WithContext(ctx context.Context) ITaskDo { return t.taskDo.WithContext(ctx) }

func (t task) TableName() string { return t.taskDo.TableName() }

func (t task) Alias() string { return t.taskDo.Alias() }

func (t task) Columns(cols ...field.Expr) gen.Columns { return t.taskDo.Columns(cols...) }

func (t *task) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *task) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 26)
	t.fieldMap["id"] = t.ID
	t.fieldMap["title"] = t.Title
	t.fieldMap["description"] = t.Description
	t.fieldMap["reward_cents"] = t.RewardCents
	t.fieldMap["currency"] = t.Currency
	t.fieldMap["pickup_location"] = t.PickupLocation
	t.fieldMap["dropoff_location"] = t.DropoffLocation
	t.fieldMap["deadline"] = t.Deadline
	t.fieldMap["status"] = t.Status
	t.fieldMap["review_status"] = t.ReviewStatus
	t.fieldMap["review_reason"] = t.ReviewReason
	t.fieldMap["reviewed_by"] = t.ReviewedBy
	t.fieldMap["reviewed_at"] = t.ReviewedAt
	t.fieldMap["requester_id"] = t.RequesterId
	t.fieldMap["contact_type"] = t.ContactType
	t.fieldMap["contact_ciphertext"] = t.ContactCiphertext
	t.fieldMap["runner_id"] = t.RunnerId
	t.fieldMap["trade_order_id"] = t.TradeOrderId
	t.fieldMap["accepted_at"] = t.AcceptedAt
	t.fieldMap["picked_up_at"] = t.PickedUpAt
	t.fieldMap["delivered_at"] = t.DeliveredAt
	t.fieldMap["completed_at"] = t.CompletedAt
	t.fieldMap["cancelled_at"] = t.CancelledAt
	t.fieldMap["version"] = t.Version
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
}

func (t task) clone(db *gorm.DB) task {
	t.taskDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t task) replaceDB(db *gorm.DB) task {
	t.taskDo.ReplaceDB(db)
	return t
}

type taskDo struct{ gen.DO }

type ITaskDo interface {
	gen.SubQuery
	Debug() ITaskDo
	WithContext(ctx context.Context) ITaskDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITaskDo
	WriteDB() ITaskDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITaskDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITaskDo
	Not(conds ...gen.Condition) ITaskDo
	Or(conds ...gen.Condition) ITaskDo
	Select(conds ...field.Expr) ITaskDo
	Where(conds ...gen.Condition) ITaskDo
	Order(conds ...field.Expr) ITaskDo
	Distinct(cols ...field.Expr) ITaskDo
	Omit(cols ...field.Expr) ITaskDo
	Join(table schema.Tabler, on ...field.Expr) ITaskDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITaskDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITaskDo
	Group(cols ...field.Expr) ITaskDo
	Having(conds ...gen.Condition) ITaskDo
	Limit(limit int) ITaskDo
	Offset(offset int) ITaskDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITaskDo
	Unscoped() ITaskDo
	Create(values ...*domain.Task) error
	CreateInBatches(values []*domain.Task, batchSize int) error
	Save(values ...*domain.Task) error
	First() (*domain.Task, error)
	Take() (*domain.Task, error)
	Last() (*domain.Task, error)
	Find() ([]*domain.Task, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.Task, err error)
	FindInBatches(result *[]*domain.Task, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*domain.Task) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITaskDo
	Assign(attrs ...field.AssignExpr) ITaskDo
	Joins(fields ...field.RelationField) ITaskDo
	Preload(fields ...field.RelationField) ITaskDo
	FirstOrInit() (*domain.Task, error)
	FirstOrCreate() (*domain.Task, error)
	FindByPage(offset int, limit int) (result []*domain.Task, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITaskDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t taskDo) Debug() ITaskDo {
	return t.withDO(t.DO.Debug())
}

func (t taskDo) WithContext(ctx context.Context) ITaskDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t taskDo) ReadDB() ITaskDo {
	return t.Clauses(dbresolver.Read)
}

func (t taskDo) WriteDB() ITaskDo {
	return t.Clauses(dbresolver.Write)
}

func (t taskDo) Session(config *gorm.Session) ITaskDo {
	return t.withDO(t.DO.Session(config))
}

func (t taskDo) Clauses(conds ...clause.Expression) ITaskDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t taskDo) Returning(value interface{}, columns ...string) ITaskDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t taskDo) Not(conds ...gen.Condition) ITaskDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t taskDo) Or(conds ...gen.Condition) ITaskDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t taskDo) Select(conds ...field.Expr) ITaskDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t taskDo) Where(conds ...gen.Condition) ITaskDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t taskDo) Order(conds ...field.Expr) ITaskDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t taskDo) Distinct(cols ...field.Expr) ITaskDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t taskDo) Omit(cols ...field.Expr) ITaskDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t taskDo) Join(table schema.Tabler, on ...field.Expr) ITaskDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t taskDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITaskDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t taskDo) RightJoin(table schema.Tabler, on ...field.Expr) ITaskDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t taskDo) Group(cols ...field.Expr) ITaskDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t taskDo) Having(conds ...gen.Condition) ITaskDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t taskDo) Limit(limit int) ITaskDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t taskDo) Offset(offset int) ITaskDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t taskDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITaskDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t taskDo) Unscoped() ITaskDo {
	return t.withDO(t.DO.Unscoped())
}

func (t taskDo) Create(values ...*domain.Task) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t taskDo) CreateInBatches(values []*domain.Task, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t taskDo) Save(values ...*domain.Task) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t taskDo) First() (*domain.Task, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*domain.Task), nil
	}
}

func (t taskDo) Take() (*domain.Task, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*domain.Task), nil
	}
}

func (t taskDo) Last() (*domain.Task, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*domain.Task), nil
	}
}

func (t taskDo) Find() ([]*domain.Task, error) {
	result, err := t.DO.Find()
	return result.([]*domain.Task), err
}

func (t taskDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.Task, err error) {
	buf := make([]*domain.Task, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t taskDo) FindInBatches(result *[]*domain.Task, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t taskDo) Attrs(attrs ...field.AssignExpr) ITaskDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t taskDo) Assign(attrs ...field.AssignExpr) ITaskDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t taskDo) Joins(fields ...field.RelationField) ITaskDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t taskDo) Preload(fields ...field.RelationField) ITaskDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t taskDo) FirstOrInit() (*domain.Task, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*domain.Task), nil
	}
}

func (t taskDo) FirstOrCreate() (*domain.Task, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*domain.Task), nil
	}
}

func (t taskDo) FindByPage(offset int, limit int) (result []*domain.Task, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t taskDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t taskDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t taskDo) Delete(models ...*domain.Task) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *taskDo) withDO(do gen.Dao) *taskDo {
	t.DO = *do.(*gen.DO)
	return t
}
