// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/weouc-plus/campus-platform/internal/modules/marketplace/domain"
)

func newListing(db *gorm.DB, opts ...gen.DOOption) listing {
	_listing := listing{}

	_listing.listingDo.UseDB(db, opts...)
	_listing.listingDo.UseModel(&domain.Listing{})

	tableName := _listing.listingDo.TableName()
	_listing.ALL = field.NewAsterisk(tableName)
	_listing.ID = field.NewUint64(tableName, "id")
	_listing.Title = field.NewString(tableName, "title")
	_listing.Description = field.NewString(tableName, "description")
	_listing.PriceCents = field.NewInt64(tableName, "price_cents")
	_listing.Currency = field.NewString(tableName, "currency")
	_listing.Status = field.NewString(tableName, "status")
	_listing.RejectionReason = field.NewString(tableName, "rejection_reason")
	_listing.OwnerId = field.NewUint64(tableName, "owner_id")
	_listing.ContactType = field.NewString(tableName, "contact_type")
	_listing.ContactCiphertext = field.NewString(tableName, "contact_ciphertext")
	_listing.ReviewedBy = field.NewUint64(tableName, "reviewed_by")
	_listing.ReviewedAt = field.NewTime(tableName, "reviewed_at")
	_listing.Version = field.NewUint64(tableName, "version")
	_listing.CreatedAt = field.NewTime(tableName, "created_at")
	_listing.UpdatedAt = field.NewTime(tableName, "updated_at")

	_listing.fillFieldMap()

	return _listing
}

type listing struct {
	listingDo listingDo

	ALL               field.Asterisk
	ID                field.Uint64
	Title             field.String
	Description       field.String
	PriceCents        field.Int64
	Currency          field.String
	Status            field.String
	RejectionReason   field.String
	OwnerId           field.Uint64
	ContactType       field.String
	ContactCiphertext field.String
	ReviewedBy        field.Uint64
	ReviewedAt        field.Time
	Version           field.Uint64
	CreatedAt         field.Time
	UpdatedAt         field.Time

	fieldMap map[string]field.Expr
}

func (l listing) Table(newTableName string) *listing {
	l.listingDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l listing) As(alias string) *listing {
	l.listingDo.DO = *(l.listingDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *listing) updateTableName(table string) *listing {
	l.ALL = field.NewAsterisk(table)
	l.ID = field.NewUint64(table, "id")
	l.Title = field.NewString(table, "title")
	l.Description = field.NewString(table, "description")
	l.PriceCents = field.NewInt64(table, "price_cents")
	l.Currency = field.NewString(table, "currency")
	l.Status = field.NewString(table, "status")
	l.RejectionReason = field.NewString(table, "rejection_reason")
	l.OwnerId = field.NewUint64(table, "owner_id")
	l.ContactType = field.NewString(table, "contact_type")
	l.ContactCiphertext = field.NewString(table, "contact_ciphertext")
	l.ReviewedBy = field.NewUint64(table, "reviewed_by")
	l.ReviewedAt = field.NewTime(table, "reviewed_at")
	l.Version = field.NewUint64(table, "version")
	l.CreatedAt = field.NewTime(table, "created_at")
	l.UpdatedAt = field.NewTime(table, "updated_at")

	l.fillFieldMap()

	return l
}

func (l *listing) WithContext(ctx context.Context) IListingDo { return l.listingDo.WithContext(ctx) }

func (l listing) TableName() string { return l.listingDo.TableName() }

func (l listing) Alias() string { return l.listingDo.Alias() }

func (l listing) Columns(cols ...field.Expr) gen.Columns { return l.listingDo.Columns(cols...) }

func (l *listing) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *listing) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 15)
	l.fieldMap["id"] = l.ID
	l.fieldMap["title"] = l.Title
	l.fieldMap["description"] = l.Description
	l.fieldMap["price_cents"] = l.PriceCents
	l.fieldMap["currency"] = l.Currency
	l.fieldMap["status"] = l.Status
	l.fieldMap["rejection_reason"] = l.RejectionReason
	l.fieldMap["owner_id"] = l.OwnerId
	l.fieldMap["contact_type"] = l.ContactType
	l.fieldMap["contact_ciphertext"] = l.ContactCiphertext
	l.fieldMap["reviewed_by"] = l.ReviewedBy
	l.fieldMap["reviewed_at"] = l.ReviewedAt
	l.fieldMap["version"] = l.Version
	l.fieldMap["created_at"] = l.CreatedAt
	l.fieldMap["updated_at"] = l.UpdatedAt
}

func (l listing) clone(db *gorm.DB) listing {
	l.listingDo.ReplaceConnPool(db.Statement.ConnPool)
	return l
}

func (l listing) replaceDB(db *gorm.DB) listing {
	l.listingDo.ReplaceDB(db)
	return l
}

type listingDo struct{ gen.DO }

type IListingDo interface {
	gen.SubQuery
	Debug() IListingDo
	WithContext(ctx context.Context) IListingDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IListingDo
	WriteDB() IListingDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IListingDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IListingDo
	Not(conds ...gen.Condition) IListingDo
	Or(conds ...gen.Condition) IListingDo
	Select(conds ...field.Expr) IListingDo
	Where(conds ...gen.Condition) IListingDo
	Order(conds ...field.Expr) IListingDo
	Distinct(cols ...field.Expr) IListingDo
	Omit(cols ...field.Expr) IListingDo
	Join(table schema.Tabler, on ...field.Expr) IListingDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IListingDo
	RightJoin(table schema.Tabler, on ...field.Expr) IListingDo
	Group(cols ...field.Expr) IListingDo
	Having(conds ...gen.Condition) IListingDo
	Limit(limit int) IListingDo
	Offset(offset int) IListingDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IListingDo
	Unscoped() IListingDo
	Create(values ...*domain.Listing) error
	CreateInBatches(values []*domain.Listing, batchSize int) error
	Save(values ...*domain.Listing) error
	First() (*domain.Listing, error)
	Take() (*domain.Listing, error)
	Last() (*domain.Listing, error)
	Find() ([]*domain.Listing, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.Listing, err error)
	FindInBatches(result *[]*domain.Listing, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*domain.Listing) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IListingDo
	Assign(attrs ...field.AssignExpr) IListingDo
	Joins(fields ...field.RelationField) IListingDo
	Preload(fields ...field.RelationField) IListingDo
	FirstOrInit() (*domain.Listing, error)
	FirstOrCreate() (*domain.Listing, error)
	FindByPage(offset int, limit int) (result []*domain.Listing, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IListingDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (l listingDo) Debug() IListingDo {
	return l.withDO(l.DO.Debug())
}

func (l listingDo) WithContext(ctx context.Context) IListingDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l listingDo) ReadDB() IListingDo {
	return l.Clauses(dbresolver.Read)
}

func (l listingDo) WriteDB() IListingDo {
	return l.Clauses(dbresolver.Write)
}

func (l listingDo) Session(config *gorm.Session) IListingDo {
	return l.withDO(l.DO.Session(config))
}

func (l listingDo) Clauses(conds ...clause.Expression) IListingDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l listingDo) Returning(value interface{}, columns ...string) IListingDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l listingDo) Not(conds ...gen.Condition) IListingDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l listingDo) Or(conds ...gen.Condition) IListingDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l listingDo) Select(conds ...field.Expr) IListingDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l listingDo) Where(conds ...gen.Condition) IListingDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l listingDo) Order(conds ...field.Expr) IListingDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l listingDo) Distinct(cols ...field.Expr) IListingDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l listingDo) Omit(cols ...field.Expr) IListingDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l listingDo) Join(table schema.Tabler, on ...field.Expr) IListingDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l listingDo) LeftJoin(table schema.Tabler, on ...field.Expr) IListingDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l listingDo) RightJoin(table schema.Tabler, on ...field.Expr) IListingDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l listingDo) Group(cols ...field.Expr) IListingDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l listingDo) Having(conds ...gen.Condition) IListingDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l listingDo) Limit(limit int) IListingDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l listingDo) Offset(offset int) IListingDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l listingDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IListingDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l listingDo) Unscoped() IListingDo {
	return l.withDO(l.DO.Unscoped())
}

func (l listingDo) Create(values ...*domain.Listing) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l listingDo) CreateInBatches(values []*domain.Listing, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l listingDo) Save(values ...*domain.Listing) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l listingDo) First() (*domain.Listing, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*domain.Listing), nil
	}
}

func (l listingDo) Take() (*domain.Listing, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*domain.Listing), nil
	}
}

func (l listingDo) Last() (*domain.Listing, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*domain.Listing), nil
	}
}

func (l listingDo) Find() ([]*domain.Listing, error) {
	result, err := l.DO.Find()
	return result.([]*domain.Listing), err
}

func (l listingDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.Listing, err error) {
	buf := make([]*domain.Listing, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l listingDo) FindInBatches(result *[]*domain.Listing, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l listingDo) Attrs(attrs ...field.AssignExpr) IListingDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l listingDo) Assign(attrs ...field.AssignExpr) IListingDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l listingDo) Joins(fields ...field.RelationField) IListingDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l listingDo) Preload(fields ...field.RelationField) IListingDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l listingDo) FirstOrInit() (*domain.Listing, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*domain.Listing), nil
	}
}

func (l listingDo) FirstOrCreate() (*domain.Listing, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*domain.Listing), nil
	}
}

func (l listingDo) FindByPage(offset int, limit int) (result []*domain.Listing, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l listingDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l listingDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l listingDo) Delete(models ...*domain.Listing) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *listingDo) withDO(do gen.Dao) *listingDo {
	l.DO = *do.(*gen.DO)
	return l
}
