// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/weouc-plus/campus-platform/internal/modules/marketplace/domain"
)

func newListingImage(db *gorm.DB, opts ...gen.DOOption) listingImage {
	_listingImage := listingImage{}

	_listingImage.listingImageDo.UseDB(db, opts...)
	_listingImage.listingImageDo.UseModel(&domain.ListingImage{})

	tableName := _listingImage.listingImageDo.TableName()
	_listingImage.ALL = field.NewAsterisk(tableName)
	_listingImage.ID = field.NewUint64(tableName, "id")
	_listingImage.ListingId = field.NewUint64(tableName, "listing_id")
	_listingImage.Url = field.NewString(tableName, "url")
	_listingImage.Position = field.NewInt64(tableName, "position")
	_listingImage.CreatedAt = field.NewTime(tableName, "created_at")
	_listingImage.UpdatedAt = field.NewTime(tableName, "updated_at")

	_listingImage.fillFieldMap()

	return _listingImage
}

type listingImage struct {
	listingImageDo listingImageDo

	ALL       field.Asterisk
	ID        field.Uint64
	ListingId field.Uint64
	Url       field.String
	Position  field.Int64
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (l listingImage) Table(newTableName string) *listingImage {
	l.listingImageDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l listingImage) As(alias string) *listingImage {
	l.listingImageDo.DO = *(l.listingImageDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *listingImage) updateTableName(table string) *listingImage {
	l.ALL = field.NewAsterisk(table)
	l.ID = field.NewUint64(table, "id")
	l.ListingId = field.NewUint64(table, "listing_id")
	l.Url = field.NewString(table, "url")
	l.Position = field.NewInt64(table, "position")
	l.CreatedAt = field.NewTime(table, "created_at")
	l.UpdatedAt = field.NewTime(table, "updated_at")

	l.fillFieldMap()

	return l
}

func (l *listingImage) WithContext(ctx context.Context) IListingImageDo {
	return l.listingImageDo.WithContext(ctx)
}

func (l listingImage) TableName() string { return l.listingImageDo.TableName() }

func (l listingImage) Alias() string { return l.listingImageDo.Alias() }

func (l listingImage) Columns(cols ...field.Expr) gen.Columns {
	return l.listingImageDo.Columns(cols...)
}

func (l *listingImage) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *listingImage) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 6)
	l.fieldMap["id"] = l.ID
	l.fieldMap["listing_id"] = l.ListingId
	l.fieldMap["url"] = l.Url
	l.fieldMap["position"] = l.Position
	l.fieldMap["created_at"] = l.CreatedAt
	l.fieldMap["updated_at"] = l.UpdatedAt
}

func (l listingImage) clone(db *gorm.DB) listingImage {
	l.listingImageDo.ReplaceConnPool(db.Statement.ConnPool)
	return l
}

func (l listingImage) replaceDB(db *gorm.DB) listingImage {
	l.listingImageDo.ReplaceDB(db)
	return l
}

type listingImageDo struct{ gen.DO }

type IListingImageDo interface {
	gen.SubQuery
	Debug() IListingImageDo
	WithContext(ctx context.Context) IListingImageDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IListingImageDo
	WriteDB() IListingImageDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IListingImageDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IListingImageDo
	Not(conds ...gen.Condition) IListingImageDo
	Or(conds ...gen.Condition) IListingImageDo
	Select(conds ...field.Expr) IListingImageDo
	Where(conds ...gen.Condition) IListingImageDo
	Order(conds ...field.Expr) IListingImageDo
	Distinct(cols ...field.Expr) IListingImageDo
	Omit(cols ...field.Expr) IListingImageDo
	Join(table schema.Tabler, on ...field.Expr) IListingImageDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IListingImageDo
	RightJoin(table schema.Tabler, on ...field.Expr) IListingImageDo
	Group(cols ...field.Expr) IListingImageDo
	Having(conds ...gen.Condition) IListingImageDo
	Limit(limit int) IListingImageDo
	Offset(offset int) IListingImageDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IListingImageDo
	Unscoped() IListingImageDo
	Create(values ...*domain.ListingImage) error
	CreateInBatches(values []*domain.ListingImage, batchSize int) error
	Save(values ...*domain.ListingImage) error
	First() (*domain.ListingImage, error)
	Take() (*domain.ListingImage, error)
	Last() (*domain.ListingImage, error)
	Find() ([]*domain.ListingImage, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.ListingImage, err error)
	FindInBatches(result *[]*domain.ListingImage, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*domain.ListingImage) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IListingImageDo
	Assign(attrs ...field.AssignExpr) IListingImageDo
	Joins(fields ...field.RelationField) IListingImageDo
	Preload(fields ...field.RelationField) IListingImageDo
	FirstOrInit() (*domain.ListingImage, error)
	FirstOrCreate() (*domain.ListingImage, error)
	FindByPage(offset int, limit int) (result []*domain.ListingImage, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IListingImageDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (l listingImageDo) Debug() IListingImageDo {
	return l.withDO(l.DO.Debug())
}

func (l listingImageDo) WithContext(ctx context.Context) IListingImageDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l listingImageDo) ReadDB() IListingImageDo {
	return l.Clauses(dbresolver.Read)
}

func (l listingImageDo) WriteDB() IListingImageDo {
	return l.Clauses(dbresolver.Write)
}

func (l listingImageDo) Session(config *gorm.Session) IListingImageDo {
	return l.withDO(l.DO.Session(config))
}

func (l listingImageDo) Clauses(conds ...clause.Expression) IListingImageDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l listingImageDo) Returning(value interface{}, columns ...string) IListingImageDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l listingImageDo) Not(conds ...gen.Condition) IListingImageDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l listingImageDo) Or(conds ...gen.Condition) IListingImageDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l listingImageDo) Select(conds ...field.Expr) IListingImageDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l listingImageDo) Where(conds ...gen.Condition) IListingImageDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l listingImageDo) Order(conds ...field.Expr) IListingImageDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l listingImageDo) Distinct(cols ...field.Expr) IListingImageDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l listingImageDo) Omit(cols ...field.Expr) IListingImageDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l listingImageDo) Join(table schema.Tabler, on ...field.Expr) IListingImageDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l listingImageDo) LeftJoin(table schema.Tabler, on ...field.Expr) IListingImageDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l listingImageDo) RightJoin(table schema.Tabler, on ...field.Expr) IListingImageDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l listingImageDo) Group(cols ...field.Expr) IListingImageDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l listingImageDo) Having(conds ...gen.Condition) IListingImageDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l listingImageDo) Limit(limit int) IListingImageDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l listingImageDo) Offset(offset int) IListingImageDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l listingImageDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IListingImageDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l listingImageDo) Unscoped() IListingImageDo {
	return l.withDO(l.DO.Unscoped())
}

func (l listingImageDo) Create(values ...*domain.ListingImage) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l listingImageDo) CreateInBatches(values []*domain.ListingImage, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l listingImageDo) Save(values ...*domain.ListingImage) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l listingImageDo) First() (*domain.ListingImage, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*domain.ListingImage), nil
	}
}

func (l listingImageDo) Take() (*domain.ListingImage, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*domain.ListingImage), nil
	}
}

func (l listingImageDo) Last() (*domain.ListingImage, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*domain.ListingImage), nil
	}
}

func (l listingImageDo) Find() ([]*domain.ListingImage, error) {
	result, err := l.DO.Find()
	return result.([]*domain.ListingImage), err
}

func (l listingImageDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.ListingImage, err error) {
	buf := make([]*domain.ListingImage, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l listingImageDo) FindInBatches(result *[]*domain.ListingImage, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l listingImageDo) Attrs(attrs ...field.AssignExpr) IListingImageDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l listingImageDo) Assign(attrs ...field.AssignExpr) IListingImageDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l listingImageDo) Joins(fields ...field.RelationField) IListingImageDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l listingImageDo) Preload(fields ...field.RelationField) IListingImageDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l listingImageDo) FirstOrInit() (*domain.ListingImage, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*domain.ListingImage), nil
	}
}

func (l listingImageDo) FirstOrCreate() (*domain.ListingImage, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*domain.ListingImage), nil
	}
}

func (l listingImageDo) FindByPage(offset int, limit int) (result []*domain.ListingImage, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l listingImageDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l listingImageDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l listingImageDo) Delete(models ...*domain.ListingImage) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *listingImageDo) withDO(do gen.Dao) *listingImageDo {
	l.DO = *do.(*gen.DO)
	return l
}
