// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/weouc-plus/campus-platform/internal/modules/marketplace/domain"
)

func newMarketplaceReservation(db *gorm.DB, opts ...gen.DOOption) marketplaceReservation {
	_marketplaceReservation := marketplaceReservation{}

	_marketplaceReservation.marketplaceReservationDo.UseDB(db, opts...)
	_marketplaceReservation.marketplaceReservationDo.UseModel(&domain.MarketplaceReservation{})

	tableName := _marketplaceReservation.marketplaceReservationDo.TableName()
	_marketplaceReservation.ALL = field.NewAsterisk(tableName)
	_marketplaceReservation.ID = field.NewUint64(tableName, "id")
	_marketplaceReservation.ListingId = field.NewUint64(tableName, "listing_id")
	_marketplaceReservation.TradeOrderId = field.NewUint64(tableName, "trade_order_id")
	_marketplaceReservation.BuyerId = field.NewUint64(tableName, "buyer_id")
	_marketplaceReservation.Status = field.NewString(tableName, "status")
	_marketplaceReservation.ExpiresAt = field.NewTime(tableName, "expires_at")
	_marketplaceReservation.Version = field.NewUint64(tableName, "version")
	_marketplaceReservation.CreatedAt = field.NewTime(tableName, "created_at")
	_marketplaceReservation.UpdatedAt = field.NewTime(tableName, "updated_at")

	_marketplaceReservation.fillFieldMap()

	return _marketplaceReservation
}

type marketplaceReservation struct {
	marketplaceReservationDo marketplaceReservationDo

	ALL          field.Asterisk
	ID           field.Uint64
	ListingId    field.Uint64
	TradeOrderId field.Uint64
	BuyerId      field.Uint64
	Status       field.String
	ExpiresAt    field.Time
	Version      field.Uint64
	CreatedAt    field.Time
	UpdatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (m marketplaceReservation) Table(newTableName string) *marketplaceReservation {
	m.marketplaceReservationDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m marketplaceReservation) As(alias string) *marketplaceReservation {
	m.marketplaceReservationDo.DO = *(m.marketplaceReservationDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *marketplaceReservation) updateTableName(table string) *marketplaceReservation {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewUint64(table, "id")
	m.ListingId = field.NewUint64(table, "listing_id")
	m.TradeOrderId = field.NewUint64(table, "trade_order_id")
	m.BuyerId = field.NewUint64(table, "buyer_id")
	m.Status = field.NewString(table, "status")
	m.ExpiresAt = field.NewTime(table, "expires_at")
	m.Version = field.NewUint64(table, "version")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")

	m.fillFieldMap()

	return m
}

func (m *marketplaceReservation) WithContext(ctx context.Context) IMarketplaceReservationDo {
	return m.marketplaceReservationDo.WithContext(ctx)
}

func (m marketplaceReservation) TableName() string { return m.marketplaceReservationDo.TableName() }

func (m marketplaceReservation) Alias() string { return m.marketplaceReservationDo.Alias() }

func (m marketplaceReservation) Columns(cols ...field.Expr) gen.Columns {
	return m.marketplaceReservationDo.Columns(cols...)
}

func (m *marketplaceReservation) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *marketplaceReservation) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 9)
	m.fieldMap["id"] = m.ID
	m.fieldMap["listing_id"] = m.ListingId
	m.fieldMap["trade_order_id"] = m.TradeOrderId
	m.fieldMap["buyer_id"] = m.BuyerId
	m.fieldMap["status"] = m.Status
	m.fieldMap["expires_at"] = m.ExpiresAt
	m.fieldMap["version"] = m.Version
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
}

func (m marketplaceReservation) clone(db *gorm.DB) marketplaceReservation {
	m.marketplaceReservationDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m marketplaceReservation) replaceDB(db *gorm.DB) marketplaceReservation {
	m.marketplaceReservationDo.ReplaceDB(db)
	return m
}

type marketplaceReservationDo struct{ gen.DO }

type IMarketplaceReservationDo interface {
	gen.SubQuery
	Debug() IMarketplaceReservationDo
	WithContext(ctx context.Context) IMarketplaceReservationDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMarketplaceReservationDo
	WriteDB() IMarketplaceReservationDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMarketplaceReservationDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMarketplaceReservationDo
	Not(conds ...gen.Condition) IMarketplaceReservationDo
	Or(conds ...gen.Condition) IMarketplaceReservationDo
	Select(conds ...field.Expr) IMarketplaceReservationDo
	Where(conds ...gen.Condition) IMarketplaceReservationDo
	Order(conds ...field.Expr) IMarketplaceReservationDo
	Distinct(cols ...field.Expr) IMarketplaceReservationDo
	Omit(cols ...field.Expr) IMarketplaceReservationDo
	Join(table schema.Tabler, on ...field.Expr) IMarketplaceReservationDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMarketplaceReservationDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMarketplaceReservationDo
	Group(cols ...field.Expr) IMarketplaceReservationDo
	Having(conds ...gen.Condition) IMarketplaceReservationDo
	Limit(limit int) IMarketplaceReservationDo
	Offset(offset int) IMarketplaceReservationDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMarketplaceReservationDo
	Unscoped() IMarketplaceReservationDo
	Create(values ...*domain.MarketplaceReservation) error
	CreateInBatches(values []*domain.MarketplaceReservation, batchSize int) error
	Save(values ...*domain.MarketplaceReservation) error
	First() (*domain.MarketplaceReservation, error)
	Take() (*domain.MarketplaceReservation, error)
	Last() (*domain.MarketplaceReservation, error)
	Find() ([]*domain.MarketplaceReservation, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.MarketplaceReservation, err error)
	FindInBatches(result *[]*domain.MarketplaceReservation, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*domain.MarketplaceReservation) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMarketplaceReservationDo
	Assign(attrs ...field.AssignExpr) IMarketplaceReservationDo
	Joins(fields ...field.RelationField) IMarketplaceReservationDo
	Preload(fields ...field.RelationField) IMarketplaceReservationDo
	FirstOrInit() (*domain.MarketplaceReservation, error)
	FirstOrCreate() (*domain.MarketplaceReservation, error)
	FindByPage(offset int, limit int) (result []*domain.MarketplaceReservation, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMarketplaceReservationDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m marketplaceReservationDo) Debug() IMarketplaceReservationDo {
	return m.withDO(m.DO.Debug())
}

func (m marketplaceReservationDo) WithContext(ctx context.Context) IMarketplaceReservationDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m marketplaceReservationDo) ReadDB() IMarketplaceReservationDo {
	return m.Clauses(dbresolver.Read)
}

func (m marketplaceReservationDo) WriteDB() IMarketplaceReservationDo {
	return m.Clauses(dbresolver.Write)
}

func (m marketplaceReservationDo) Session(config *gorm.Session) IMarketplaceReservationDo {
	return m.withDO(m.DO.Session(config))
}

func (m marketplaceReservationDo) Clauses(conds ...clause.Expression) IMarketplaceReservationDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m marketplaceReservationDo) Returning(value interface{}, columns ...string) IMarketplaceReservationDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m marketplaceReservationDo) Not(conds ...gen.Condition) IMarketplaceReservationDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m marketplaceReservationDo) Or(conds ...gen.Condition) IMarketplaceReservationDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m marketplaceReservationDo) Select(conds ...field.Expr) IMarketplaceReservationDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m marketplaceReservationDo) Where(conds ...gen.Condition) IMarketplaceReservationDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m marketplaceReservationDo) Order(conds ...field.Expr) IMarketplaceReservationDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m marketplaceReservationDo) Distinct(cols ...field.Expr) IMarketplaceReservationDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m marketplaceReservationDo) Omit(cols ...field.Expr) IMarketplaceReservationDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m marketplaceReservationDo) Join(table schema.Tabler, on ...field.Expr) IMarketplaceReservationDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m marketplaceReservationDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMarketplaceReservationDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m marketplaceReservationDo) RightJoin(table schema.Tabler, on ...field.Expr) IMarketplaceReservationDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m marketplaceReservationDo) Group(cols ...field.Expr) IMarketplaceReservationDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m marketplaceReservationDo) Having(conds ...gen.Condition) IMarketplaceReservationDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m marketplaceReservationDo) Limit(limit int) IMarketplaceReservationDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m marketplaceReservationDo) Offset(offset int) IMarketplaceReservationDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m marketplaceReservationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMarketplaceReservationDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m marketplaceReservationDo) Unscoped() IMarketplaceReservationDo {
	return m.withDO(m.DO.Unscoped())
}

func (m marketplaceReservationDo) Create(values ...*domain.MarketplaceReservation) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m marketplaceReservationDo) CreateInBatches(values []*domain.MarketplaceReservation, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m marketplaceReservationDo) Save(values ...*domain.MarketplaceReservation) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m marketplaceReservationDo) First() (*domain.MarketplaceReservation, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*domain.MarketplaceReservation), nil
	}
}

func (m marketplaceReservationDo) Take() (*domain.MarketplaceReservation, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*domain.MarketplaceReservation), nil
	}
}

func (m marketplaceReservationDo) Last() (*domain.MarketplaceReservation, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*domain.MarketplaceReservation), nil
	}
}

func (m marketplaceReservationDo) Find() ([]*domain.MarketplaceReservation, error) {
	result, err := m.DO.Find()
	return result.([]*domain.MarketplaceReservation), err
}

func (m marketplaceReservationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.MarketplaceReservation, err error) {
	buf := make([]*domain.MarketplaceReservation, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m marketplaceReservationDo) FindInBatches(result *[]*domain.MarketplaceReservation, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m marketplaceReservationDo) Attrs(attrs ...field.AssignExpr) IMarketplaceReservationDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m marketplaceReservationDo) Assign(attrs ...field.AssignExpr) IMarketplaceReservationDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m marketplaceReservationDo) Joins(fields ...field.RelationField) IMarketplaceReservationDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m marketplaceReservationDo) Preload(fields ...field.RelationField) IMarketplaceReservationDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m marketplaceReservationDo) FirstOrInit() (*domain.MarketplaceReservation, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*domain.MarketplaceReservation), nil
	}
}

func (m marketplaceReservationDo) FirstOrCreate() (*domain.MarketplaceReservation, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*domain.MarketplaceReservation), nil
	}
}

func (m marketplaceReservationDo) FindByPage(offset int, limit int) (result []*domain.MarketplaceReservation, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m marketplaceReservationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m marketplaceReservationDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m marketplaceReservationDo) Delete(models ...*domain.MarketplaceReservation) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *marketplaceReservationDo) withDO(do gen.Dao) *marketplaceReservationDo {
	m.DO = *do.(*gen.DO)
	return m
}
