// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/weouc-plus/campus-platform/internal/modules/notice/domain"
)

func newNoticeAudience(db *gorm.DB, opts ...gen.DOOption) noticeAudience {
	_noticeAudience := noticeAudience{}

	_noticeAudience.noticeAudienceDo.UseDB(db, opts...)
	_noticeAudience.noticeAudienceDo.UseModel(&domain.NoticeAudience{})

	tableName := _noticeAudience.noticeAudienceDo.TableName()
	_noticeAudience.ALL = field.NewAsterisk(tableName)
	_noticeAudience.ID = field.NewUint64(tableName, "id")
	_noticeAudience.NoticeId = field.NewUint64(tableName, "notice_id")
	_noticeAudience.AudienceType = field.NewString(tableName, "audience_type")
	_noticeAudience.AudienceValue = field.NewString(tableName, "audience_value")
	_noticeAudience.CreatedAt = field.NewTime(tableName, "created_at")
	_noticeAudience.UpdatedAt = field.NewTime(tableName, "updated_at")

	_noticeAudience.fillFieldMap()

	return _noticeAudience
}

type noticeAudience struct {
	noticeAudienceDo noticeAudienceDo

	ALL           field.Asterisk
	ID            field.Uint64
	NoticeId      field.Uint64
	AudienceType  field.String
	AudienceValue field.String
	CreatedAt     field.Time
	UpdatedAt     field.Time

	fieldMap map[string]field.Expr
}

func (n noticeAudience) Table(newTableName string) *noticeAudience {
	n.noticeAudienceDo.UseTable(newTableName)
	return n.updateTableName(newTableName)
}

func (n noticeAudience) As(alias string) *noticeAudience {
	n.noticeAudienceDo.DO = *(n.noticeAudienceDo.As(alias).(*gen.DO))
	return n.updateTableName(alias)
}

func (n *noticeAudience) updateTableName(table string) *noticeAudience {
	n.ALL = field.NewAsterisk(table)
	n.ID = field.NewUint64(table, "id")
	n.NoticeId = field.NewUint64(table, "notice_id")
	n.AudienceType = field.NewString(table, "audience_type")
	n.AudienceValue = field.NewString(table, "audience_value")
	n.CreatedAt = field.NewTime(table, "created_at")
	n.UpdatedAt = field.NewTime(table, "updated_at")

	n.fillFieldMap()

	return n
}

func (n *noticeAudience) WithContext(ctx context.Context) INoticeAudienceDo {
	return n.noticeAudienceDo.WithContext(ctx)
}

func (n noticeAudience) TableName() string { return n.noticeAudienceDo.TableName() }

func (n noticeAudience) Alias() string { return n.noticeAudienceDo.Alias() }

func (n noticeAudience) Columns(cols ...field.Expr) gen.Columns {
	return n.noticeAudienceDo.Columns(cols...)
}

func (n *noticeAudience) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := n.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (n *noticeAudience) fillFieldMap() {
	n.fieldMap = make(map[string]field.Expr, 6)
	n.fieldMap["id"] = n.ID
	n.fieldMap["notice_id"] = n.NoticeId
	n.fieldMap["audience_type"] = n.AudienceType
	n.fieldMap["audience_value"] = n.AudienceValue
	n.fieldMap["created_at"] = n.CreatedAt
	n.fieldMap["updated_at"] = n.UpdatedAt
}

func (n noticeAudience) clone(db *gorm.DB) noticeAudience {
	n.noticeAudienceDo.ReplaceConnPool(db.Statement.ConnPool)
	return n
}

func (n noticeAudience) replaceDB(db *gorm.DB) noticeAudience {
	n.noticeAudienceDo.ReplaceDB(db)
	return n
}

type noticeAudienceDo struct{ gen.DO }

type INoticeAudienceDo interface {
	gen.SubQuery
	Debug() INoticeAudienceDo
	WithContext(ctx context.Context) INoticeAudienceDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() INoticeAudienceDo
	WriteDB() INoticeAudienceDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) INoticeAudienceDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) INoticeAudienceDo
	Not(conds ...gen.Condition) INoticeAudienceDo
	Or(conds ...gen.Condition) INoticeAudienceDo
	Select(conds ...field.Expr) INoticeAudienceDo
	Where(conds ...gen.Condition) INoticeAudienceDo
	Order(conds ...field.Expr) INoticeAudienceDo
	Distinct(cols ...field.Expr) INoticeAudienceDo
	Omit(cols ...field.Expr) INoticeAudienceDo
	Join(table schema.Tabler, on ...field.Expr) INoticeAudienceDo
	LeftJoin(table schema.Tabler, on ...field.Expr) INoticeAudienceDo
	RightJoin(table schema.Tabler, on ...field.Expr) INoticeAudienceDo
	Group(cols ...field.Expr) INoticeAudienceDo
	Having(conds ...gen.Condition) INoticeAudienceDo
	Limit(limit int) INoticeAudienceDo
	Offset(offset int) INoticeAudienceDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) INoticeAudienceDo
	Unscoped() INoticeAudienceDo
	Create(values ...*domain.NoticeAudience) error
	CreateInBatches(values []*domain.NoticeAudience, batchSize int) error
	Save(values ...*domain.NoticeAudience) error
	First() (*domain.NoticeAudience, error)
	Take() (*domain.NoticeAudience, error)
	Last() (*domain.NoticeAudience, error)
	Find() ([]*domain.NoticeAudience, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.NoticeAudience, err error)
	FindInBatches(result *[]*domain.NoticeAudience, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*domain.NoticeAudience) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) INoticeAudienceDo
	Assign(attrs ...field.AssignExpr) INoticeAudienceDo
	Joins(fields ...field.RelationField) INoticeAudienceDo
	Preload(fields ...field.RelationField) INoticeAudienceDo
	FirstOrInit() (*domain.NoticeAudience, error)
	FirstOrCreate() (*domain.NoticeAudience, error)
	FindByPage(offset int, limit int) (result []*domain.NoticeAudience, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) INoticeAudienceDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (n noticeAudienceDo) Debug() INoticeAudienceDo {
	return n.withDO(n.DO.Debug())
}

func (n noticeAudienceDo) WithContext(ctx context.Context) INoticeAudienceDo {
	return n.withDO(n.DO.WithContext(ctx))
}

func (n noticeAudienceDo) ReadDB() INoticeAudienceDo {
	return n.Clauses(dbresolver.Read)
}

func (n noticeAudienceDo) WriteDB() INoticeAudienceDo {
	return n.Clauses(dbresolver.Write)
}

func (n noticeAudienceDo) Session(config *gorm.Session) INoticeAudienceDo {
	return n.withDO(n.DO.Session(config))
}

func (n noticeAudienceDo) Clauses(conds ...clause.Expression) INoticeAudienceDo {
	return n.withDO(n.DO.Clauses(conds...))
}

func (n noticeAudienceDo) Returning(value interface{}, columns ...string) INoticeAudienceDo {
	return n.withDO(n.DO.Returning(value, columns...))
}

func (n noticeAudienceDo) Not(conds ...gen.Condition) INoticeAudienceDo {
	return n.withDO(n.DO.Not(conds...))
}

func (n noticeAudienceDo) Or(conds ...gen.Condition) INoticeAudienceDo {
	return n.withDO(n.DO.Or(conds...))
}

func (n noticeAudienceDo) Select(conds ...field.Expr) INoticeAudienceDo {
	return n.withDO(n.DO.Select(conds...))
}

func (n noticeAudienceDo) Where(conds ...gen.Condition) INoticeAudienceDo {
	return n.withDO(n.DO.Where(conds...))
}

func (n noticeAudienceDo) Order(conds ...field.Expr) INoticeAudienceDo {
	return n.withDO(n.DO.Order(conds...))
}

func (n noticeAudienceDo) Distinct(cols ...field.Expr) INoticeAudienceDo {
	return n.withDO(n.DO.Distinct(cols...))
}

func (n noticeAudienceDo) Omit(cols ...field.Expr) INoticeAudienceDo {
	return n.withDO(n.DO.Omit(cols...))
}

func (n noticeAudienceDo) Join(table schema.Tabler, on ...field.Expr) INoticeAudienceDo {
	return n.withDO(n.DO.Join(table, on...))
}

func (n noticeAudienceDo) LeftJoin(table schema.Tabler, on ...field.Expr) INoticeAudienceDo {
	return n.withDO(n.DO.LeftJoin(table, on...))
}

func (n noticeAudienceDo) RightJoin(table schema.Tabler, on ...field.Expr) INoticeAudienceDo {
	return n.withDO(n.DO.RightJoin(table, on...))
}

func (n noticeAudienceDo) Group(cols ...field.Expr) INoticeAudienceDo {
	return n.withDO(n.DO.Group(cols...))
}

func (n noticeAudienceDo) Having(conds ...gen.Condition) INoticeAudienceDo {
	return n.withDO(n.DO.Having(conds...))
}

func (n noticeAudienceDo) Limit(limit int) INoticeAudienceDo {
	return n.withDO(n.DO.Limit(limit))
}

func (n noticeAudienceDo) Offset(offset int) INoticeAudienceDo {
	return n.withDO(n.DO.Offset(offset))
}

func (n noticeAudienceDo) Scopes(funcs ...func(gen.Dao) gen.Dao) INoticeAudienceDo {
	return n.withDO(n.DO.Scopes(funcs...))
}

func (n noticeAudienceDo) Unscoped() INoticeAudienceDo {
	return n.withDO(n.DO.Unscoped())
}

func (n noticeAudienceDo) Create(values ...*domain.NoticeAudience) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Create(values)
}

func (n noticeAudienceDo) CreateInBatches(values []*domain.NoticeAudience, batchSize int) error {
	return n.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (n noticeAudienceDo) Save(values ...*domain.NoticeAudience) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Save(values)
}

func (n noticeAudienceDo) First() (*domain.NoticeAudience, error) {
	if result, err := n.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*domain.NoticeAudience), nil
	}
}

func (n noticeAudienceDo) Take() (*domain.NoticeAudience, error) {
	if result, err := n.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*domain.NoticeAudience), nil
	}
}

func (n noticeAudienceDo) Last() (*domain.NoticeAudience, error) {
	if result, err := n.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*domain.NoticeAudience), nil
	}
}

func (n noticeAudienceDo) Find() ([]*domain.NoticeAudience, error) {
	result, err := n.DO.Find()
	return result.([]*domain.NoticeAudience), err
}

func (n noticeAudienceDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.NoticeAudience, err error) {
	buf := make([]*domain.NoticeAudience, 0, batchSize)
	err = n.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (n noticeAudienceDo) FindInBatches(result *[]*domain.NoticeAudience, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return n.DO.FindInBatches(result, batchSize, fc)
}

func (n noticeAudienceDo) Attrs(attrs ...field.AssignExpr) INoticeAudienceDo {
	return n.withDO(n.DO.Attrs(attrs...))
}

func (n noticeAudienceDo) Assign(attrs ...field.AssignExpr) INoticeAudienceDo {
	return n.withDO(n.DO.Assign(attrs...))
}

func (n noticeAudienceDo) Joins(fields ...field.RelationField) INoticeAudienceDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Joins(_f))
	}
	return &n
}

func (n noticeAudienceDo) Preload(fields ...field.RelationField) INoticeAudienceDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Preload(_f))
	}
	return &n
}

func (n noticeAudienceDo) FirstOrInit() (*domain.NoticeAudience, error) {
	if result, err := n.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*domain.NoticeAudience), nil
	}
}

func (n noticeAudienceDo) FirstOrCreate() (*domain.NoticeAudience, error) {
	if result, err := n.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*domain.NoticeAudience), nil
	}
}

func (n noticeAudienceDo) FindByPage(offset int, limit int) (result []*domain.NoticeAudience, count int64, err error) {
	result, err = n.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = n.Offset(-1).Limit(-1).Count()
	return
}

func (n noticeAudienceDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = n.Count()
	if err != nil {
		return
	}

	err = n.Offset(offset).Limit(limit).Scan(result)
	return
}

func (n noticeAudienceDo) Scan(result interface{}) (err error) {
	return n.DO.Scan(result)
}

func (n noticeAudienceDo) Delete(models ...*domain.NoticeAudience) (result gen.ResultInfo, err error) {
	return n.DO.Delete(models)
}

func (n *noticeAudienceDo) withDO(do gen.Dao) *noticeAudienceDo {
	n.DO = *do.(*gen.DO)
	return n
}
