// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/weouc-plus/campus-platform/internal/modules/notice/domain"
)

func newNoticeRecipient(db *gorm.DB, opts ...gen.DOOption) noticeRecipient {
	_noticeRecipient := noticeRecipient{}

	_noticeRecipient.noticeRecipientDo.UseDB(db, opts...)
	_noticeRecipient.noticeRecipientDo.UseModel(&domain.NoticeRecipient{})

	tableName := _noticeRecipient.noticeRecipientDo.TableName()
	_noticeRecipient.ALL = field.NewAsterisk(tableName)
	_noticeRecipient.ID = field.NewUint64(tableName, "id")
	_noticeRecipient.NoticeId = field.NewUint64(tableName, "notice_id")
	_noticeRecipient.UserId = field.NewUint64(tableName, "user_id")
	_noticeRecipient.ReadAt = field.NewTime(tableName, "read_at")
	_noticeRecipient.CreatedAt = field.NewTime(tableName, "created_at")
	_noticeRecipient.UpdatedAt = field.NewTime(tableName, "updated_at")

	_noticeRecipient.fillFieldMap()

	return _noticeRecipient
}

type noticeRecipient struct {
	noticeRecipientDo noticeRecipientDo

	ALL       field.Asterisk
	ID        field.Uint64
	NoticeId  field.Uint64
	UserId    field.Uint64
	ReadAt    field.Time
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (n noticeRecipient) Table(newTableName string) *noticeRecipient {
	n.noticeRecipientDo.UseTable(newTableName)
	return n.updateTableName(newTableName)
}

func (n noticeRecipient) As(alias string) *noticeRecipient {
	n.noticeRecipientDo.DO = *(n.noticeRecipientDo.As(alias).(*gen.DO))
	return n.updateTableName(alias)
}

func (n *noticeRecipient) updateTableName(table string) *noticeRecipient {
	n.ALL = field.NewAsterisk(table)
	n.ID = field.NewUint64(table, "id")
	n.NoticeId = field.NewUint64(table, "notice_id")
	n.UserId = field.NewUint64(table, "user_id")
	n.ReadAt = field.NewTime(table, "read_at")
	n.CreatedAt = field.NewTime(table, "created_at")
	n.UpdatedAt = field.NewTime(table, "updated_at")

	n.fillFieldMap()

	return n
}

func (n *noticeRecipient) WithContext(ctx context.Context) INoticeRecipientDo {
	return n.noticeRecipientDo.WithContext(ctx)
}

func (n noticeRecipient) TableName() string { return n.noticeRecipientDo.TableName() }

func (n noticeRecipient) Alias() string { return n.noticeRecipientDo.Alias() }

func (n noticeRecipient) Columns(cols ...field.Expr) gen.Columns {
	return n.noticeRecipientDo.Columns(cols...)
}

func (n *noticeRecipient) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := n.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (n *noticeRecipient) fillFieldMap() {
	n.fieldMap = make(map[string]field.Expr, 6)
	n.fieldMap["id"] = n.ID
	n.fieldMap["notice_id"] = n.NoticeId
	n.fieldMap["user_id"] = n.UserId
	n.fieldMap["read_at"] = n.ReadAt
	n.fieldMap["created_at"] = n.CreatedAt
	n.fieldMap["updated_at"] = n.UpdatedAt
}

func (n noticeRecipient) clone(db *gorm.DB) noticeRecipient {
	n.noticeRecipientDo.ReplaceConnPool(db.Statement.ConnPool)
	return n
}

func (n noticeRecipient) replaceDB(db *gorm.DB) noticeRecipient {
	n.noticeRecipientDo.ReplaceDB(db)
	return n
}

type noticeRecipientDo struct{ gen.DO }

type INoticeRecipientDo interface {
	gen.SubQuery
	Debug() INoticeRecipientDo
	WithContext(ctx context.Context) INoticeRecipientDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() INoticeRecipientDo
	WriteDB() INoticeRecipientDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) INoticeRecipientDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) INoticeRecipientDo
	Not(conds ...gen.Condition) INoticeRecipientDo
	Or(conds ...gen.Condition) INoticeRecipientDo
	Select(conds ...field.Expr) INoticeRecipientDo
	Where(conds ...gen.Condition) INoticeRecipientDo
	Order(conds ...field.Expr) INoticeRecipientDo
	Distinct(cols ...field.Expr) INoticeRecipientDo
	Omit(cols ...field.Expr) INoticeRecipientDo
	Join(table schema.Tabler, on ...field.Expr) INoticeRecipientDo
	LeftJoin(table schema.Tabler, on ...field.Expr) INoticeRecipientDo
	RightJoin(table schema.Tabler, on ...field.Expr) INoticeRecipientDo
	Group(cols ...field.Expr) INoticeRecipientDo
	Having(conds ...gen.Condition) INoticeRecipientDo
	Limit(limit int) INoticeRecipientDo
	Offset(offset int) INoticeRecipientDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) INoticeRecipientDo
	Unscoped() INoticeRecipientDo
	Create(values ...*domain.NoticeRecipient) error
	CreateInBatches(values []*domain.NoticeRecipient, batchSize int) error
	Save(values ...*domain.NoticeRecipient) error
	First() (*domain.NoticeRecipient, error)
	Take() (*domain.NoticeRecipient, error)
	Last() (*domain.NoticeRecipient, error)
	Find() ([]*domain.NoticeRecipient, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.NoticeRecipient, err error)
	FindInBatches(result *[]*domain.NoticeRecipient, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*domain.NoticeRecipient) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) INoticeRecipientDo
	Assign(attrs ...field.AssignExpr) INoticeRecipientDo
	Joins(fields ...field.RelationField) INoticeRecipientDo
	Preload(fields ...field.RelationField) INoticeRecipientDo
	FirstOrInit() (*domain.NoticeRecipient, error)
	FirstOrCreate() (*domain.NoticeRecipient, error)
	FindByPage(offset int, limit int) (result []*domain.NoticeRecipient, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) INoticeRecipientDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (n noticeRecipientDo) Debug() INoticeRecipientDo {
	return n.withDO(n.DO.Debug())
}

func (n noticeRecipientDo) WithContext(ctx context.Context) INoticeRecipientDo {
	return n.withDO(n.DO.WithContext(ctx))
}

func (n noticeRecipientDo) ReadDB() INoticeRecipientDo {
	return n.Clauses(dbresolver.Read)
}

func (n noticeRecipientDo) WriteDB() INoticeRecipientDo {
	return n.Clauses(dbresolver.Write)
}

func (n noticeRecipientDo) Session(config *gorm.Session) INoticeRecipientDo {
	return n.withDO(n.DO.Session(config))
}

func (n noticeRecipientDo) Clauses(conds ...clause.Expression) INoticeRecipientDo {
	return n.withDO(n.DO.Clauses(conds...))
}

func (n noticeRecipientDo) Returning(value interface{}, columns ...string) INoticeRecipientDo {
	return n.withDO(n.DO.Returning(value, columns...))
}

func (n noticeRecipientDo) Not(conds ...gen.Condition) INoticeRecipientDo {
	return n.withDO(n.DO.Not(conds...))
}

func (n noticeRecipientDo) Or(conds ...gen.Condition) INoticeRecipientDo {
	return n.withDO(n.DO.Or(conds...))
}

func (n noticeRecipientDo) Select(conds ...field.Expr) INoticeRecipientDo {
	return n.withDO(n.DO.Select(conds...))
}

func (n noticeRecipientDo) Where(conds ...gen.Condition) INoticeRecipientDo {
	return n.withDO(n.DO.Where(conds...))
}

func (n noticeRecipientDo) Order(conds ...field.Expr) INoticeRecipientDo {
	return n.withDO(n.DO.Order(conds...))
}

func (n noticeRecipientDo) Distinct(cols ...field.Expr) INoticeRecipientDo {
	return n.withDO(n.DO.Distinct(cols...))
}

func (n noticeRecipientDo) Omit(cols ...field.Expr) INoticeRecipientDo {
	return n.withDO(n.DO.Omit(cols...))
}

func (n noticeRecipientDo) Join(table schema.Tabler, on ...field.Expr) INoticeRecipientDo {
	return n.withDO(n.DO.Join(table, on...))
}

func (n noticeRecipientDo) LeftJoin(table schema.Tabler, on ...field.Expr) INoticeRecipientDo {
	return n.withDO(n.DO.LeftJoin(table, on...))
}

func (n noticeRecipientDo) RightJoin(table schema.Tabler, on ...field.Expr) INoticeRecipientDo {
	return n.withDO(n.DO.RightJoin(table, on...))
}

func (n noticeRecipientDo) Group(cols ...field.Expr) INoticeRecipientDo {
	return n.withDO(n.DO.Group(cols...))
}

func (n noticeRecipientDo) Having(conds ...gen.Condition) INoticeRecipientDo {
	return n.withDO(n.DO.Having(conds...))
}

func (n noticeRecipientDo) Limit(limit int) INoticeRecipientDo {
	return n.withDO(n.DO.Limit(limit))
}

func (n noticeRecipientDo) Offset(offset int) INoticeRecipientDo {
	return n.withDO(n.DO.Offset(offset))
}

func (n noticeRecipientDo) Scopes(funcs ...func(gen.Dao) gen.Dao) INoticeRecipientDo {
	return n.withDO(n.DO.Scopes(funcs...))
}

func (n noticeRecipientDo) Unscoped() INoticeRecipientDo {
	return n.withDO(n.DO.Unscoped())
}

func (n noticeRecipientDo) Create(values ...*domain.NoticeRecipient) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Create(values)
}

func (n noticeRecipientDo) CreateInBatches(values []*domain.NoticeRecipient, batchSize int) error {
	return n.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (n noticeRecipientDo) Save(values ...*domain.NoticeRecipient) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Save(values)
}

func (n noticeRecipientDo) First() (*domain.NoticeRecipient, error) {
	if result, err := n.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*domain.NoticeRecipient), nil
	}
}

func (n noticeRecipientDo) Take() (*domain.NoticeRecipient, error) {
	if result, err := n.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*domain.NoticeRecipient), nil
	}
}

func (n noticeRecipientDo) Last() (*domain.NoticeRecipient, error) {
	if result, err := n.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*domain.NoticeRecipient), nil
	}
}

func (n noticeRecipientDo) Find() ([]*domain.NoticeRecipient, error) {
	result, err := n.DO.Find()
	return result.([]*domain.NoticeRecipient), err
}

func (n noticeRecipientDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.NoticeRecipient, err error) {
	buf := make([]*domain.NoticeRecipient, 0, batchSize)
	err = n.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (n noticeRecipientDo) FindInBatches(result *[]*domain.NoticeRecipient, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return n.DO.FindInBatches(result, batchSize, fc)
}

func (n noticeRecipientDo) Attrs(attrs ...field.AssignExpr) INoticeRecipientDo {
	return n.withDO(n.DO.Attrs(attrs...))
}

func (n noticeRecipientDo) Assign(attrs ...field.AssignExpr) INoticeRecipientDo {
	return n.withDO(n.DO.Assign(attrs...))
}

func (n noticeRecipientDo) Joins(fields ...field.RelationField) INoticeRecipientDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Joins(_f))
	}
	return &n
}

func (n noticeRecipientDo) Preload(fields ...field.RelationField) INoticeRecipientDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Preload(_f))
	}
	return &n
}

func (n noticeRecipientDo) FirstOrInit() (*domain.NoticeRecipient, error) {
	if result, err := n.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*domain.NoticeRecipient), nil
	}
}

func (n noticeRecipientDo) FirstOrCreate() (*domain.NoticeRecipient, error) {
	if result, err := n.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*domain.NoticeRecipient), nil
	}
}

func (n noticeRecipientDo) FindByPage(offset int, limit int) (result []*domain.NoticeRecipient, count int64, err error) {
	result, err = n.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = n.Offset(-1).Limit(-1).Count()
	return
}

func (n noticeRecipientDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = n.Count()
	if err != nil {
		return
	}

	err = n.Offset(offset).Limit(limit).Scan(result)
	return
}

func (n noticeRecipientDo) Scan(result interface{}) (err error) {
	return n.DO.Scan(result)
}

func (n noticeRecipientDo) Delete(models ...*domain.NoticeRecipient) (result gen.ResultInfo, err error) {
	return n.DO.Delete(models)
}

func (n *noticeRecipientDo) withDO(do gen.Dao) *noticeRecipientDo {
	n.DO = *do.(*gen.DO)
	return n
}
