// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/weouc-plus/campus-platform/internal/modules/payment/domain"
)

func newPaymentCallback(db *gorm.DB, opts ...gen.DOOption) paymentCallback {
	_paymentCallback := paymentCallback{}

	_paymentCallback.paymentCallbackDo.UseDB(db, opts...)
	_paymentCallback.paymentCallbackDo.UseModel(&domain.PaymentCallback{})

	tableName := _paymentCallback.paymentCallbackDo.TableName()
	_paymentCallback.ALL = field.NewAsterisk(tableName)
	_paymentCallback.ID = field.NewUint64(tableName, "id")
	_paymentCallback.Provider = field.NewString(tableName, "provider")
	_paymentCallback.ProviderEventId = field.NewString(tableName, "provider_event_id")
	_paymentCallback.PayloadDigest = field.NewString(tableName, "payload_digest")
	_paymentCallback.Status = field.NewString(tableName, "status")
	_paymentCallback.ProcessedAt = field.NewTime(tableName, "processed_at")
	_paymentCallback.LastError = field.NewString(tableName, "last_error")
	_paymentCallback.CreatedAt = field.NewTime(tableName, "created_at")
	_paymentCallback.UpdatedAt = field.NewTime(tableName, "updated_at")

	_paymentCallback.fillFieldMap()

	return _paymentCallback
}

type paymentCallback struct {
	paymentCallbackDo paymentCallbackDo

	ALL             field.Asterisk
	ID              field.Uint64
	Provider        field.String
	ProviderEventId field.String
	PayloadDigest   field.String
	Status          field.String
	ProcessedAt     field.Time
	LastError       field.String
	CreatedAt       field.Time
	UpdatedAt       field.Time

	fieldMap map[string]field.Expr
}

func (p paymentCallback) Table(newTableName string) *paymentCallback {
	p.paymentCallbackDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p paymentCallback) As(alias string) *paymentCallback {
	p.paymentCallbackDo.DO = *(p.paymentCallbackDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *paymentCallback) updateTableName(table string) *paymentCallback {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewUint64(table, "id")
	p.Provider = field.NewString(table, "provider")
	p.ProviderEventId = field.NewString(table, "provider_event_id")
	p.PayloadDigest = field.NewString(table, "payload_digest")
	p.Status = field.NewString(table, "status")
	p.ProcessedAt = field.NewTime(table, "processed_at")
	p.LastError = field.NewString(table, "last_error")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")

	p.fillFieldMap()

	return p
}

func (p *paymentCallback) WithContext(ctx context.Context) IPaymentCallbackDo {
	return p.paymentCallbackDo.WithContext(ctx)
}

func (p paymentCallback) TableName() string { return p.paymentCallbackDo.TableName() }

func (p paymentCallback) Alias() string { return p.paymentCallbackDo.Alias() }

func (p paymentCallback) Columns(cols ...field.Expr) gen.Columns {
	return p.paymentCallbackDo.Columns(cols...)
}

func (p *paymentCallback) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *paymentCallback) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 9)
	p.fieldMap["id"] = p.ID
	p.fieldMap["provider"] = p.Provider
	p.fieldMap["provider_event_id"] = p.ProviderEventId
	p.fieldMap["payload_digest"] = p.PayloadDigest
	p.fieldMap["status"] = p.Status
	p.fieldMap["processed_at"] = p.ProcessedAt
	p.fieldMap["last_error"] = p.LastError
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
}

func (p paymentCallback) clone(db *gorm.DB) paymentCallback {
	p.paymentCallbackDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p paymentCallback) replaceDB(db *gorm.DB) paymentCallback {
	p.paymentCallbackDo.ReplaceDB(db)
	return p
}

type paymentCallbackDo struct{ gen.DO }

type IPaymentCallbackDo interface {
	gen.SubQuery
	Debug() IPaymentCallbackDo
	WithContext(ctx context.Context) IPaymentCallbackDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPaymentCallbackDo
	WriteDB() IPaymentCallbackDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPaymentCallbackDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPaymentCallbackDo
	Not(conds ...gen.Condition) IPaymentCallbackDo
	Or(conds ...gen.Condition) IPaymentCallbackDo
	Select(conds ...field.Expr) IPaymentCallbackDo
	Where(conds ...gen.Condition) IPaymentCallbackDo
	Order(conds ...field.Expr) IPaymentCallbackDo
	Distinct(cols ...field.Expr) IPaymentCallbackDo
	Omit(cols ...field.Expr) IPaymentCallbackDo
	Join(table schema.Tabler, on ...field.Expr) IPaymentCallbackDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPaymentCallbackDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPaymentCallbackDo
	Group(cols ...field.Expr) IPaymentCallbackDo
	Having(conds ...gen.Condition) IPaymentCallbackDo
	Limit(limit int) IPaymentCallbackDo
	Offset(offset int) IPaymentCallbackDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPaymentCallbackDo
	Unscoped() IPaymentCallbackDo
	Create(values ...*domain.PaymentCallback) error
	CreateInBatches(values []*domain.PaymentCallback, batchSize int) error
	Save(values ...*domain.PaymentCallback) error
	First() (*domain.PaymentCallback, error)
	Take() (*domain.PaymentCallback, error)
	Last() (*domain.PaymentCallback, error)
	Find() ([]*domain.PaymentCallback, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.PaymentCallback, err error)
	FindInBatches(result *[]*domain.PaymentCallback, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*domain.PaymentCallback) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPaymentCallbackDo
	Assign(attrs ...field.AssignExpr) IPaymentCallbackDo
	Joins(fields ...field.RelationField) IPaymentCallbackDo
	Preload(fields ...field.RelationField) IPaymentCallbackDo
	FirstOrInit() (*domain.PaymentCallback, error)
	FirstOrCreate() (*domain.PaymentCallback, error)
	FindByPage(offset int, limit int) (result []*domain.PaymentCallback, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPaymentCallbackDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p paymentCallbackDo) Debug() IPaymentCallbackDo {
	return p.withDO(p.DO.Debug())
}

func (p paymentCallbackDo) WithContext(ctx context.Context) IPaymentCallbackDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p paymentCallbackDo) ReadDB() IPaymentCallbackDo {
	return p.Clauses(dbresolver.Read)
}

func (p paymentCallbackDo) WriteDB() IPaymentCallbackDo {
	return p.Clauses(dbresolver.Write)
}

func (p paymentCallbackDo) Session(config *gorm.Session) IPaymentCallbackDo {
	return p.withDO(p.DO.Session(config))
}

func (p paymentCallbackDo) Clauses(conds ...clause.Expression) IPaymentCallbackDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p paymentCallbackDo) Returning(value interface{}, columns ...string) IPaymentCallbackDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p paymentCallbackDo) Not(conds ...gen.Condition) IPaymentCallbackDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p paymentCallbackDo) Or(conds ...gen.Condition) IPaymentCallbackDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p paymentCallbackDo) Select(conds ...field.Expr) IPaymentCallbackDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p paymentCallbackDo) Where(conds ...gen.Condition) IPaymentCallbackDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p paymentCallbackDo) Order(conds ...field.Expr) IPaymentCallbackDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p paymentCallbackDo) Distinct(cols ...field.Expr) IPaymentCallbackDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p paymentCallbackDo) Omit(cols ...field.Expr) IPaymentCallbackDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p paymentCallbackDo) Join(table schema.Tabler, on ...field.Expr) IPaymentCallbackDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p paymentCallbackDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPaymentCallbackDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p paymentCallbackDo) RightJoin(table schema.Tabler, on ...field.Expr) IPaymentCallbackDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p paymentCallbackDo) Group(cols ...field.Expr) IPaymentCallbackDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p paymentCallbackDo) Having(conds ...gen.Condition) IPaymentCallbackDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p paymentCallbackDo) Limit(limit int) IPaymentCallbackDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p paymentCallbackDo) Offset(offset int) IPaymentCallbackDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p paymentCallbackDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPaymentCallbackDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p paymentCallbackDo) Unscoped() IPaymentCallbackDo {
	return p.withDO(p.DO.Unscoped())
}

func (p paymentCallbackDo) Create(values ...*domain.PaymentCallback) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p paymentCallbackDo) CreateInBatches(values []*domain.PaymentCallback, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p paymentCallbackDo) Save(values ...*domain.PaymentCallback) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p paymentCallbackDo) First() (*domain.PaymentCallback, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*domain.PaymentCallback), nil
	}
}

func (p paymentCallbackDo) Take() (*domain.PaymentCallback, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*domain.PaymentCallback), nil
	}
}

func (p paymentCallbackDo) Last() (*domain.PaymentCallback, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*domain.PaymentCallback), nil
	}
}

func (p paymentCallbackDo) Find() ([]*domain.PaymentCallback, error) {
	result, err := p.DO.Find()
	return result.([]*domain.PaymentCallback), err
}

func (p paymentCallbackDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.PaymentCallback, err error) {
	buf := make([]*domain.PaymentCallback, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p paymentCallbackDo) FindInBatches(result *[]*domain.PaymentCallback, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p paymentCallbackDo) Attrs(attrs ...field.AssignExpr) IPaymentCallbackDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p paymentCallbackDo) Assign(attrs ...field.AssignExpr) IPaymentCallbackDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p paymentCallbackDo) Joins(fields ...field.RelationField) IPaymentCallbackDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p paymentCallbackDo) Preload(fields ...field.RelationField) IPaymentCallbackDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p paymentCallbackDo) FirstOrInit() (*domain.PaymentCallback, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*domain.PaymentCallback), nil
	}
}

func (p paymentCallbackDo) FirstOrCreate() (*domain.PaymentCallback, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*domain.PaymentCallback), nil
	}
}

func (p paymentCallbackDo) FindByPage(offset int, limit int) (result []*domain.PaymentCallback, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p paymentCallbackDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p paymentCallbackDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p paymentCallbackDo) Delete(models ...*domain.PaymentCallback) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *paymentCallbackDo) withDO(do gen.Dao) *paymentCallbackDo {
	p.DO = *do.(*gen.DO)
	return p
}
