// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/weouc-plus/campus-platform/internal/modules/payment/domain"
)

func newPaymentTransaction(db *gorm.DB, opts ...gen.DOOption) paymentTransaction {
	_paymentTransaction := paymentTransaction{}

	_paymentTransaction.paymentTransactionDo.UseDB(db, opts...)
	_paymentTransaction.paymentTransactionDo.UseModel(&domain.PaymentTransaction{})

	tableName := _paymentTransaction.paymentTransactionDo.TableName()
	_paymentTransaction.ALL = field.NewAsterisk(tableName)
	_paymentTransaction.ID = field.NewUint64(tableName, "id")
	_paymentTransaction.IntentId = field.NewUint64(tableName, "intent_id")
	_paymentTransaction.AttemptNo = field.NewInt64(tableName, "attempt_no")
	_paymentTransaction.Provider = field.NewString(tableName, "provider")
	_paymentTransaction.ProviderTransactionId = field.NewString(tableName, "provider_transaction_id")
	_paymentTransaction.Status = field.NewString(tableName, "status")
	_paymentTransaction.FailureCode = field.NewString(tableName, "failure_code")
	_paymentTransaction.FailureMessage = field.NewString(tableName, "failure_message")
	_paymentTransaction.PaidAt = field.NewTime(tableName, "paid_at")
	_paymentTransaction.CreatedAt = field.NewTime(tableName, "created_at")
	_paymentTransaction.UpdatedAt = field.NewTime(tableName, "updated_at")

	_paymentTransaction.fillFieldMap()

	return _paymentTransaction
}

type paymentTransaction struct {
	paymentTransactionDo paymentTransactionDo

	ALL                   field.Asterisk
	ID                    field.Uint64
	IntentId              field.Uint64
	AttemptNo             field.Int64
	Provider              field.String
	ProviderTransactionId field.String
	Status                field.String
	FailureCode           field.String
	FailureMessage        field.String
	PaidAt                field.Time
	CreatedAt             field.Time
	UpdatedAt             field.Time

	fieldMap map[string]field.Expr
}

func (p paymentTransaction) Table(newTableName string) *paymentTransaction {
	p.paymentTransactionDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p paymentTransaction) As(alias string) *paymentTransaction {
	p.paymentTransactionDo.DO = *(p.paymentTransactionDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *paymentTransaction) updateTableName(table string) *paymentTransaction {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewUint64(table, "id")
	p.IntentId = field.NewUint64(table, "intent_id")
	p.AttemptNo = field.NewInt64(table, "attempt_no")
	p.Provider = field.NewString(table, "provider")
	p.ProviderTransactionId = field.NewString(table, "provider_transaction_id")
	p.Status = field.NewString(table, "status")
	p.FailureCode = field.NewString(table, "failure_code")
	p.FailureMessage = field.NewString(table, "failure_message")
	p.PaidAt = field.NewTime(table, "paid_at")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")

	p.fillFieldMap()

	return p
}

func (p *paymentTransaction) WithContext(ctx context.Context) IPaymentTransactionDo {
	return p.paymentTransactionDo.WithContext(ctx)
}

func (p paymentTransaction) TableName() string { return p.paymentTransactionDo.TableName() }

func (p paymentTransaction) Alias() string { return p.paymentTransactionDo.Alias() }

func (p paymentTransaction) Columns(cols ...field.Expr) gen.Columns {
	return p.paymentTransactionDo.Columns(cols...)
}

func (p *paymentTransaction) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *paymentTransaction) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 11)
	p.fieldMap["id"] = p.ID
	p.fieldMap["intent_id"] = p.IntentId
	p.fieldMap["attempt_no"] = p.AttemptNo
	p.fieldMap["provider"] = p.Provider
	p.fieldMap["provider_transaction_id"] = p.ProviderTransactionId
	p.fieldMap["status"] = p.Status
	p.fieldMap["failure_code"] = p.FailureCode
	p.fieldMap["failure_message"] = p.FailureMessage
	p.fieldMap["paid_at"] = p.PaidAt
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
}

func (p paymentTransaction) clone(db *gorm.DB) paymentTransaction {
	p.paymentTransactionDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p paymentTransaction) replaceDB(db *gorm.DB) paymentTransaction {
	p.paymentTransactionDo.ReplaceDB(db)
	return p
}

type paymentTransactionDo struct{ gen.DO }

type IPaymentTransactionDo interface {
	gen.SubQuery
	Debug() IPaymentTransactionDo
	WithContext(ctx context.Context) IPaymentTransactionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPaymentTransactionDo
	WriteDB() IPaymentTransactionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPaymentTransactionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPaymentTransactionDo
	Not(conds ...gen.Condition) IPaymentTransactionDo
	Or(conds ...gen.Condition) IPaymentTransactionDo
	Select(conds ...field.Expr) IPaymentTransactionDo
	Where(conds ...gen.Condition) IPaymentTransactionDo
	Order(conds ...field.Expr) IPaymentTransactionDo
	Distinct(cols ...field.Expr) IPaymentTransactionDo
	Omit(cols ...field.Expr) IPaymentTransactionDo
	Join(table schema.Tabler, on ...field.Expr) IPaymentTransactionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPaymentTransactionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPaymentTransactionDo
	Group(cols ...field.Expr) IPaymentTransactionDo
	Having(conds ...gen.Condition) IPaymentTransactionDo
	Limit(limit int) IPaymentTransactionDo
	Offset(offset int) IPaymentTransactionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPaymentTransactionDo
	Unscoped() IPaymentTransactionDo
	Create(values ...*domain.PaymentTransaction) error
	CreateInBatches(values []*domain.PaymentTransaction, batchSize int) error
	Save(values ...*domain.PaymentTransaction) error
	First() (*domain.PaymentTransaction, error)
	Take() (*domain.PaymentTransaction, error)
	Last() (*domain.PaymentTransaction, error)
	Find() ([]*domain.PaymentTransaction, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.PaymentTransaction, err error)
	FindInBatches(result *[]*domain.PaymentTransaction, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*domain.PaymentTransaction) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPaymentTransactionDo
	Assign(attrs ...field.AssignExpr) IPaymentTransactionDo
	Joins(fields ...field.RelationField) IPaymentTransactionDo
	Preload(fields ...field.RelationField) IPaymentTransactionDo
	FirstOrInit() (*domain.PaymentTransaction, error)
	FirstOrCreate() (*domain.PaymentTransaction, error)
	FindByPage(offset int, limit int) (result []*domain.PaymentTransaction, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPaymentTransactionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p paymentTransactionDo) Debug() IPaymentTransactionDo {
	return p.withDO(p.DO.Debug())
}

func (p paymentTransactionDo) WithContext(ctx context.Context) IPaymentTransactionDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p paymentTransactionDo) ReadDB() IPaymentTransactionDo {
	return p.Clauses(dbresolver.Read)
}

func (p paymentTransactionDo) WriteDB() IPaymentTransactionDo {
	return p.Clauses(dbresolver.Write)
}

func (p paymentTransactionDo) Session(config *gorm.Session) IPaymentTransactionDo {
	return p.withDO(p.DO.Session(config))
}

func (p paymentTransactionDo) Clauses(conds ...clause.Expression) IPaymentTransactionDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p paymentTransactionDo) Returning(value interface{}, columns ...string) IPaymentTransactionDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p paymentTransactionDo) Not(conds ...gen.Condition) IPaymentTransactionDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p paymentTransactionDo) Or(conds ...gen.Condition) IPaymentTransactionDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p paymentTransactionDo) Select(conds ...field.Expr) IPaymentTransactionDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p paymentTransactionDo) Where(conds ...gen.Condition) IPaymentTransactionDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p paymentTransactionDo) Order(conds ...field.Expr) IPaymentTransactionDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p paymentTransactionDo) Distinct(cols ...field.Expr) IPaymentTransactionDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p paymentTransactionDo) Omit(cols ...field.Expr) IPaymentTransactionDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p paymentTransactionDo) Join(table schema.Tabler, on ...field.Expr) IPaymentTransactionDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p paymentTransactionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPaymentTransactionDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p paymentTransactionDo) RightJoin(table schema.Tabler, on ...field.Expr) IPaymentTransactionDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p paymentTransactionDo) Group(cols ...field.Expr) IPaymentTransactionDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p paymentTransactionDo) Having(conds ...gen.Condition) IPaymentTransactionDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p paymentTransactionDo) Limit(limit int) IPaymentTransactionDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p paymentTransactionDo) Offset(offset int) IPaymentTransactionDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p paymentTransactionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPaymentTransactionDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p paymentTransactionDo) Unscoped() IPaymentTransactionDo {
	return p.withDO(p.DO.Unscoped())
}

func (p paymentTransactionDo) Create(values ...*domain.PaymentTransaction) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p paymentTransactionDo) CreateInBatches(values []*domain.PaymentTransaction, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p paymentTransactionDo) Save(values ...*domain.PaymentTransaction) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p paymentTransactionDo) First() (*domain.PaymentTransaction, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*domain.PaymentTransaction), nil
	}
}

func (p paymentTransactionDo) Take() (*domain.PaymentTransaction, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*domain.PaymentTransaction), nil
	}
}

func (p paymentTransactionDo) Last() (*domain.PaymentTransaction, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*domain.PaymentTransaction), nil
	}
}

func (p paymentTransactionDo) Find() ([]*domain.PaymentTransaction, error) {
	result, err := p.DO.Find()
	return result.([]*domain.PaymentTransaction), err
}

func (p paymentTransactionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.PaymentTransaction, err error) {
	buf := make([]*domain.PaymentTransaction, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p paymentTransactionDo) FindInBatches(result *[]*domain.PaymentTransaction, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p paymentTransactionDo) Attrs(attrs ...field.AssignExpr) IPaymentTransactionDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p paymentTransactionDo) Assign(attrs ...field.AssignExpr) IPaymentTransactionDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p paymentTransactionDo) Joins(fields ...field.RelationField) IPaymentTransactionDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p paymentTransactionDo) Preload(fields ...field.RelationField) IPaymentTransactionDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p paymentTransactionDo) FirstOrInit() (*domain.PaymentTransaction, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*domain.PaymentTransaction), nil
	}
}

func (p paymentTransactionDo) FirstOrCreate() (*domain.PaymentTransaction, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*domain.PaymentTransaction), nil
	}
}

func (p paymentTransactionDo) FindByPage(offset int, limit int) (result []*domain.PaymentTransaction, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p paymentTransactionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p paymentTransactionDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p paymentTransactionDo) Delete(models ...*domain.PaymentTransaction) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *paymentTransactionDo) withDO(do gen.Dao) *paymentTransactionDo {
	p.DO = *do.(*gen.DO)
	return p
}
