// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/weouc-plus/campus-platform/internal/modules/payment/domain"
)

func newPaymentIntent(db *gorm.DB, opts ...gen.DOOption) paymentIntent {
	_paymentIntent := paymentIntent{}

	_paymentIntent.paymentIntentDo.UseDB(db, opts...)
	_paymentIntent.paymentIntentDo.UseModel(&domain.PaymentIntent{})

	tableName := _paymentIntent.paymentIntentDo.TableName()
	_paymentIntent.ALL = field.NewAsterisk(tableName)
	_paymentIntent.ID = field.NewUint64(tableName, "id")
	_paymentIntent.IntentNo = field.NewString(tableName, "intent_no")
	_paymentIntent.ResourceType = field.NewString(tableName, "resource_type")
	_paymentIntent.ResourceId = field.NewUint64(tableName, "resource_id")
	_paymentIntent.PayerId = field.NewUint64(tableName, "payer_id")
	_paymentIntent.PayeeId = field.NewUint64(tableName, "payee_id")
	_paymentIntent.AmountCents = field.NewInt64(tableName, "amount_cents")
	_paymentIntent.Currency = field.NewString(tableName, "currency")
	_paymentIntent.Method = field.NewString(tableName, "method")
	_paymentIntent.Provider = field.NewString(tableName, "provider")
	_paymentIntent.Status = field.NewString(tableName, "status")
	_paymentIntent.IdempotencyKey = field.NewString(tableName, "idempotency_key")
	_paymentIntent.ProviderIntentId = field.NewString(tableName, "provider_intent_id")
	_paymentIntent.ExpiresAt = field.NewTime(tableName, "expires_at")
	_paymentIntent.Version = field.NewUint64(tableName, "version")
	_paymentIntent.CreatedAt = field.NewTime(tableName, "created_at")
	_paymentIntent.UpdatedAt = field.NewTime(tableName, "updated_at")

	_paymentIntent.fillFieldMap()

	return _paymentIntent
}

type paymentIntent struct {
	paymentIntentDo paymentIntentDo

	ALL              field.Asterisk
	ID               field.Uint64
	IntentNo         field.String
	ResourceType     field.String
	ResourceId       field.Uint64
	PayerId          field.Uint64
	PayeeId          field.Uint64
	AmountCents      field.Int64
	Currency         field.String
	Method           field.String
	Provider         field.String
	Status           field.String
	IdempotencyKey   field.String
	ProviderIntentId field.String
	ExpiresAt        field.Time
	Version          field.Uint64
	CreatedAt        field.Time
	UpdatedAt        field.Time

	fieldMap map[string]field.Expr
}

func (p paymentIntent) Table(newTableName string) *paymentIntent {
	p.paymentIntentDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p paymentIntent) As(alias string) *paymentIntent {
	p.paymentIntentDo.DO = *(p.paymentIntentDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *paymentIntent) updateTableName(table string) *paymentIntent {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewUint64(table, "id")
	p.IntentNo = field.NewString(table, "intent_no")
	p.ResourceType = field.NewString(table, "resource_type")
	p.ResourceId = field.NewUint64(table, "resource_id")
	p.PayerId = field.NewUint64(table, "payer_id")
	p.PayeeId = field.NewUint64(table, "payee_id")
	p.AmountCents = field.NewInt64(table, "amount_cents")
	p.Currency = field.NewString(table, "currency")
	p.Method = field.NewString(table, "method")
	p.Provider = field.NewString(table, "provider")
	p.Status = field.NewString(table, "status")
	p.IdempotencyKey = field.NewString(table, "idempotency_key")
	p.ProviderIntentId = field.NewString(table, "provider_intent_id")
	p.ExpiresAt = field.NewTime(table, "expires_at")
	p.Version = field.NewUint64(table, "version")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")

	p.fillFieldMap()

	return p
}

func (p *paymentIntent) WithContext(ctx context.Context) IPaymentIntentDo {
	return p.paymentIntentDo.WithContext(ctx)
}

func (p paymentIntent) TableName() string { return p.paymentIntentDo.TableName() }

func (p paymentIntent) Alias() string { return p.paymentIntentDo.Alias() }

func (p paymentIntent) Columns(cols ...field.Expr) gen.Columns {
	return p.paymentIntentDo.Columns(cols...)
}

func (p *paymentIntent) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *paymentIntent) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 17)
	p.fieldMap["id"] = p.ID
	p.fieldMap["intent_no"] = p.IntentNo
	p.fieldMap["resource_type"] = p.ResourceType
	p.fieldMap["resource_id"] = p.ResourceId
	p.fieldMap["payer_id"] = p.PayerId
	p.fieldMap["payee_id"] = p.PayeeId
	p.fieldMap["amount_cents"] = p.AmountCents
	p.fieldMap["currency"] = p.Currency
	p.fieldMap["method"] = p.Method
	p.fieldMap["provider"] = p.Provider
	p.fieldMap["status"] = p.Status
	p.fieldMap["idempotency_key"] = p.IdempotencyKey
	p.fieldMap["provider_intent_id"] = p.ProviderIntentId
	p.fieldMap["expires_at"] = p.ExpiresAt
	p.fieldMap["version"] = p.Version
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
}

func (p paymentIntent) clone(db *gorm.DB) paymentIntent {
	p.paymentIntentDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p paymentIntent) replaceDB(db *gorm.DB) paymentIntent {
	p.paymentIntentDo.ReplaceDB(db)
	return p
}

type paymentIntentDo struct{ gen.DO }

type IPaymentIntentDo interface {
	gen.SubQuery
	Debug() IPaymentIntentDo
	WithContext(ctx context.Context) IPaymentIntentDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPaymentIntentDo
	WriteDB() IPaymentIntentDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPaymentIntentDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPaymentIntentDo
	Not(conds ...gen.Condition) IPaymentIntentDo
	Or(conds ...gen.Condition) IPaymentIntentDo
	Select(conds ...field.Expr) IPaymentIntentDo
	Where(conds ...gen.Condition) IPaymentIntentDo
	Order(conds ...field.Expr) IPaymentIntentDo
	Distinct(cols ...field.Expr) IPaymentIntentDo
	Omit(cols ...field.Expr) IPaymentIntentDo
	Join(table schema.Tabler, on ...field.Expr) IPaymentIntentDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPaymentIntentDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPaymentIntentDo
	Group(cols ...field.Expr) IPaymentIntentDo
	Having(conds ...gen.Condition) IPaymentIntentDo
	Limit(limit int) IPaymentIntentDo
	Offset(offset int) IPaymentIntentDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPaymentIntentDo
	Unscoped() IPaymentIntentDo
	Create(values ...*domain.PaymentIntent) error
	CreateInBatches(values []*domain.PaymentIntent, batchSize int) error
	Save(values ...*domain.PaymentIntent) error
	First() (*domain.PaymentIntent, error)
	Take() (*domain.PaymentIntent, error)
	Last() (*domain.PaymentIntent, error)
	Find() ([]*domain.PaymentIntent, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.PaymentIntent, err error)
	FindInBatches(result *[]*domain.PaymentIntent, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*domain.PaymentIntent) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPaymentIntentDo
	Assign(attrs ...field.AssignExpr) IPaymentIntentDo
	Joins(fields ...field.RelationField) IPaymentIntentDo
	Preload(fields ...field.RelationField) IPaymentIntentDo
	FirstOrInit() (*domain.PaymentIntent, error)
	FirstOrCreate() (*domain.PaymentIntent, error)
	FindByPage(offset int, limit int) (result []*domain.PaymentIntent, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPaymentIntentDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p paymentIntentDo) Debug() IPaymentIntentDo {
	return p.withDO(p.DO.Debug())
}

func (p paymentIntentDo) WithContext(ctx context.Context) IPaymentIntentDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p paymentIntentDo) ReadDB() IPaymentIntentDo {
	return p.Clauses(dbresolver.Read)
}

func (p paymentIntentDo) WriteDB() IPaymentIntentDo {
	return p.Clauses(dbresolver.Write)
}

func (p paymentIntentDo) Session(config *gorm.Session) IPaymentIntentDo {
	return p.withDO(p.DO.Session(config))
}

func (p paymentIntentDo) Clauses(conds ...clause.Expression) IPaymentIntentDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p paymentIntentDo) Returning(value interface{}, columns ...string) IPaymentIntentDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p paymentIntentDo) Not(conds ...gen.Condition) IPaymentIntentDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p paymentIntentDo) Or(conds ...gen.Condition) IPaymentIntentDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p paymentIntentDo) Select(conds ...field.Expr) IPaymentIntentDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p paymentIntentDo) Where(conds ...gen.Condition) IPaymentIntentDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p paymentIntentDo) Order(conds ...field.Expr) IPaymentIntentDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p paymentIntentDo) Distinct(cols ...field.Expr) IPaymentIntentDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p paymentIntentDo) Omit(cols ...field.Expr) IPaymentIntentDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p paymentIntentDo) Join(table schema.Tabler, on ...field.Expr) IPaymentIntentDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p paymentIntentDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPaymentIntentDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p paymentIntentDo) RightJoin(table schema.Tabler, on ...field.Expr) IPaymentIntentDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p paymentIntentDo) Group(cols ...field.Expr) IPaymentIntentDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p paymentIntentDo) Having(conds ...gen.Condition) IPaymentIntentDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p paymentIntentDo) Limit(limit int) IPaymentIntentDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p paymentIntentDo) Offset(offset int) IPaymentIntentDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p paymentIntentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPaymentIntentDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p paymentIntentDo) Unscoped() IPaymentIntentDo {
	return p.withDO(p.DO.Unscoped())
}

func (p paymentIntentDo) Create(values ...*domain.PaymentIntent) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p paymentIntentDo) CreateInBatches(values []*domain.PaymentIntent, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p paymentIntentDo) Save(values ...*domain.PaymentIntent) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p paymentIntentDo) First() (*domain.PaymentIntent, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*domain.PaymentIntent), nil
	}
}

func (p paymentIntentDo) Take() (*domain.PaymentIntent, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*domain.PaymentIntent), nil
	}
}

func (p paymentIntentDo) Last() (*domain.PaymentIntent, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*domain.PaymentIntent), nil
	}
}

func (p paymentIntentDo) Find() ([]*domain.PaymentIntent, error) {
	result, err := p.DO.Find()
	return result.([]*domain.PaymentIntent), err
}

func (p paymentIntentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.PaymentIntent, err error) {
	buf := make([]*domain.PaymentIntent, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p paymentIntentDo) FindInBatches(result *[]*domain.PaymentIntent, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p paymentIntentDo) Attrs(attrs ...field.AssignExpr) IPaymentIntentDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p paymentIntentDo) Assign(attrs ...field.AssignExpr) IPaymentIntentDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p paymentIntentDo) Joins(fields ...field.RelationField) IPaymentIntentDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p paymentIntentDo) Preload(fields ...field.RelationField) IPaymentIntentDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p paymentIntentDo) FirstOrInit() (*domain.PaymentIntent, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*domain.PaymentIntent), nil
	}
}

func (p paymentIntentDo) FirstOrCreate() (*domain.PaymentIntent, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*domain.PaymentIntent), nil
	}
}

func (p paymentIntentDo) FindByPage(offset int, limit int) (result []*domain.PaymentIntent, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p paymentIntentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p paymentIntentDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p paymentIntentDo) Delete(models ...*domain.PaymentIntent) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *paymentIntentDo) withDO(do gen.Dao) *paymentIntentDo {
	p.DO = *do.(*gen.DO)
	return p
}
