// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/weouc-plus/campus-platform/internal/modules/trade/domain"
)

func newOrderTransition(db *gorm.DB, opts ...gen.DOOption) orderTransition {
	_orderTransition := orderTransition{}

	_orderTransition.orderTransitionDo.UseDB(db, opts...)
	_orderTransition.orderTransitionDo.UseModel(&domain.OrderTransition{})

	tableName := _orderTransition.orderTransitionDo.TableName()
	_orderTransition.ALL = field.NewAsterisk(tableName)
	_orderTransition.ID = field.NewUint64(tableName, "id")
	_orderTransition.OrderId = field.NewUint64(tableName, "order_id")
	_orderTransition.FromStatus = field.NewString(tableName, "from_status")
	_orderTransition.ToStatus = field.NewString(tableName, "to_status")
	_orderTransition.ActorType = field.NewString(tableName, "actor_type")
	_orderTransition.ActorId = field.NewUint64(tableName, "actor_id")
	_orderTransition.ReasonCode = field.NewString(tableName, "reason_code")
	_orderTransition.ReasonText = field.NewString(tableName, "reason_text")
	_orderTransition.IdempotencyKey = field.NewString(tableName, "idempotency_key")
	_orderTransition.CreatedAt = field.NewTime(tableName, "created_at")
	_orderTransition.UpdatedAt = field.NewTime(tableName, "updated_at")

	_orderTransition.fillFieldMap()

	return _orderTransition
}

type orderTransition struct {
	orderTransitionDo orderTransitionDo

	ALL            field.Asterisk
	ID             field.Uint64
	OrderId        field.Uint64
	FromStatus     field.String
	ToStatus       field.String
	ActorType      field.String
	ActorId        field.Uint64
	ReasonCode     field.String
	ReasonText     field.String
	IdempotencyKey field.String
	CreatedAt      field.Time
	UpdatedAt      field.Time

	fieldMap map[string]field.Expr
}

func (o orderTransition) Table(newTableName string) *orderTransition {
	o.orderTransitionDo.UseTable(newTableName)
	return o.updateTableName(newTableName)
}

func (o orderTransition) As(alias string) *orderTransition {
	o.orderTransitionDo.DO = *(o.orderTransitionDo.As(alias).(*gen.DO))
	return o.updateTableName(alias)
}

func (o *orderTransition) updateTableName(table string) *orderTransition {
	o.ALL = field.NewAsterisk(table)
	o.ID = field.NewUint64(table, "id")
	o.OrderId = field.NewUint64(table, "order_id")
	o.FromStatus = field.NewString(table, "from_status")
	o.ToStatus = field.NewString(table, "to_status")
	o.ActorType = field.NewString(table, "actor_type")
	o.ActorId = field.NewUint64(table, "actor_id")
	o.ReasonCode = field.NewString(table, "reason_code")
	o.ReasonText = field.NewString(table, "reason_text")
	o.IdempotencyKey = field.NewString(table, "idempotency_key")
	o.CreatedAt = field.NewTime(table, "created_at")
	o.UpdatedAt = field.NewTime(table, "updated_at")

	o.fillFieldMap()

	return o
}

func (o *orderTransition) WithContext(ctx context.Context) IOrderTransitionDo {
	return o.orderTransitionDo.WithContext(ctx)
}

func (o orderTransition) TableName() string { return o.orderTransitionDo.TableName() }

func (o orderTransition) Alias() string { return o.orderTransitionDo.Alias() }

func (o orderTransition) Columns(cols ...field.Expr) gen.Columns {
	return o.orderTransitionDo.Columns(cols...)
}

func (o *orderTransition) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := o.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (o *orderTransition) fillFieldMap() {
	o.fieldMap = make(map[string]field.Expr, 11)
	o.fieldMap["id"] = o.ID
	o.fieldMap["order_id"] = o.OrderId
	o.fieldMap["from_status"] = o.FromStatus
	o.fieldMap["to_status"] = o.ToStatus
	o.fieldMap["actor_type"] = o.ActorType
	o.fieldMap["actor_id"] = o.ActorId
	o.fieldMap["reason_code"] = o.ReasonCode
	o.fieldMap["reason_text"] = o.ReasonText
	o.fieldMap["idempotency_key"] = o.IdempotencyKey
	o.fieldMap["created_at"] = o.CreatedAt
	o.fieldMap["updated_at"] = o.UpdatedAt
}

func (o orderTransition) clone(db *gorm.DB) orderTransition {
	o.orderTransitionDo.ReplaceConnPool(db.Statement.ConnPool)
	return o
}

func (o orderTransition) replaceDB(db *gorm.DB) orderTransition {
	o.orderTransitionDo.ReplaceDB(db)
	return o
}

type orderTransitionDo struct{ gen.DO }

type IOrderTransitionDo interface {
	gen.SubQuery
	Debug() IOrderTransitionDo
	WithContext(ctx context.Context) IOrderTransitionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IOrderTransitionDo
	WriteDB() IOrderTransitionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IOrderTransitionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IOrderTransitionDo
	Not(conds ...gen.Condition) IOrderTransitionDo
	Or(conds ...gen.Condition) IOrderTransitionDo
	Select(conds ...field.Expr) IOrderTransitionDo
	Where(conds ...gen.Condition) IOrderTransitionDo
	Order(conds ...field.Expr) IOrderTransitionDo
	Distinct(cols ...field.Expr) IOrderTransitionDo
	Omit(cols ...field.Expr) IOrderTransitionDo
	Join(table schema.Tabler, on ...field.Expr) IOrderTransitionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IOrderTransitionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IOrderTransitionDo
	Group(cols ...field.Expr) IOrderTransitionDo
	Having(conds ...gen.Condition) IOrderTransitionDo
	Limit(limit int) IOrderTransitionDo
	Offset(offset int) IOrderTransitionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IOrderTransitionDo
	Unscoped() IOrderTransitionDo
	Create(values ...*domain.OrderTransition) error
	CreateInBatches(values []*domain.OrderTransition, batchSize int) error
	Save(values ...*domain.OrderTransition) error
	First() (*domain.OrderTransition, error)
	Take() (*domain.OrderTransition, error)
	Last() (*domain.OrderTransition, error)
	Find() ([]*domain.OrderTransition, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.OrderTransition, err error)
	FindInBatches(result *[]*domain.OrderTransition, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*domain.OrderTransition) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IOrderTransitionDo
	Assign(attrs ...field.AssignExpr) IOrderTransitionDo
	Joins(fields ...field.RelationField) IOrderTransitionDo
	Preload(fields ...field.RelationField) IOrderTransitionDo
	FirstOrInit() (*domain.OrderTransition, error)
	FirstOrCreate() (*domain.OrderTransition, error)
	FindByPage(offset int, limit int) (result []*domain.OrderTransition, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IOrderTransitionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (o orderTransitionDo) Debug() IOrderTransitionDo {
	return o.withDO(o.DO.Debug())
}

func (o orderTransitionDo) WithContext(ctx context.Context) IOrderTransitionDo {
	return o.withDO(o.DO.WithContext(ctx))
}

func (o orderTransitionDo) ReadDB() IOrderTransitionDo {
	return o.Clauses(dbresolver.Read)
}

func (o orderTransitionDo) WriteDB() IOrderTransitionDo {
	return o.Clauses(dbresolver.Write)
}

func (o orderTransitionDo) Session(config *gorm.Session) IOrderTransitionDo {
	return o.withDO(o.DO.Session(config))
}

func (o orderTransitionDo) Clauses(conds ...clause.Expression) IOrderTransitionDo {
	return o.withDO(o.DO.Clauses(conds...))
}

func (o orderTransitionDo) Returning(value interface{}, columns ...string) IOrderTransitionDo {
	return o.withDO(o.DO.Returning(value, columns...))
}

func (o orderTransitionDo) Not(conds ...gen.Condition) IOrderTransitionDo {
	return o.withDO(o.DO.Not(conds...))
}

func (o orderTransitionDo) Or(conds ...gen.Condition) IOrderTransitionDo {
	return o.withDO(o.DO.Or(conds...))
}

func (o orderTransitionDo) Select(conds ...field.Expr) IOrderTransitionDo {
	return o.withDO(o.DO.Select(conds...))
}

func (o orderTransitionDo) Where(conds ...gen.Condition) IOrderTransitionDo {
	return o.withDO(o.DO.Where(conds...))
}

func (o orderTransitionDo) Order(conds ...field.Expr) IOrderTransitionDo {
	return o.withDO(o.DO.Order(conds...))
}

func (o orderTransitionDo) Distinct(cols ...field.Expr) IOrderTransitionDo {
	return o.withDO(o.DO.Distinct(cols...))
}

func (o orderTransitionDo) Omit(cols ...field.Expr) IOrderTransitionDo {
	return o.withDO(o.DO.Omit(cols...))
}

func (o orderTransitionDo) Join(table schema.Tabler, on ...field.Expr) IOrderTransitionDo {
	return o.withDO(o.DO.Join(table, on...))
}

func (o orderTransitionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IOrderTransitionDo {
	return o.withDO(o.DO.LeftJoin(table, on...))
}

func (o orderTransitionDo) RightJoin(table schema.Tabler, on ...field.Expr) IOrderTransitionDo {
	return o.withDO(o.DO.RightJoin(table, on...))
}

func (o orderTransitionDo) Group(cols ...field.Expr) IOrderTransitionDo {
	return o.withDO(o.DO.Group(cols...))
}

func (o orderTransitionDo) Having(conds ...gen.Condition) IOrderTransitionDo {
	return o.withDO(o.DO.Having(conds...))
}

func (o orderTransitionDo) Limit(limit int) IOrderTransitionDo {
	return o.withDO(o.DO.Limit(limit))
}

func (o orderTransitionDo) Offset(offset int) IOrderTransitionDo {
	return o.withDO(o.DO.Offset(offset))
}

func (o orderTransitionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IOrderTransitionDo {
	return o.withDO(o.DO.Scopes(funcs...))
}

func (o orderTransitionDo) Unscoped() IOrderTransitionDo {
	return o.withDO(o.DO.Unscoped())
}

func (o orderTransitionDo) Create(values ...*domain.OrderTransition) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Create(values)
}

func (o orderTransitionDo) CreateInBatches(values []*domain.OrderTransition, batchSize int) error {
	return o.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (o orderTransitionDo) Save(values ...*domain.OrderTransition) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Save(values)
}

func (o orderTransitionDo) First() (*domain.OrderTransition, error) {
	if result, err := o.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*domain.OrderTransition), nil
	}
}

func (o orderTransitionDo) Take() (*domain.OrderTransition, error) {
	if result, err := o.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*domain.OrderTransition), nil
	}
}

func (o orderTransitionDo) Last() (*domain.OrderTransition, error) {
	if result, err := o.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*domain.OrderTransition), nil
	}
}

func (o orderTransitionDo) Find() ([]*domain.OrderTransition, error) {
	result, err := o.DO.Find()
	return result.([]*domain.OrderTransition), err
}

func (o orderTransitionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.OrderTransition, err error) {
	buf := make([]*domain.OrderTransition, 0, batchSize)
	err = o.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (o orderTransitionDo) FindInBatches(result *[]*domain.OrderTransition, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return o.DO.FindInBatches(result, batchSize, fc)
}

func (o orderTransitionDo) Attrs(attrs ...field.AssignExpr) IOrderTransitionDo {
	return o.withDO(o.DO.Attrs(attrs...))
}

func (o orderTransitionDo) Assign(attrs ...field.AssignExpr) IOrderTransitionDo {
	return o.withDO(o.DO.Assign(attrs...))
}

func (o orderTransitionDo) Joins(fields ...field.RelationField) IOrderTransitionDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Joins(_f))
	}
	return &o
}

func (o orderTransitionDo) Preload(fields ...field.RelationField) IOrderTransitionDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Preload(_f))
	}
	return &o
}

func (o orderTransitionDo) FirstOrInit() (*domain.OrderTransition, error) {
	if result, err := o.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*domain.OrderTransition), nil
	}
}

func (o orderTransitionDo) FirstOrCreate() (*domain.OrderTransition, error) {
	if result, err := o.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*domain.OrderTransition), nil
	}
}

func (o orderTransitionDo) FindByPage(offset int, limit int) (result []*domain.OrderTransition, count int64, err error) {
	result, err = o.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = o.Offset(-1).Limit(-1).Count()
	return
}

func (o orderTransitionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = o.Count()
	if err != nil {
		return
	}

	err = o.Offset(offset).Limit(limit).Scan(result)
	return
}

func (o orderTransitionDo) Scan(result interface{}) (err error) {
	return o.DO.Scan(result)
}

func (o orderTransitionDo) Delete(models ...*domain.OrderTransition) (result gen.ResultInfo, err error) {
	return o.DO.Delete(models)
}

func (o *orderTransitionDo) withDO(do gen.Dao) *orderTransitionDo {
	o.DO = *do.(*gen.DO)
	return o
}
