package generator

import (
	"bytes"
	"context"
	"embed"
	"encoding/json"
	"errors"
	"fmt"
	"go/format"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"text/template"
)

const generatedHeader = "Code generated by campusctl from a module schema. DO NOT EDIT."

// ErrDrift indicates that generated output differs from the checked-in files.
var ErrDrift = errors.New("generated module files are out of date")

//go:embed templates/*.tmpl
var templateFiles embed.FS

// Options controls module generation.
type Options struct {
	Root       string
	Source     string
	Check      bool
	ModulePath string
}

// Result summarizes a validation or generation operation.
type Result struct {
	Module  string
	Entity  string
	Files   int
	Changed []string
	Managed []string
}

type outputFile struct {
	path     string
	content  []byte
	preserve bool
}

type registry struct {
	Version int          `json:"version"`
	Modules []ModuleInfo `json:"modules"`
}

// ModuleInfo is one stable entry in the generated module registry.
type ModuleInfo struct {
	Name     string   `json:"name"`
	Entity   string   `json:"entity"`
	Entities []string `json:"entities,omitempty"`
	Schema   string   `json:"schema"`
}

type templateData struct {
	Schema
	Header     string
	ModulePath string
	Source     string
	Routes     []apiRoute
	Modules    []ModuleInfo
}

type apiRoute struct {
	Path    string
	Methods []apiOperation
}

type apiOperation struct {
	Method      string
	MethodLower string
	OperationID string
	Permission  string
}

// Generate renders one normalized schema and either writes it or checks drift.
func Generate(ctx context.Context, schema Schema, options Options) (Result, error) {
	if err := ctx.Err(); err != nil {
		return Result{}, err
	}
	if err := schema.Normalize(); err != nil {
		return Result{}, err
	}
	root, err := filepath.Abs(options.Root)
	if err != nil {
		return Result{}, fmt.Errorf("resolve repository root: %w", err)
	}
	if options.ModulePath == "" {
		options.ModulePath = "github.com/weouc-plus/campus-platform"
	}
	files, err := plan(root, schema, options)
	if err != nil {
		return Result{}, err
	}
	result := Result{Module: schema.Module, Entity: schema.Entity.Name, Files: len(files)}
	for _, file := range files {
		if err = ctx.Err(); err != nil {
			return Result{}, err
		}
		current, readErr := os.ReadFile(file.path)
		exists := readErr == nil
		if readErr != nil && !errors.Is(readErr, fs.ErrNotExist) {
			return Result{}, fmt.Errorf("read generated output %s: %w", file.path, readErr)
		}
		if file.preserve && exists {
			continue
		}
		if !file.preserve {
			rel, relErr := filepath.Rel(root, file.path)
			if relErr != nil {
				return Result{}, fmt.Errorf("format managed path: %w", relErr)
			}
			result.Managed = append(result.Managed, filepath.ToSlash(rel))
		}
		if exists && bytes.Equal(current, file.content) {
			continue
		}
		rel, relErr := filepath.Rel(root, file.path)
		if relErr != nil {
			return Result{}, fmt.Errorf("format generated path: %w", relErr)
		}
		result.Changed = append(result.Changed, filepath.ToSlash(rel))
	}
	sort.Strings(result.Managed)
	sort.Strings(result.Changed)
	if options.Check {
		if len(result.Changed) > 0 {
			return result, fmt.Errorf("%w: %s", ErrDrift, strings.Join(result.Changed, ", "))
		}
		return result, nil
	}
	for _, file := range files {
		if file.preserve {
			if _, statErr := os.Stat(file.path); statErr == nil {
				continue
			} else if !errors.Is(statErr, fs.ErrNotExist) {
				return Result{}, fmt.Errorf("inspect preserved output %s: %w", file.path, statErr)
			}
		}
		if err = atomicWrite(file.path, file.content); err != nil {
			return Result{}, err
		}
	}
	return result, nil
}

// ListModules reads the deterministic module registry from a repository root.
func ListModules(ctx context.Context, root string) ([]ModuleInfo, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	path, err := safeJoin(root, ".agent/modules.json")
	if err != nil {
		return nil, err
	}
	// #nosec G304 -- safeJoin confines the registry to the repository root.
	data, err := os.ReadFile(path)
	if errors.Is(err, fs.ErrNotExist) {
		return []ModuleInfo{}, nil
	}
	if err != nil {
		return nil, fmt.Errorf("read module registry: %w", err)
	}
	var value registry
	if err = json.Unmarshal(data, &value); err != nil {
		return nil, fmt.Errorf("decode module registry: %w", err)
	}
	if value.Version != RegistryVersion {
		return nil, fmt.Errorf("unsupported module registry version %d", value.Version)
	}
	sort.Slice(value.Modules, func(i, j int) bool { return value.Modules[i].Name < value.Modules[j].Name })
	return value.Modules, nil
}

// DiscoverModules builds the module registry from schemas/*.yaml, making schema
// presence the source of truth for additions, renames and deletions.
func DiscoverModules(ctx context.Context, root string) ([]ModuleInfo, error) {
	directory, err := safeJoin(root, "schemas")
	if err != nil {
		return nil, err
	}
	entries, err := os.ReadDir(directory)
	if err != nil {
		return nil, fmt.Errorf("read schema directory: %w", err)
	}
	modules := make([]ModuleInfo, 0, len(entries))
	seen := map[string]string{}
	for _, entry := range entries {
		if err = ctx.Err(); err != nil {
			return nil, err
		}
		if entry.IsDir() || filepath.Ext(entry.Name()) != ".yaml" {
			continue
		}
		relative := filepath.ToSlash(filepath.Join("schemas", entry.Name()))
		schema, loadErr := Load(ctx, filepath.Join(directory, entry.Name()))
		if loadErr != nil {
			return nil, loadErr
		}
		if previous, ok := seen[schema.Module]; ok {
			return nil, fmt.Errorf("module %q is declared by both %s and %s", schema.Module, previous, relative)
		}
		seen[schema.Module] = relative
		entities := []string{schema.Entity.Name}
		if schema.Version == SchemaVersion {
			entities = make([]string, len(schema.Entities))
			for index := range schema.Entities {
				entities[index] = schema.Entities[index].Name
			}
		}
		modules = append(modules, ModuleInfo{Name: schema.Module, Entity: schema.Entity.Name, Entities: entities, Schema: relative})
	}
	sort.Slice(modules, func(i, j int) bool { return modules[i].Name < modules[j].Name })
	return modules, nil
}

// SyncModuleRegistry atomically writes or checks an exact discovered registry.
func SyncModuleRegistry(ctx context.Context, root string, modules []ModuleInfo, check bool) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	path, err := safeJoin(root, ".agent/modules.json")
	if err != nil {
		return err
	}
	modules = append([]ModuleInfo(nil), modules...)
	sort.Slice(modules, func(i, j int) bool { return modules[i].Name < modules[j].Name })
	content, err := json.MarshalIndent(registry{Version: RegistryVersion, Modules: modules}, "", "  ")
	if err != nil {
		return fmt.Errorf("encode module registry: %w", err)
	}
	content = append(content, '\n')
	current, readErr := os.ReadFile(path) // #nosec G304 -- safeJoin confines the registry to the repository root.
	if check {
		if readErr != nil || !bytes.Equal(current, content) {
			return fmt.Errorf("%w: .agent/modules.json", ErrDrift)
		}
		return nil
	}
	return atomicWrite(path, content)
}

func plan(root string, schema Schema, options Options) ([]outputFile, error) {
	registryValue, registryFile, err := planRegistry(root, schema, options.Source)
	if err != nil {
		return nil, err
	}
	data := templateData{
		Schema: schema, Header: generatedHeader, ModulePath: options.ModulePath,
		Source: filepath.ToSlash(options.Source), Routes: routes(schema.Permissions), Modules: registryValue.Modules,
	}
	specs := []struct {
		template string
		path     string
		preserve bool
		goFile   bool
	}{
		{"repository.go.tmpl", "internal/modules/" + schema.Module + "/domain/repository.gen.go", false, true},
		{"rule.go.tmpl", "internal/modules/" + schema.Module + "/domain/rule.go", true, true},
		{"service.go.tmpl", "internal/modules/" + schema.Module + "/application/service.gen.go", false, true},
		{"mysql_repository.go.tmpl", "internal/modules/" + schema.Module + "/infrastructure/repository.gen.go", false, true},
		{"handler.go.tmpl", "internal/modules/" + schema.Module + "/api/handler.gen.go", false, true},
		{"httpapi_adapter.go.tmpl", "internal/api/httpapi/" + schema.Module + "_adapter.gen.go", false, true},
		{"module.go.tmpl", "internal/modules/" + schema.Module + "/module.go", false, true},
		{"module_test.go.tmpl", "internal/modules/" + schema.Module + "/domain/rule_test.go", true, true},
		{"openapi.yaml.tmpl", "api/modules/" + schema.Module + ".yaml", false, false},
		{"gorm_modules.go.tmpl", "internal/infrastructure/mysql/generator/modules.gen.go", false, true},
	}
	outputs := make([]outputFile, 0, len(specs)+2)
	entities := schema.Entities
	if schema.Version == 1 {
		entities = []Entity{schema.Entity}
	}
	for _, entity := range entities {
		entityData := data
		entityData.Entity = entity
		content, renderErr := render("entity.go.tmpl", entityData)
		if renderErr != nil {
			return nil, renderErr
		}
		content, renderErr = format.Source(content)
		if renderErr != nil {
			return nil, fmt.Errorf("format entity %s: %w", entity.Name, renderErr)
		}
		name := "entity.gen.go"
		if schema.Version == 2 {
			name = entity.Table + ".gen.go"
		}
		path, joinErr := safeJoin(root, "internal/modules/"+schema.Module+"/domain/"+name)
		if joinErr != nil {
			return nil, joinErr
		}
		outputs = append(outputs, outputFile{path: path, content: content})
	}
	for _, spec := range specs {
		content, err := render(spec.template, data)
		if err != nil {
			return nil, err
		}
		if spec.goFile {
			content, err = format.Source(content)
			if err != nil {
				return nil, fmt.Errorf("format template %s: %w", spec.template, err)
			}
		}
		path, err := safeJoin(root, spec.path)
		if err != nil {
			return nil, err
		}
		outputs = append(outputs, outputFile{path: path, content: content, preserve: spec.preserve})
	}
	permissionData, err := json.MarshalIndent(struct {
		Module      string       `json:"module"`
		Permissions []Permission `json:"permissions"`
	}{schema.Module, schema.Permissions}, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("encode permission manifest: %w", err)
	}
	permissionData = append(permissionData, '\n')
	permissionPath, err := safeJoin(root, "permissions/modules/"+schema.Module+".json")
	if err != nil {
		return nil, err
	}
	outputs = append(outputs, outputFile{path: permissionPath, content: permissionData})
	outputs = append(outputs, registryFile)
	return outputs, nil
}

func planRegistry(root string, schema Schema, source string) (registry, outputFile, error) {
	path, err := safeJoin(root, ".agent/modules.json")
	if err != nil {
		return registry{}, outputFile{}, err
	}
	value := registry{Version: RegistryVersion, Modules: []ModuleInfo{}}
	// #nosec G304 -- safeJoin confines the registry to the repository root.
	if data, readErr := os.ReadFile(path); readErr == nil {
		if err = json.Unmarshal(data, &value); err != nil {
			return registry{}, outputFile{}, fmt.Errorf("decode module registry: %w", err)
		}
	} else if !errors.Is(readErr, fs.ErrNotExist) {
		return registry{}, outputFile{}, fmt.Errorf("read module registry: %w", readErr)
	}
	if value.Version != RegistryVersion {
		return registry{}, outputFile{}, fmt.Errorf("unsupported module registry version %d", value.Version)
	}
	entityNames := []string{schema.Entity.Name}
	if schema.Version == 2 {
		entityNames = make([]string, len(schema.Entities))
		for i := range schema.Entities {
			entityNames[i] = schema.Entities[i].Name
		}
	}
	entry := ModuleInfo{Name: schema.Module, Entity: schema.Entity.Name, Entities: entityNames, Schema: filepath.ToSlash(source)}
	found := false
	for i := range value.Modules {
		if value.Modules[i].Name == schema.Module {
			value.Modules[i] = entry
			found = true
		}
	}
	if !found {
		value.Modules = append(value.Modules, entry)
	}
	sort.Slice(value.Modules, func(i, j int) bool { return value.Modules[i].Name < value.Modules[j].Name })
	content, err := json.MarshalIndent(value, "", "  ")
	if err != nil {
		return registry{}, outputFile{}, fmt.Errorf("encode module registry: %w", err)
	}
	return value, outputFile{path: path, content: append(content, '\n')}, nil
}

func render(name string, data templateData) ([]byte, error) {
	raw, err := templateFiles.ReadFile("templates/" + name)
	if err != nil {
		return nil, fmt.Errorf("read template %s: %w", name, err)
	}
	functions := template.FuncMap{
		"lower": strings.ToLower,
		"lowerFirst": func(value string) string {
			if value == "" {
				return value
			}
			return strings.ToLower(value[:1]) + value[1:]
		},
		"pathParams": func(path string) []string {
			matches := regexp.MustCompile(`\{([A-Za-z][A-Za-z0-9_]*)\}`).FindAllStringSubmatch(path, -1)
			values := make([]string, 0, len(matches))
			for _, match := range matches {
				values = append(values, match[1])
			}
			return values
		},
		"has": func(values []string, target string) bool {
			for _, value := range values {
				if value == target {
					return true
				}
			}
			return false
		},
	}
	parsed, err := template.New(name).Funcs(functions).Option("missingkey=error").Parse(string(raw))
	if err != nil {
		return nil, fmt.Errorf("parse template %s: %w", name, err)
	}
	var buffer bytes.Buffer
	if err = parsed.Execute(&buffer, data); err != nil {
		return nil, fmt.Errorf("render template %s: %w", name, err)
	}
	return buffer.Bytes(), nil
}

func routes(permissions []Permission) []apiRoute {
	byPath := map[string][]apiOperation{}
	for _, permission := range permissions {
		for _, method := range permission.Methods {
			operationID := strings.ReplaceAll(permission.Name, ":", "_") + "_" + strings.ToLower(method)
			byPath[permission.Path] = append(byPath[permission.Path], apiOperation{
				Method: method, MethodLower: strings.ToLower(method), OperationID: operationID, Permission: permission.Name,
			})
		}
	}
	paths := make([]string, 0, len(byPath))
	for path := range byPath {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	out := make([]apiRoute, 0, len(paths))
	for _, path := range paths {
		operations := byPath[path]
		sort.Slice(operations, func(i, j int) bool { return operations[i].Method < operations[j].Method })
		out = append(out, apiRoute{Path: path, Methods: operations})
	}
	return out
}

func safeJoin(root, relative string) (string, error) {
	if filepath.IsAbs(relative) {
		return "", fmt.Errorf("absolute output path is forbidden: %s", relative)
	}
	root, err := filepath.Abs(root)
	if err != nil {
		return "", fmt.Errorf("resolve output root: %w", err)
	}
	joined := filepath.Clean(filepath.Join(root, filepath.FromSlash(relative)))
	rel, err := filepath.Rel(root, joined)
	if err != nil || rel == ".." || strings.HasPrefix(rel, ".."+string(filepath.Separator)) {
		return "", fmt.Errorf("output path escapes repository root: %s", relative)
	}
	return joined, nil
}

func atomicWrite(path string, content []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		return fmt.Errorf("create generated directory: %w", err)
	}
	temporary, err := os.CreateTemp(filepath.Dir(path), ".campus-generate-*")
	if err != nil {
		return fmt.Errorf("create generated temporary file: %w", err)
	}
	temporaryName := temporary.Name()
	defer func() { _ = os.Remove(temporaryName) }()
	if err = temporary.Chmod(0o644); err != nil {
		_ = temporary.Close()
		return fmt.Errorf("set generated file mode: %w", err)
	}
	if _, err = temporary.Write(content); err != nil {
		_ = temporary.Close()
		return fmt.Errorf("write generated temporary file: %w", err)
	}
	if err = temporary.Close(); err != nil {
		return fmt.Errorf("close generated temporary file: %w", err)
	}
	if err = os.Rename(temporaryName, path); err != nil {
		return fmt.Errorf("replace generated file: %w", err)
	}
	return nil
}
