// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/campus_circle.yaml

// Package campus_circle wires the generated module components.
package campus_circle

import (
	"github.com/weouc-plus/campus-platform/internal/modules/campus_circle/api"
	"github.com/weouc-plus/campus-platform/internal/modules/campus_circle/application"
	"github.com/weouc-plus/campus-platform/internal/modules/campus_circle/infrastructure"
	"gorm.io/gorm"
)

// Module contains the public runtime components of the campus_circle module.
type Module struct{ Handler *api.Handler }

// New creates a campus_circle module from shared infrastructure.
func New(db *gorm.DB) *Module {
	repository := infrastructure.NewRepository(db)
	service := application.NewService(repository)
	return &Module{Handler: api.NewHandler(service)}
}
