// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/campus_circle.yaml

package domain

import "time"

// CampusCircleSection is the persistent domain entity for the campus_circle module.
type CampusCircleSection struct {
	ID          uint64    `gorm:"primaryKey;autoIncrement" json:"id"`
	ParentId    *uint64   `gorm:"column:parent_id;index" json:"parent_id"`
	Slug        string    `gorm:"column:slug;not null;uniqueIndex" json:"slug"`
	Name        string    `gorm:"column:name;not null" json:"name"`
	Description *string   `gorm:"column:description" json:"description"`
	IconUrl     *string   `gorm:"column:icon_url" json:"icon_url"`
	CoverUrl    *string   `gorm:"column:cover_url" json:"cover_url"`
	SortOrder   int64     `gorm:"column:sort_order;not null" json:"sort_order"`
	Status      string    `gorm:"column:status;not null;index" json:"status"`
	CreatedBy   uint64    `gorm:"column:created_by;not null" json:"created_by"`
	UpdatedBy   uint64    `gorm:"column:updated_by;not null" json:"updated_by"`
	Version     uint64    `gorm:"column:version;not null" json:"version"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// TableName returns the schema-controlled database table.
func (CampusCircleSection) TableName() string { return "campus_circle_sections" }
