// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/campus_circle.yaml

package domain

import "time"

// CampusCirclePost is the persistent domain entity for the campus_circle module.
type CampusCirclePost struct {
	ID           uint64     `gorm:"primaryKey;autoIncrement" json:"id"`
	SectionId    uint64     `gorm:"column:section_id;not null;index" json:"section_id"`
	AuthorId     uint64     `gorm:"column:author_id;not null;index" json:"author_id"`
	Title        *string    `gorm:"column:title" json:"title"`
	Content      *string    `gorm:"column:content" json:"content"`
	Status       string     `gorm:"column:status;not null;index" json:"status"`
	ReviewReason *string    `gorm:"column:review_reason" json:"review_reason"`
	ReviewedBy   *uint64    `gorm:"column:reviewed_by" json:"reviewed_by"`
	ReviewedAt   *time.Time `gorm:"column:reviewed_at" json:"reviewed_at"`
	PublishedAt  *time.Time `gorm:"column:published_at" json:"published_at"`
	Version      uint64     `gorm:"column:version;not null" json:"version"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
}

// TableName returns the schema-controlled database table.
func (CampusCirclePost) TableName() string { return "campus_circle_posts" }
