// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/campus_circle.yaml

package domain

import "context"

// Repository defines persistence operations enabled by the module schema.
type Repository interface {
	Create(context.Context, *CampusCircleSection) error
	Get(context.Context, uint64) (*CampusCircleSection, error)
	List(context.Context, int, int) ([]CampusCircleSection, int64, error)
	Update(context.Context, *CampusCircleSection) error
}
