// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/carpool.yaml

// Package application coordinates carpool use cases.
package application

import (
	"context"

	"github.com/weouc-plus/campus-platform/internal/modules/carpool/domain"
)

// Service coordinates generated CRUD operations and handwritten domain rules.
type Service struct{ repository domain.Repository }

// NewService creates a carpool application service.
func NewService(repository domain.Repository) *Service { return &Service{repository: repository} }

// Create persists a new Trip.
func (s *Service) Create(ctx context.Context, value *domain.Trip) error {
	return s.repository.Create(ctx, value)
}

// Get returns one Trip by ID.
func (s *Service) Get(ctx context.Context, id uint64) (*domain.Trip, error) {
	return s.repository.Get(ctx, id)
}

// List returns a page of Trip values.
func (s *Service) List(ctx context.Context, page, pageSize int) ([]domain.Trip, int64, error) {
	return s.repository.List(ctx, page, pageSize)
}

// Update persists an existing Trip.
func (s *Service) Update(ctx context.Context, value *domain.Trip) error {
	return s.repository.Update(ctx, value)
}
