// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/academic_verification.yaml

package domain

import "time"

// AcademicVerificationRequest is the persistent domain entity for the academic_verification module.
type AcademicVerificationRequest struct {
	ID           uint64     `gorm:"primaryKey;autoIncrement" json:"id"`
	UserId       uint64     `gorm:"column:user_id;not null;index" json:"user_id"`
	StudentNo    string     `gorm:"column:student_no;not null;index" json:"student_no"`
	RealName     string     `gorm:"column:real_name;not null" json:"real_name"`
	Method       string     `gorm:"column:method;not null" json:"method"`
	MaterialId   *uint64    `gorm:"column:material_id" json:"material_id"`
	Status       string     `gorm:"column:status;not null;index" json:"status"`
	ReviewReason *string    `gorm:"column:review_reason" json:"review_reason"`
	ReviewedBy   *uint64    `gorm:"column:reviewed_by" json:"reviewed_by"`
	ReviewedAt   *time.Time `gorm:"column:reviewed_at" json:"reviewed_at"`
	Version      uint64     `gorm:"column:version;not null" json:"version"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
}

// TableName returns the schema-controlled database table.
func (AcademicVerificationRequest) TableName() string { return "academic_verification_requests" }
