// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/academic_verification.yaml

package domain

import "time"

// AcademicIdentity is the persistent domain entity for the academic_verification module.
type AcademicIdentity struct {
	ID           uint64     `gorm:"primaryKey;autoIncrement" json:"id"`
	UserId       uint64     `gorm:"column:user_id;not null;uniqueIndex" json:"user_id"`
	StudentNo    string     `gorm:"column:student_no;not null;uniqueIndex" json:"student_no"`
	RealName     string     `gorm:"column:real_name;not null" json:"real_name"`
	Method       string     `gorm:"column:method;not null" json:"method"`
	Status       string     `gorm:"column:status;not null;index" json:"status"`
	VerifiedAt   time.Time  `gorm:"column:verified_at;not null" json:"verified_at"`
	RevokedAt    *time.Time `gorm:"column:revoked_at" json:"revoked_at"`
	RevokeReason *string    `gorm:"column:revoke_reason" json:"revoke_reason"`
	Version      uint64     `gorm:"column:version;not null" json:"version"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
}

// TableName returns the schema-controlled database table.
func (AcademicIdentity) TableName() string { return "academic_identities" }
