// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/academic_verification.yaml

package domain

import "context"

// Repository defines persistence operations enabled by the module schema.
type Repository interface {
	Create(context.Context, *AcademicIdentity) error
	Get(context.Context, uint64) (*AcademicIdentity, error)
	List(context.Context, int, int) ([]AcademicIdentity, int64, error)
	Update(context.Context, *AcademicIdentity) error
}
